### ISSUE TITLE
You must set an arbitrary default cookie value in order to use the cookieJar to set a cookie

### ISSUE THREAD

**Issue by Shazwazza** [artilleryio/artillery#1035]
With the latest 1.7.x version the cookie jar (which is a [ToughCookie](https://github.com/salesforce/tough-cookie) instance) will not work unless it is specifically enabled. This means that if you have any JS that assigns a cookie to the request it will not work unless a previous response had a cookie, or your config has an explicit cookie defined. This is different than the prev 1.6.x version.

It's due to this code here: https://github.com/artilleryio/artillery/blob/v1.6.x/core/lib/engine_http.js#L262

To work around this you need to set a default cookie value, even if it's empty so the cookieJar is enabled. You can do this at top level of your config like:

```yml
config:
  defaults:
    cookie:
      MY_COOKIE: ""
```

or at request levels, etc...

If you do this, then the cookieJar is enabled which is this code: https://github.com/artilleryio/artillery/blob/v1.6.x/core/lib/engine_http.js#L653

There's another work around, which is to forcefully enable it in the beginRequest method like:

```js
if (!context._enableCookieJar) {
    context._enableCookieJar = true;
    requestParams.cookieJar = context._jar;
}
```

I think it may be clearer be able to explicitly enable this in config, something like

```yml
config:
  defaults:
    cookieJar: "always"
```

and perhaps you could have "auto" or even "never" (not sure why you'd want that, but maybe). Could be some other options like that but is a bit more clear that you just want to be able to dynamically set cookies in a request without having to declare an empty cookie.

**Comment by Shazwazza** [comment]
(I also mostly wanted to report this in case other people are searching work arounds for this)

**Comment by hassy** [comment]
Thank you for opening the issue @Shazwazza and for taking the time to investigate the cause! We can treat this as a regression - cookies should just work and be enabled by default.
