### ISSUE TITLE
artillery-plugin-expect doesn't exit with code 1

### ISSUE THREAD

**Issue by Shazwazza** [artilleryio/artillery#1046]
Hi, I was trying to use the `artillery-plugin-expect` plugin to use the expect status code functionality. I am using artillery 1.7.2 and the latest version of this plugin.

I can get the plugin to validate that the expected status code was not met, however the exit code for artillery is still 0 instead of 1. I was looking at the code here and can see that its trying to set a 1 exit code: 
https://github.com/artilleryio/artillery-plugin-expect/blob/7bbbe389cafec311b50433cbf3659c7c8a25e060/index.js#L134

But that doesn't seem to actually cause the exit code to be 1, it still exits with 0 even though it does list the request as being 'not ok'

**Comment by hassy** [comment]
👋 @Shazwazza. Yep that only works with v2.0. It's available as a dev release at the moment if you want to give it a go: `npm install -g artillery@dev`. We're hoping to have a stable release soon😄
