### ISSUE TITLE
Is there a way to test server sent events streams?

### ISSUE THREAD

**Issue by nvartolomei** [artilleryio/artillery#107]
Now just sending get requests, but actually waiting for data.

**Comment by hassy** [comment]
@nvartolomei Not yet, but it's on a wishlist. What sort of functionality would you need for your use-case?

**Comment by nvartolomei** [comment]
I'm not very familiar with artillery, neither with SSE.
But from my perspective the only thing that needs to be tested is amount of open connects that server can handle at the same time.
Maybe somehow to also test the throughput by implementing some specific code server side for event stream?

https://github.com/matthiasn/sse-perf

**Comment by thegoatherder** [comment]
Did this ever get implemented?
My use cases:
  1. Measure json stream rows/sec
  2. Measure json stream MB/sec
  3. If a stream pushes a "done" event, measure the total time to receive.

**Comment by iambumblehead** [comment]
I would like to test server-sent events but did not find any documentation for this, though this issue is closed as completed

**Comment by DrSensor** [comment]
after asking copilot and search their repo, seems it's not yet implemented 🤔

**Comment by JessicaQi** [comment]
Hey 👋  happened to see this [artillery-engine-sse](https://github.com/artilleryio/artillery-engine-sse) from 2 years ago, and was wondering if it's officially released or supported by any of the existing Artillery engines? I couldn’t find any mention of it in the current docs 👀

Also, anybody ever tried this sse engine with GraphQL subscription? Thanks
