### ISSUE TITLE
JSON variables with value=0 are not captured

### ISSUE THREAD

**Issue by i-k-o** [artilleryio/artillery#1078]
JSON variables that has value 0 are not properly captured and as: var is not populated

**Comment by sateffen** [comment]
I've got the same problem.

The culprint is [this line](https://github.com/artilleryio/artillery/blob/v1.6.x/core/lib/engine_util.js#L345).

To fix this behaviour [this commit](https://github.com/artilleryio/artillery/commit/0aae8fbf901802c1dba07128b1bbe37ba1c8ed66) can be cherry-picked to the current 1.6.x branch, resolving this issue.

**Comment by flentini** [comment]
fixed in d06f3d44e73947658ef22ab5bea5e0ee474d9347
