### ISSUE TITLE
1.7 broke processor-functions FormData handling

### ISSUE THREAD

**Issue by sateffen** [artilleryio/artillery#1096]
Hey,

I've updated a project from 1.6 to 1.7, which contains a breaking change with processor-functions. [This commit](https://github.com/artilleryio/artillery/commit/6211c1775fb33653e25df743998a262d91904785) line [351](https://github.com/artilleryio/artillery/commit/6211c1775fb33653e25df743998a262d91904785#diff-b4f212990828cb2d6668a0128ee6c6838226d35b7245dc8eef9ef561976592d0R351) replaced `requestParams.formData` with `params.formData`, so when extending the FormData in a processor-function, the added data-fields are missing.

To fix this bug, the line [356 of core/lib/engine_http.js](https://github.com/artilleryio/artillery/blob/6514d30c7f8709cba1131cfdbe6c561c148f4db9/core/lib/engine_http.js#L356) has to change back from `params.formData` to `requestParams.formData`.

As this is a breaking change it would be nice to have a bugfix-release for the 1.7, that way all users can upgrade in semver way.

Best regards

**Comment by hassy** [comment]
thank you @sateffen - will include in v1.7.4
