### ISSUE TITLE
Artillery expect plugin- Undefined function "expectationsPluginMaybeFlushDatadog": 10

### ISSUE THREAD

**Issue by smksnutmeg** [artilleryio/artillery#1128]
Whenever I use the expect plugin I get this as an error on my reports.
Undefined function "expectationsPluginMaybeFlushDatadog": 10

**Comment by elton-okawa** [comment]
Recently there was a change to count as error if a custom function step does not exist #1102. 
I've notice that in `plugin-expect` we register `expectationsPluginMaybeFlushDatadog` but we do not add it as processor, I'll open a PR to fix it.

**Comment by smksnutmeg** [comment]
Thank you!!

**Comment by smksnutmeg** [comment]
Do we have a new published version available?

**Comment by hassy** [comment]
v1.5.0 of the plugin is out with the fix :)
