### ISSUE TITLE
the 'after' code block does not work in version 1.7.6 or previous

### ISSUE THREAD

**Issue by nicomisfits** [artilleryio/artillery#1130]
I only could use it in dev's version

**Comment by bentovsky** [comment]
That worked for me. Thanks for your output
:rocket:

**Comment by bentovsky** [comment]
I've noticed that, with the dev's version, the html report doesn't display any information

**Comment by flentini** [comment]
hi @nicomisfits you are correct, `after` is only supported in v2 (dev). We'll update the documentation to make that clear.

**Comment by rmpt** [comment]
how can I run v2?

**Comment by hassy** [comment]
docs have been updated
