### ISSUE TITLE
Error: Cannot assign to read only property 'headers' of /test

### ISSUE THREAD

**Issue by hostiphur** [artilleryio/artillery#116]
I'm trying to follow along with the documentation and I added some default headers:

```
"config": {
    "target": "http://localhost:3085",
    "phases": [{
        "duration": 60,
        "arrivalRate": 20
    }],
    "defaults": {
        "headers": {
            "x-container-uuid": "fd62ee70-eb00-407a-960d-8a92dbb60b12",
            "x-user-uuid": "46c6973a-304f-4a9f-a9a6-c6c42567ad18"
        }
    },
```

...

When I try to run the test I get the following error:

/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:78
    requestParams.headers = _.extend(defaultHeaders,
                          ^

TypeError: Cannot assign to read only property 'headers' of /test
    at f (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:78:27)
    at fn (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback](timers.js:374:17)

**Comment by hostiphur** [comment]
nevermind, I fixed it by putting the headers in the scenario like below. However, I'm still not sure why using the headers under defaults wouldn't work.

    "scenarios": [
        {
            "name": "test 1",
            "flow": [
                {
                    "post": {
                        "url": "/test",
                        "headers": {
                            "x-container-uuid": "fd62ee70-eb00-407a-960d-8a92dbb60b12",
                            "x-user-uuid": "46c6973a-304f-4a9f-a9a6-c6c42567ad18"
                        },...

**Comment by hassy** [comment]
Reopening since it looks like it could be a bug - will need to investigate.

Thanks @hostiphur
