### ISSUE TITLE
Artillery >= 1.7.2 does not stop when setting "gzip: true"

### ISSUE THREAD

**Issue by RemiEven** [artilleryio/artillery#1163]
Hello,

I recently updated the version of artillery we used from 1.6.0-29 to the latest 1.7.8.
Our tests worked fine before the update, but now artillery won't stop, printing 
```
Report @ 14:59:45(+0000) 2021-09-02
Elapsed time: 20 seconds
  Scenarios launched:  0
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
```
again and again.

I can share a file to reproduce this, but it contains URLs we'd rather not post publicly here.

I tried different versions of artillery and found that for us the problem appeared starting at artillery 1.7.2.
In later versions, deleting the "gzip: true" setting in our scenarios make them work again.
I suppose this has something to do with this commit: https://github.com/artilleryio/artillery/commit/82f7cd8e02776b2b163e85d7da30b41873855aa3 .

Interestingly, when enabling logging with `export DEBUG=http,http:capture,http:response` , everything works and artillery stops as expected.

I've read https://github.com/artilleryio/artillery/issues/215 and https://github.com/artilleryio/artillery/issues/238 but I'm not sure if they are relevant for this problem or not.

We're happy with using artillery 1.7.1, but it would be nice if that was fixed so we could update to the latest version

**Comment by hassy** [comment]
hi @RemiEven, thanks for the extra details, I'll try to reproduce the issue here.

if you don't mind sharing the URLs privately you can email me on h@artillery.io

**Comment by RemiEven** [comment]
Thanks ! I've just sent you an email to the address you provided

**Comment by hassy** [comment]
Fixed by https://github.com/artilleryio/artillery/pull/1164

**Comment by RemiEven** [comment]
I confirm the PR resolves the problem on our end, and it does :smiley: 
So I'll close this issue.
Thanks a lot for the quick resolution !
