### ISSUE TITLE
"ECONNRESET" and "ETIMEDOUT" errors on MacBook Pro M1 chip only

### ISSUE THREAD

**Issue by annageorge1** [artilleryio/artillery#1169]
My script fails about 50% of the time (errors “ECONNRESET” and/or “ETIMED OUT”) when running on MacBook Pro w/ M1 chip.
 
My team and I have run it on a few different computers, and we confirmed that it does NOT occur on MacBooks WITHOUT the M1 chip.
 
 
Example script:
```
config:
 target: “https://XXXXXXXX”
 http:
   timeout: 120
   maxSockets: 1000
 phases:
   - duration: 1
     arrivalRate: 1
     name: Warm up
   - pause: 15
   - duration: 1
     arrivalCount: 5000
     name: Sustained load
 defaults:
   headers:
     Accept: “application/XXXXXXX”
scenarios:
 - name: “create transactions”
   flow:
     - post:
         url: “/XXXXXXX”
         json:
           event_timestamp: “2021-09-01-01:23:45”
           resource_status: “D”
           notification_id: “test”
           notification_url: “XXXXXXX”
           notification_description: “Token declined”
           notification_type: “AUTHORIZATION”
           service_type: “CA”
           resource_id: “XXXXXXXX”
           resource_type: “PYMT”
```
 
 
 
Example result (~50% error at creating 5000 objects):
```
All virtual users finished
 Summary report @ 13:55:56(-0400) 2021-09-20
  Scenarios launched: 5001
  Scenarios completed: 2507
  Requests completed: 2507
  Mean response/sec: 25.16
  Response time (msec):
    min: 7
    max: 21305
    median: 1167
    p95: 21248
    p99: 21273
  Scenario counts:
    create XXXXXX: 5001 (100%)
  Codes:
    200: 2507
  Errors:
    ETIMEDOUT: 2494
```
 
Example result from MacBook Air (close to 0% error, testing 30,000 objects):
```
All virtual users finished
Summary report @ 16:44:51(-0400) 2021-09-20
 Scenarios launched: 30304
 Scenarios completed: 30252
 Requests completed: 30252
 Mean response/sec: 182.07
 Response time (msec):
  min: 1
  max: 10250
  median: 138
  p95: 549
  p99: 1036
 Scenario counts:
  create XXXXXX: 30304 (100%)
 Codes:
  200: 30252
 Errors:
  ENOTFOUND: 52
```
 
MacBook Pro, 2020
macOS Big Sur Version 11.4
Apple M1 Chip
Node version: v16.9.1
NPM version: 7.21.1
Artillery version: 1.7.9
 
MacBook Air, 2018
macOS Mojave Version 10.14.6
1.6 GHz Intel Core i5
Node version: v14.17.1
NPM version: 6.14.13
Artillery version: 1.7.9

**Comment by hassy** [comment]
That's interesting. I wonder if the difference is to do with macOS version rather than the chip. There may be differences between Node 14 and 16 too.

Both `ETIMEDOUT` and `ECONNRESET` are usually reported when the server under test is struggling with load, vs errors that occur in Artillery itself.

**Comment by hassy** [comment]
closing, unlikely to do with CPU architecture

**Comment by TinyStorm** [comment]
Same question on MacBook Pro 2019 with intel.
How do you resolve it ?

**Comment by hassy** [comment]
hi @TinyStorm 👋 

> Both ETIMEDOUT and ECONNRESET are usually reported when the server under test is struggling with load, vs errors that occur in Artillery itself.

Typical solution is to scale up or start optimizing the system under test (give it more CPU/memory, scale out horizontally, introduce caching etc)
