### ISSUE TITLE
plugin:expect Not running in a worker

### ISSUE THREAD

**Issue by oleg-koval** [artilleryio/artillery#1177]
Getting such debug info:

```
artillery -v                               

ARTILLERY DEV PREVIEW 🚀
Please report bugs on https://github.com/artilleryio/artillery/issues

artillery/2.0.0-1 darwin-x64 node-v12.22.1
```

artillery-plugin-expect version  - 2.0.0-2

```
⠋   plugin:expect Not running in a worker, exiting +0ms
⠴ 2021-09-30T10:07:57.176Z plugin:expect Not running in a worker, exiting
⠦ 2021-09-30T10:07:57.224Z plugin:expect Not running in a worker, exiting
2021-09-30T10:07:57.252Z plugin:expect Not running in a worker, exiting
⠧ 2021-09-30T10:07:57.273Z plugin:expect Not running in a worker, exiting
2021-09-30T10:07:57.308Z plugin:expect Not running in a worker, exiting
Phase started: Warm up (index: 0, duration: 60s) 13:07:57(+0300)
```

expect does not work for me, how it can be solved?

**Comment by hassy** [comment]
hi @oleg-koval 👋 this should now be fixed in the most recent version of the plugin + Artillery `v2.0.0-2`

**Comment by oleg-koval** [comment]
hi @hassy 

Updated artillery + plugin to version you said:

artillery -v                                          

ARTILLERY DEV PREVIEW 🚀
Please report bugs on https://github.com/artilleryio/artillery/issues

artillery/2.0.0-2 darwin-x64 node-v12.22.1
```
⠋   plugin:expect Not running in a worker, exiting +0ms
⠼ 2021-10-05T11:52:38.816Z plugin:expect Initialized
```

**Comment by hassy** [comment]
do you see the output from the plugin on the terminal? that "not running in a worker, exiting" message is just a diagnostic message which can be ignored

**Comment by hassy** [comment]
Should look like something like this:

![0_6__tmux__--plugin-expect_](https://user-images.githubusercontent.com/1490/136022365-9965ac59-679d-4acc-9abd-e93f78ecc496.png)

**Comment by oleg-koval** [comment]
@hassy looks fine, you right, the message was confusing

**Comment by hassy** [comment]
awesome 🙌 thanks for confirming!
