### ISSUE TITLE
missing report charts in dashboard 

### ISSUE THREAD

**Issue by Hussain-Ruhullah** [artilleryio/artillery#1197]
when a report is generated using the latest Artillery version and converted to .HTML 
the dashboard does not contain the charts 

but it works in older version "artillery": "1.7.6" 
![2021-11-02 15_14_55-](https://user-images.githubusercontent.com/21989914/139865385-8ca7781a-68f9-482e-a2ae-2ef99d63283c.png)

**Comment by hassy** [comment]
fixed in #1203
