### ISSUE TITLE
Before and After hooks are executed per worker in V2

### ISSUE THREAD

**Issue by chringwer** [artilleryio/artillery#1200]
The documented behaviour suggests that the before/after hooks are only executed once per test script. In V2 this seems to only be true if workers are limited to 1. Otherwise the setup and teardown routines are called multiple times (up to WORKERS count) which might lead to unexpected results.

Ideally this would be constrained to run before the scenario execution is forked and after all workers have completed or at least should be pointed out in the documentation.

**Comment by hassy** [comment]
thank you for the bug report @chringwer!
