### ISSUE TITLE
2.0.4 version thats now on npm has some new bugs

### ISSUE THREAD

**Issue by npopov-d3** [artilleryio/artillery#1220]
The bigger one of the two i noticed is that given a csv input and a decent load (few users per second) it will generate multiple users using the same line in csv, resulting in duplicate scenarios executed a few ms apart.

The other issue is the html report generation is broken, resulting in html report with no graphs.

**Comment by hassy** [comment]
hi @npopov-d3 👋

reports have been fixed in #1203 

the issue with CSV inputs is due to multithreading which is on by default, I've created an issue to track here: https://github.com/artilleryio/artillery/issues/1221

**Comment by MagicKriss** [comment]
Hi, @hassy !
I stumbled upon this issue while running stress tests.
As you mentioned, a "proper" implementation would require some global state. 

However, while trying to find a possible workaround, I dug through the source code and noticed that the whole payload data is being copied to each worker. 
In this process, the same as phases, payload data could be distributed among workers similarly. 

What do you think about this approach? I could create a PR with the implementation.
