### ISSUE TITLE
CSV data is duplicated across threads

### ISSUE THREAD

**Issue by hassy** [artilleryio/artillery#1221]
Every worker thread gets its own copy of the entire payload - that means that the default `sequence` traversal through the rows is broken as every row will be reused by every worker.

**Comment by hassy** [comment]
We won't be fixing this, as it introduces the requirement of inter-VU coordination / global state, which is especially tricky to solve in distributed tests. The recommendation is to use `random` for load tests, and only use `sequence` for tests run in "solo" mode with just one VU.

**Comment by MagicKriss** [comment]
Hi, @hassy !
I stumbled upon this issue while running stress tests.
As you mentioned, a "proper" implementation would require some global state. 

However, while trying to find a possible workaround, I dug through the source code and noticed that the whole payload data is being copied to each worker. 
In this process, the same as phases, payload data could be distributed among workers similarly. 

What do you think about this approach? I could create a PR with the implementation.
