### ISSUE TITLE
report HTML is showing empty results

### ISSUE THREAD

**Issue by sealabr** [artilleryio/artillery#1222]
Hello i just installed artillery version 2 on my node v16.5.0

(artillery/2.0.0-4 linux-x64 node-v16.5.0)

![image](https://user-images.githubusercontent.com/21187479/141410367-18b987e5-f5af-4a8c-a149-abdd9c7a3426.png)

is showing an empty report in linux AMI 2

--------------------------------
Summary report @ 04:35:45(+0000)
--------------------------------

vusers.created_by_name.0: ................................... 90
vusers.created.total: ....................................... 90
vusers.completed: ........................................... 90
vusers.session_length:
  min: ...................................................... 485.5
  max: ...................................................... 3254.6
  median: ................................................... 1826.6
  p95: ...................................................... 3072.4
  p99: ...................................................... 3134.5
http.request_rate: .......................................... 3/sec
http.requests: .............................................. 90
http.codes.200: ............................................. 90
http.responses: ............................................. 90
http.response_time:
  min: ...................................................... 243
  max: ...................................................... 3013
  median: ................................................... 1556.5
  p95: ...................................................... 2836.2
  p99: ...................................................... 2893.5
Log file: droz/reports/example.json
Report generated: logs/report-1636691712-droz-homolog-example.html

**Comment by hassy** [comment]
fixed in #1203, will release a new version soon
