### ISSUE TITLE
Typo in Testing HTTP docs

### ISSUE THREAD

**Issue by DC4JG** [artilleryio/artillery#1255]
There is a typo in the following [bullet point](https://www.artillery.io/docs/guides/guides/http-reference#get--post--put--patch--delete-requests) for HTTP request attributes:

- `capture` - Sse this to capture values from the response body of a request and store those in variables.

I guess "Sse" should be "Set".

---

Sorry if this is the wrong place to report such an issue.  
I couldn't find the source repository for the official documentation to provide a fix.

**Comment by hassy** [comment]
thank you @DC4JG! fixed now.
