### ISSUE TITLE
Improve documentation of HTML report generation

### ISSUE THREAD

**Issue by DC4JG** [artilleryio/artillery#1256]
The [documentation](https://www.artillery.io/docs/guides/guides/command-line#generating-an-html-report) could be improved for clarity by renaming `report.json` and adding file extension `.html`.

Currently the command `artillery report --output report report.json` repeats the word `report` thrice. Some alternative naming suggestion would be `report.json` -> `data/record/metric.json` or `report` -> `(test)result/analysis`.

Another (additional) way to make the differentiation more clear would be to add the `.html` extension to `report`. This adds the benefit of using e.g. double click in GUI/Windows to open the report in a browser and allows other automations/scripts to recognize the file type without analyzing the content.

**Comment by hassy** [comment]
oh, that's a good catch @DC4JG - thank you! updated the docs to omit `--output` flag since it's optional, and a `.html` extension is appended by default. (update should be live soon)
