### ISSUE TITLE
Issue when using csv payload in latest version

### ISSUE THREAD

**Issue by andyglez96** [artilleryio/artillery#1263]
![image](https://user-images.githubusercontent.com/88163491/145872155-36ffe8d3-4f88-48a7-b2cb-45dbab47c601.png)
When try to load a payload from csv the console throw this error

Node version: v16.11.1

**Comment by flentini** [comment]
hi @andyglez96 - could you also post the yaml test you are running ?

**Comment by andyglez96** [comment]
Sure...

config:
    target: "http://localhost:5000"
    phases:
        -   duration: 60
            arrivalRate: 1
            name: Warm up
    processor: "./utils.js"
    payload:
        path: "data.csv"
        fields:
            - "totalCampaigns"
        skipHeader: true

before:
    flow:
        -   log: "Get auth token"
        -   post:
                url: "/v2/users/login"
                json:
                    email: "user0@example.com"
                    password: "password"
                capture:
                    -   json: $.accessToken
                        as: token
scenarios:
    -   name: List all campaigns
    -   flow:
            -   get:
                    url: "/campaigns/find?sort=desc&sortBy=_id&page=1&per_page={{totalCampaigns}}"
                    headers:
                        authorization: "Bearer {{ token }}"
                    capture:
                        -   json: $.data
                            as: campaigns
            -   function: "getRandomCampaignId"
            -   get:
                    url: "/campaigns/{{ campaignId }}"
                    headers:
                        authorization: "Bearer {{ token }}"
                    capture:
                        -   json: $.originals
                            as: originals
            -   function: "getRandomOriginalId"
            -   get:
                    url: "/originals/{{ originalId }}"
                    headers:
                        authorization: "Bearer {{ token }}"
                    capture:
                        -   json: $.remakes
                            as: remakes
            -   function: "getRandomRemakeId"
            -   get:
                    url: "/remakes/{{ remakeId }}"
                    headers:
                        authorization: "Bearer {{ token }}"`
`
