### ISSUE TITLE
Cannot create property 'expectationsPluginCheckExpectations' on string './functions.js'

### ISSUE THREAD

**Issue by IOEggception** [artilleryio/artillery#1267]
As of the new patch released yesterday (2.0.0-8), I started seeing this failure happen in our existing configurations that have worked previously but now silently hang our deployment bamboo pipeline until manually aborted:

build	21-Dec-2021 09:34:23	worker error, id: 1 TypeError [Error]: Cannot create property 'expectationsPluginCheckExpectations' on string './functions.js'
build	21-Dec-2021 09:34:23	    at new ExpectationsPlugin (/home/bamboo/.nvm/versions/node/v14.15.1/lib/node_modules/artillery-plugin-expect/index.js:48:63)
build	21-Dec-2021 09:34:23	    at prepare (/home/bamboo/.nvm/versions/node/v14.15.1/lib/node_modules/artillery/lib/worker.js:142:27)
build	21-Dec-2021 09:34:23	    at async MessagePort.onMessage (/home/bamboo/.nvm/versions/node/v14.15.1/lib/node_modules/artillery/lib/worker.js:47:5)

Command line being executed from bamboo task:
artillery run --config ./performance_test/artillery/config/artillery-config.yml -e ${bamboo_environment_key} -o performance-results-${i} ${tests[i]}

In my project, this is where we define the processor source code, which has been working for us up until this latest patch.
![Screen Shot 2021-12-21 at 10 58 31 AM](https://user-images.githubusercontent.com/96488319/146960871-139690bb-7061-49bd-b8aa-a66f766501fa.png)

Then here is the source code itself:

![Screen Shot 2021-12-21 at 11 00 43 AM](https://user-images.githubusercontent.com/96488319/146960870-bd4b8c29-07ad-49f2-b17f-2ad21b06a737.png)

With this new patch, is there a new expectation how we define our custom JS?  or how we define the path to it?

The full error looks like this in our deployment logs:
![Screen Shot 2021-12-21 at 11 04 44 AM](https://user-images.githubusercontent.com/96488319/146961788-6bae3a56-1e4d-48c7-89f9-88a7c3ec03e3.png)

Similarly, here is a copy of "successful" logs.  Notice the same warnings are happening both before with success and current with failure.  Not sure if that version of node is really the culprit here:
![Screen Shot 2021-12-21 at 11 08 32 AM](https://user-images.githubusercontent.com/96488319/146962169-b14f98b2-227a-4202-bd08-1588c8786b15.png)

I can see from the stack trace that the error is bombing out right on this line in the artillery-expect package:
![Screen Shot 2021-12-21 at 11 17 17 AM](https://user-images.githubusercontent.com/96488319/146963327-47f03f09-2bab-4e18-a57b-d674bdde20ad.png)

Thank you!

**Comment by hassy** [comment]
thank you for the amazing level of detail @IOEggception! can confirm, it's a regression in the latest patch, we're on it and will fix asap

**Comment by IOEggception** [comment]
Thanks so much @hassy .  Do you know of any workarounds for it at the moment?  Reducing my version to the previous 2.0.0-7 isnt as easy of an option as it would seem.

**Comment by hassy** [comment]
just tagged a new version of Artillery - `v2.0.0-9` which reverts the commits that introduced the regression - should be on npm in the next 15-20m once all tests have finished running

**Comment by IOEggception** [comment]
Thank you @hassy , i can confirm your update has got my team back into a working state! Thanks for the speed!
