### ISSUE TITLE
Support ES modules as processor

### ISSUE THREAD

**Issue by d-otter** [artilleryio/artillery#1269]
Currently there is some drive in parts of the JS community to switch from commonjs to ES modules.
One example is the http request library got, also used by artillery.

This change comes with a lot of incompatibilities / headaches and also artillery in the latest 2.x version (2.0.0-9) does not seem to support specifying ES modules as processor path.

Monkey-patching line `107` in `worker.js` (https://github.com/artilleryio/artillery/blob/master/lib/worker.js#L107)
from 
```
    let processor = require(processorPath);
```
to
```
    let processor = await import(processorPath);
```
seems to work for commonjs and ES modules.

As I do not feel 100% confident this might not have any unwanted side-effects I just want to mention this here as suggestion, without proof it is the right thing to do.

Would be great to see artillery in the future also support ES modules.

Looking forward to see version 2 finally land

**Comment by hassy** [comment]
better late than never eh! just landed on `main` and will be out on Monday in v2.0.7
