### ISSUE TITLE
The blog post on using GraphQL contains an unrendered imgTag

### ISSUE THREAD

**Issue by jracabado** [artilleryio/artillery#1303]
On the blog post [Using Artillery to Load Test GraphQL APIs](https://www.artillery.io/blog/using-artillery-to-load-test-graphql-apis) there is an unrendered imgTag: 

`{% imgTag img/blog/graphql-example-schema.png "GraphQL API Example Schema" " " "border: 1px solid #ddd; margin: 0 auto;" %}`

**Comment by hassy** [comment]
fixed, thank you @jracabado!
