### ISSUE TITLE
Using arrivalCount will mess with phaseStarted and phaseCompleted events

### ISSUE THREAD

**Issue by chringwer** [artilleryio/artillery#1313]
I think with #1288 a race condition was introduced because only the first worker to start/complete a phase at the given index will be allowed to emit phaseStarted/phaseCompleted events to the reporter. With `artillery@2.0.0-11` that's causing phases showing up as "unnamed" in the console output at times.

**Comment by hassy** [comment]
@chringwer can we send you some Artillery swag? You've been very helpful with bug reports! 😄

**Comment by chringwer** [comment]
@hassy My pleasure. Thanks for all the good work!

**Comment by rmjwilbur** [comment]
I'm wondering if this is related to my current issue. I'm trying to write a local plugin and neither phaseStarted nor phaseCompleted seem to be getting emitted.

```
function ArtilleryExamplePlugin(script, events) {

  events.on('phaseStarted', function() {
    console.log('🧑 New load phase started');
  });

  events.on('phaseCompleted', function() {
    console.log('✅ Load phase complete');
  });

  events.on('stats', function() {
    console.log('🖥️ Reporting');
  });

  events.on('done', function() {
    console.log('🪄 All VUs finished');
  });

  return this;
}
```

Results:
```
    Phase started: Phase 1 (index: 0, duration: 1s) 10:41:00(-0700)
    
    Phase completed: Phase 1 (index: 0, duration: 1s) 10:41:01(-0700)

    🖥️ Reporting

    🪄 All VUs finished
```

**Comment by hassy** [comment]
@rmjwilbur thank you for reporting the issue, I can confirm that's a bug - just pushed a fix to `main` in https://github.com/artilleryio/artillery/commit/c2a39fe4be80707eff162f14b9759cc21014ccfc
