### ISSUE TITLE
An Error in the Doc

### ISSUE THREAD

**Issue by rhanqtl** [artilleryio/artillery#1344]
The [doc](https://www.artillery.io/docs/guides/guides/socketio-reference#examples) shows usage of `response` and `acknowledge` as follows:

![image](https://user-images.githubusercontent.com/28992260/154805377-05d6733c-8b20-4d94-b756-151720bb81fb.png)

However, `response` and `acknowledge` are at the same level as `emit` in the source code:

```javascript
function isResponseRequired(spec) {
  return spec.emit && spec.response && spec.response.channel;
}

function isAcknowledgeRequired(spec) {
  return spec.emit && spec.acknowledge;
}
```

**Comment by bernardobridge** [comment]
This documentation has been updated a while ago. Thanks!
