### ISSUE TITLE
Docker image doubled in size between v2.0.0-11 and v2.0.0-12

### ISSUE THREAD

**Issue by RichardoC** [artilleryio/artillery#1361]
Given the code changes don't seem [so significant](https://github.com/artilleryio/artillery/compare/v2.0.0-11...v2.0.0-12), why did the docker image size almost triple from [53MB](https://hub.docker.com/layers/artilleryio/artillery/2.0.0-11/images/sha256-d49c7fec53f55db61e837843e7ddda98cf737170391853e2d353745769449f3f?context=explore) to [139MB](https://hub.docker.com/layers/artilleryio/artillery/2.0.0-12/images/sha256-cc5877b5748453a6de580a7313ed2d3a329bdd1abceffdb2226bb1a4fba35ec7?context=explore) ?

Could we undo the regression in filesize?

Thanks!

**Comment by hassy** [comment]
Hi @RichardoC 👋 we're bundling a couple of official plugins into the Docker image now ([this change](https://github.com/artilleryio/artillery/commit/af9f5cf37c26b8a58117e3af8fb7d198c69a1f95)). 

Perhaps we could look at publishing another image with no plugins.

**Comment by RichardoC** [comment]
That makes sense, if it's making things easier I think it's fine those are included. 

I was just surprised that "This is a maintenance release with dependency upgrades and minor bug fixes." lead to such an increase! Maybe call that change out in the release notes as well?

**Comment by hassy** [comment]
Yes, good shout, updated tho notes. Thanks!
