### ISSUE TITLE
Simple Typo in Docs

### ISSUE THREAD

**Issue by qf9ar8nv** [artilleryio/artillery#1377]
I am reading the Docs to use this open source.
Thanks for the kind instructions on how to use it.

And, I found that it was spelled incorrectly.

Artillery will print "Current environment is set to: staging". at the bottom seems to be Artillery will print "Current environment is set to: local".

<img width="804" alt="image" src="https://user-images.githubusercontent.com/62492860/159235250-32bfbb7b-fa54-4c01-9c47-1782db15f2aa.png">

**Comment by hassy** [comment]
thank you @qf9ar8nv! fixed now
