### ISSUE TITLE
Postman integration

### ISSUE THREAD

**Issue by hassy** [artilleryio/artillery#14]
It would be nice to have support for [Postman](https://www.getpostman.com) collections in Artillery.

**Comment by jnicolls** [comment]
Is this still wanted?

**Comment by hassy** [comment]
@jnicolls yes, definitely!

**Comment by rupeshmore** [comment]
An attempt to convert postman api's to artillery config - https://dakiya-ykwpldbeqo.now.sh

**Comment by dennisoverbeeke** [comment]
+1

**Comment by jovanross** [comment]
Yes please +1

**Comment by randolphpark** [comment]
+1

**Comment by jing1977** [comment]
Any update on this?

**Comment by BohoCode** [comment]
Yes please!

**Comment by hassy** [comment]
No updates, the core team aren't actively working on this. If it happens, it'll have to be a community contribution for the time being.

**Comment by V-Shukla** [comment]
Yes, please!

**Comment by rufreakde** [comment]
@hassy  this was closed but it was not added neither by community nor core team right?
