### ISSUE TITLE
Schema incomplete

### ISSUE THREAD

**Issue by InsOpDe** [artilleryio/artillery#1405]
The current schema is very incomplete: https://github.com/artilleryio/artillery/blob/master/core/lib/schemas/artillery_test_script.json

the whole `scenarios` definition is missing

**Comment by hassy** [comment]
fix for this is incoming :D /cc @flentini

**Comment by InsOpDe** [comment]
hi @hassy now the schema has been deleted which is rather sad, since I use it to have auto-completion with my IDE.

do you think it would be worth it to have a schema? then id create another issue if its alright with you
