### ISSUE TITLE
Ensure plugin triggers warnings

### ISSUE THREAD

**Issue by nephix** [artilleryio/artillery#1457]
Version info: 
```
VERSION INFO:

Artillery Core: 2.0.0-16
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v16.15.0
OS:      darwin
```

When my artillery file contains: 
```
config:
  plugins:
    ensure: {}
```

I expected to see this happen:

I don't see a warning in the console, because according to https://docs-nine-inky.vercel.app/docs/guides/guides/test-script-reference#ensure---slo-checks it's a built in plugin

Instead, this happened:

```
WARNING: Could not load plugin: ensure warn
WARNING: Plugin ensure specified but module artillery-plugin-ensure could not be found (MODULE_NOT_FOUND) warn
Phase started: unnamed (index: 0, duration: 20s) 20:11:52(+0000)

[2] WARNING: Could not load plugin: ensure warn
```

**Comment by hassy** [comment]
thanks @nephix! this is fixed in the most recent release v2.0.0-17
