### ISSUE TITLE
How to handle "one of" expectations

### ISSUE THREAD

**Issue by mjclemente** [artilleryio/artillery#1459]
We have an API endpoint that returns JSON. I want to test one of the keys/values in the response, which has a set number of valid responses.

I can use `capture` to get the value in the response, but I can't use `equals` to test it, because there is more than one possible value it may return.

I saw issue #920, which suggested using the `matchesRegexp` expectation, but I'm having a hard time getting it to work for JSON responses. Basic regex checks work (like `.+` from the example), but I can't get more complex checks to work. For example, something like this: `/[^\\"]*(value one|other option)[^\\"]*/`.

Outside of artillery, when run that regex against a string, it works as expected:

```js
let expectedRegexp = /[^\\"]*(value one|other option)[^\\"]*/
let str = `"{\"guid\":\"21239975\",\"url\":\"https://internet.com/\",\"name\":\"value one\"}"`

let rx = new RegExp(expectedRegexp);
const matches = new RegExp(rx).test(str);

console.log(matches)
```

However, if my API returns that as JSON, the expectation is failing. 

It seems like maybe the JSON is being passed as an object into the matcher causing it to fail.

Is there an approach to testing a response like this?

Thanks for any help or insight!

**Comment by GeekyDeaks** [comment]
There might be an 'easier' way to do this with a [JSONpath query](https://github.com/json-path/JsonPath,) but I could only get a regexp to work (and I had to take a look at the code to figure it out)

```
  name: Retrieve Response
  url: '{{ uri }}'
  match:
    - regexp: '"(name)":"(value one|other option)"'
      value: name
      group: 1
```

The trick is to match on the attribute name also and compare that instead of the value

**Comment by mjclemente** [comment]
Interesting!

Are there docs on that `match` key you used? 

I'm not seeing them [here](https://www.artillery.io/docs/guides/guides/http-reference) (though it does seem like the `capture` option has a `regexp`, so I imagine I could use it the same way).

**Comment by GeekyDeaks** [comment]
I am not aware of any documentation.  I just looked at the code here: https://github.com/artilleryio/artillery/blob/64c04bd1f32f0b61f77d0f7a30451e0780d5989b/core/lib/engine_util.js#L384

Both the `capture` and `match` get processed by the same code, so they share very similar syntax and behaviour.

I wasn't aware of the `matchesRegexp` you pointed to in the documentation (I tend to just use the websocket engine).  I think that might be an easier way and just need a slight tweak to your regexp.  I'll take a look later

**Comment by GeekyDeaks** [comment]
Ah, doesn't look like `matchesRegexp` will work because it always tries to `JSON.parse` the body irrespective of the type of check:

https://github.com/artilleryio/artillery-plugin-expect/blob/f8709506cb3b3f6f01aba70488ebc9d7c4ef5ff3/index.js#L92

**Comment by mjclemente** [comment]
Ok, it's not the most elegant solution, but I think I am able to get the functionality I was looking for using `capture`/`match`.

Basically, I can use the capture regex as a sort of truth test - generating a valid value if it matches:

```yaml
capture:
  - regexp: '"(name)":"(value one|other option)"'
    as: present
    group: 1
```

Then, I can use `expect` and `equals` to confirm that a match was found:

```yaml
expect:
  - equals:
      - '{{ present }}'
      - 'name'
```

In cases where the regex (which looks for the multiple valid values) fails, `undefined` is returned, so the equality check fails.

Like I said, not the most elegant, but I really do appreciate you taking the time to help point me in a direction that works.

FWIW, it would be a lot nicer to be able to use either `matchesRegexp` (by converting the body to a string) or some a new expectation matcher that allowed for an array of valid matches.

Again, thanks so much for your help!
