### ISSUE TITLE
Artillery going in infinite loop with "Callback was already called" error

### ISSUE THREAD

**Issue by meetveera** [artilleryio/artillery#1542]
Hi @hassy :

After the latest update you made with the callback error, I reinstalled the latest version of artillery using the below command:
```npm install -g artillery@v2.0.0-22```

Ran the below command to execute artillery script and I am still getting the same error and the run is going in a infinite loop.

```artillery run my-file.yaml -e dev --quiet```

Below is the error I am still getting:

```
worker error, id: 1 Error: Callback was already called.
    at /usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:969:32
    at /usr/local/lib/node_modules/artillery/core/lib/engine_http.js:698:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by hassy** [comment]
hi @meetveera - managed to reproduce the issue on requests that result in multiple redirects. Is that what's triggering it in your script? Do you have a reproducible test case / can you share what your script looks like (redacted as needed or feel free to email me on h@artillery.io)

**Comment by ginaburt** [comment]
Hello @hassy, Is there a temporary work around?

**Comment by meetveera** [comment]
Hi @hassy - I am extremely sorry I wont be able to share the test scripts, but the API endponts does a redirect for RBAC authorization. Hope that answers your question.

**Comment by hassy** [comment]
@ginaburt if you're running into this issue, the best workaround right now is to downgrade to Artillery v2.0.0-19.

**Comment by hassy** [comment]
@meetveera no problem at all, thanks for the extra details!

**Comment by meetveera** [comment]
Hi @hassy - Good Morning. Thank you very much for fixing the problem. Now I am getting proper status codes for multiple redirects errors. 
But again for some APIs it is still going on infinite loop. I double checked my API by executing it via postman and it is working fine there. When I did a little more digging and commented the below line from the snippet from my local machine that all my APIs started to work absolutely fine. 
```.catch((gotErr) => {
            // TODO: Handle the error properly with run hooks
            ee.emit('error', gotErr.code || gotErr.message);
           // return callback(gotErr, context); line 702 from engine_http.js
 });
```

Could you please take a look and see what exactly the problem is? I might be wrong but again commenting that line just worked for me and now all my apis are working fine via artillery run.

Thanks
