### ISSUE TITLE
telemetry notice is shown when ARTILLERY_DISABLE_TELEMETRY='true'

### ISSUE THREAD

**Issue by gpiotti** [artilleryio/artillery#1548]
Version info: 
```
artillery/2.0.0-22 linux-x64 node-v16.16.0 (docker image artilleryio/artillery:latest)
```

Running this command: 
```
run
```

if I set the environment variable ARTILLERY_DISABLE_TELEMETRY to 'true'
I expected to see this happen:

A notice saying telemetry is off

Instead, this happened:

a notice saying `Telemetry is on. Learn more: https://artillery.io/docs/resources/core/telemetry.html`

**Comment by hassy** [comment]
hi @gpiotti, are you setting the environment variable inside the container, or on the host?

**Comment by gpiotti** [comment]
on the container, I checked login in the container and looking if the ARTILLERY_DISABLE_TELEMETRY was set

**Comment by hassy** [comment]
thanks @gpiotti - can confirm, it's a bug, the message should not be printed

(the issue is with printing the notice, telemetry logging **is** disabled as expected when `ARTILLERY_DISABLE_TELEMETRY` is set)
