### ISSUE TITLE
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

### ISSUE THREAD

**Issue by mobappgorl** [artilleryio/artillery#1602]
Please help me. I'm trying to install ionic cordova on cmd but these things shows:

C:\Users\ay>npm install -g @ionic/cli cordova
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.

changed 707 packages, and audited 708 packages in 2m

57 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by hassy** [comment]
This is not an Artillery-related issue, please file it in Cordova's issue tracker.
