### ISSUE TITLE
Run API and UI test sequentially

### ISSUE THREAD

**Issue by meetveera** [artilleryio/artillery#1615]
### Discussed in https://github.com/artilleryio/artillery/discussions/1614

<div type='discussions-op-text'>

<sup>Originally posted by **meetveera** October  7, 2022</sup>
Hi @hassy - Good Morning, Hope you are doing well :)

I have a specific question regarding the test which I am doing. I want to perform some UI testing followed by APIs and than again UI  that too sequentially. The way I am doing it that adding my UI Scripts in before and after scenarios, but the problem with that is the metrics does not report the before and after scenarios. So is there any way where I can acheive this and also get data in my metrics? 
Thannks</div>

**Comment by juanig1** [comment]
We can follow this in [this](https://github.com/artilleryio/artillery/discussions/1614) related discussion
