### ISSUE TITLE
artillery-plugin-publish-metrics: Send request name to Honeycomb

### ISSUE THREAD

**Issue by bemanuel-trove** [artilleryio/artillery#1646]
Currently, the Honeycomb payload consists of sending `url`, `host`, `method`, and `statusCode`. For certain requests (e.g. GraphQL) it can be hard to distinguish between the requests being made. It would be very nice (and a simple, one-line change) to send `name: req.name` with the rest of the payload located in `artillery-plugin-publish-metrics/lib/honeycomb.js`.

Thanks!

**Comment by hassy** [comment]
great suggestion, fixed now with a PR by @lastnamevega!
