### ISSUE TITLE
Expect Plugin

### ISSUE THREAD

**Issue by johnnyrockoff** [artilleryio/artillery#1659]
Version info:
```
VERSION INFO:

Artillery Core: 2.0.0-24
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v18.7.0
OS:      linux
```

Running this command: 
```
artillery run <MyTestScript>
```
*If expect fails the flow stop*

*I'm creating a solution to update Test Cases in Azure Test Plans Section and send Adaptive Cards on Azure Devops Teams Channels if a test fail. We are using the expect plugin and when a test fail because of the expect the artillery does not call the afterResponse section on my yaml file, is there any way to use expect without breaking the flow?*

Files being used:
-

**Comment by juanig1** [comment]
Closing this as its already being discussed [here](https://github.com/artilleryio/artillery/discussions/1656)
