### ISSUE TITLE
Artillery update check failed

### ISSUE THREAD

**Issue by blevinson** [artilleryio/artillery#1688]
Hello, I keep getting "artillery update check failed" in my reports. I've tried to do the suggested  "sudo chown -R $USER:$(id -gn $USER) /root/.config" to no avail. Is there a way to disable this check. I'd rather not have this type of communication during our tests.

**Comment by juanig1** [comment]
Hey!
| "artillery update check failed"
Do you mean npm update check failed?

More info may help troubleshooting, but this seems to be caused by an issue with your npm config and not artillery itself
