### ISSUE TITLE
Lambda: `MemorySize` error

### ISSUE THREAD

**Issue by mikevercoelen** [artilleryio/artillery#1733]
I get a `MemorySize` error when trying to run an Artillery script for `aws:lambda`

I've double checked my Lambda quotas (plus the region I'm targetting, which is `us-east-1`), and my limit is 10gb.

Not sure what's going on here?

Version info:
```
Artillery Core: 2.0.0-27
```

Running this command: 
```
artillery run ./connect.yml --platform aws:lambda --platform-opt region=us-east-1 --platform-opt memory-size=2048 --count 1 -o ./reports/connect.json
```

**Comment by juanig1** [comment]
Hi, seems we have an issue with some `--platform-opt` options not applying.
Looking at it right now
