### ISSUE TITLE
Unable to run Artillery from .github workflow

### ISSUE THREAD

**Issue by DH250439** [artilleryio/artillery#1766]
Version info: Artillery Core: 2.0.0-27
Node.js: v16.16.0

Running this command: 
```
      run: /home/node/artillery/bin/artillery run --output reports/rawItems.json test/performance/perf-tests.yml

```

I expected to see this happen:

They run successfully in the pipeline

Instead, this happened:

/home/runner/work/_temp/3dcf7f58-564c-42e4-92d9-d413254fe87c.sh: line 1: /home/node/artillery/bin/artillery: No such file or directory

Files being used:
```
yaml
```

**Comment by hassy** [comment]
hi @DH250439 👋 changing `/home/node/artillery/bin/artillery` to `//home/node/artillery/bin/run` should make it work. (The command installed globally is called `artillery` but the executable inside the Artillery package is called `run`)

**Comment by DH250439** [comment]
> Do you know the reports cmd?  This is what I currently have.
run: /home/node/artillery/bin/artillery report --output reports/rawItems.json
Thanks @hassy

**Comment by hassy** [comment]
It's the same path but with the `report` command i.e. `/home/node/artillery/bin/run report --output reports/rawItems.json`
