### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by rabee-abu-michael** [artilleryio/artillery#1779]
I have a problem when installing npm through Windows powerShell
command that you used : npm install -g firebase-tools
![Error5](https://user-images.githubusercontent.com/100477396/213580789-597e626b-c6b5-469d-a1cb-9a8de37d8eaa.PNG)

**Comment by hassy** [comment]
We don't maintain firebase-tools. Try https://github.com/firebase/firebase-tools
