### ISSUE TITLE
Is beforeRequest hooks run before or after variable substitution?

### ISSUE THREAD

**Issue by danielo515** [artilleryio/artillery#189]
Hello,

I am trying to use some JS logic to inject templated JSON payload in the request at runtime. This is for making  more automatic the task of use new payloads and smaller config files.
I wanted to use variables within the JSON templates that I inject, but this will be only possible if beforeRequest hooks runs before variable substitutions are performed.

Could you please clarify this point? If it is not already possible, would it be possible to introduce another hook that runs before variable substitution?

Thanks an regards

**Comment by hassy** [comment]
Those run after variables have been substituted already. Yeah, we can add a `beforeTemplate` hook (or something named along those lines).

**Comment by danielo515** [comment]
In my tests it is happening that variable substitution is not being performed if I inject something in the context.vars
What is the point of being able to inject something into vars if it will not be used?

**Comment by hassy** [comment]
Are you modifying the variable (or adding a new one) in the step **before** the one where you're using it?

**Comment by danielo515** [comment]
Hello @hassy ,

> Are you modifying the variable (or adding a new one) in the step before 

At first I was not, because the authorization hook runs at scenario level, and the one injecting some variables being used on the `url` was running at petition level. But now that I have moved the variable injector to scenario level too, and I put it before in the array of hooks the result is exactly the same: If I inspect the `requestParams` the variables are there, but the variables at the uri are just empty strings

**Comment by danielo515** [comment]
```
- beforeRequest:
        - "injectLatLon"
        - "authorizeRequest"
  flow:
        - get:
            url: "/grids/{{ lat }}/{{ lon }}"
```

That is one of my flows, then

**Comment by hassy** [comment]
As mentioned above `beforeRequest` runs **after** the substitutions have already been performed, that's why it doesn't work. We need a hook for before the substitutions are performed for your use case.

**Comment by danielo515** [comment]
Hello @hassy ,

I do understand that fact, I also deducted that after a while. But it is confusing that you have access to the environment variables on the `beforehooks` and that you can change them there. You should clearly specify that changing variables from the before hook will have no effect on the variable substitution, and maybe some other places that I didn't think about. Somebody (like me) could infer that if you can change it, you can take advantage of it.

thanks and regards

**Comment by rmjwilbur** [comment]
Using version 2.0.0-32 - and for me, the substitution is not happening before `beforehooks` is run.  This is mentioned in https://github.com/artilleryio/artillery/issues/892 as well.

Having some way to indicate whether we want the before or after substitution, or have access to both would be nice.

**Comment by hassy** [comment]
Updating for Artillery v2 and later, where the behavior described in the original comment changed:

Substitutions now happen **after** `beforeRequest` hooks have been run. That means that `beforeRequest` handlers get the original URL, e.g. with this request definition:
```yaml
- get:
    url: "/{{ animal }}"
```
   the `req.url` property inside a `beforeRequest` hook will be `"/{{ animal }}"`.

This means that template variables can be (re)defined inside those hooks to update the URL, for example this hook overwrites the URL to `/armadillo` by setting the template variable to that value:

```js
function beforeHandler(req, context, events, done) {
  context.vars.animal = 'armadillo';
  return done();
}
```

Artillery also exposes the built-in `template()` function now, which can be used to resolve any templated string early if needed:

```js
function beforeHandler(req, context, events, done) {
  // template variables currently defined
  console.log(context.vars);
  // print current URL, e.g. "/{{ animal }}"
  console.log(req.url);
  // substitute the `animal` variable with a custom value:
  console.log(global.artillery.util.template(req.url, { vars: { animal: 'bear'}}));
  // optionally: we could assign the result of the call to template() to req.url to
  // override the URL
  return done();
}

```

**Comment by rmjwilbur** [comment]
Thanks for clarifying the behaviour and providing the template() info @hassy - this is what returns the resolved value for me:

```
console.log('resolved:', global.artillery.util.template(req.url, { vars: context.vars }));
```
