### ISSUE TITLE
Metrics-By-Endpoint plugin not adhereing to useOnlyRequestNames

### ISSUE THREAD

**Issue by cjsaurusrex** [artilleryio/artillery#1945]
When using the metrics-by-endpoint plugin with `useOnlyRequestNames` set to `true`, if no request name is set the requestName sent in the metric is then sent as the full request path.

**Version info:**
```
Artillery: 2.0.0-33
Node.js:   v17.8.0
OS:        darwin
```

**I expected to see this happen:**

Based on the name of the plugin config setting(`useOnlyRequestNames`), if this is set to `true` I would expect only request names to be used and if one is not provided the metric to be skipped.

If this config setting is set to `false`, then I would expect the existing logic to continue in which the requestName is `{requestPath} + {requestName}` or simply just `{requestPath}`

**Instead, this happened:**
When the `useOnlyRequestNames` setting is set to true, if no name is specified for the request, the request path is instead sent.

**Comment by cjsaurusrex** [comment]
I'm also currently looking at getting a PR up for this

**Comment by hassy** [comment]
thanks @cjsaurusrex! Yes I agree the name of the setting is a bit ambiguous.

It sounds like you'd like to be able to exclude requests to certain URLs to be omitted from reports - is that right? If that's the case, then it should probably be a separate setting on the request itself, as `useOnlyRequestNames` is meant to control the name of the metric that gets generated, and changing its behavior would break backwards compatibility.

**Comment by cjsaurusrex** [comment]
Hey @hassy - I suppose it's not as much excluding certain urls as much as it is only publishing the metric if a `name` is present (e.g if somebody forgets to set a `name` we don't want to create thousands of potentially unique metrics buckets).

To ensure we don't break backwards compatibility what about us adding a new config setting for this plugin, e.g `ignoreUnnamedRequests`?

**Comment by hassy** [comment]
Ah I see, that makes sense! `ignoreUnnamedRequests` should work! Or perhaps we could generalize it and add an option to strip any querystrings and only use the path for reporting? (as I imagine that's what's creating lots of unique URLs) That way if someone forgets to set a name, they'll still see reports for the endpoint. What do you think?

**Comment by hassy** [comment]
Oh also a note on the monorepo setup we have (it's a bit weird and is not documented anywhere yet 😥) - for local development, you can edit artillery's [`package.json`](https://github.com/artilleryio/artillery/blob/main/packages/artillery/package.json#L103) to set the version of `artillery-plugin-metrics-by-endpoint` to `*` and then rerun `npm install -w artillery` from the root of the repo to then be able to test changes in the plugin instantly with the dev copy of Artillery CLI.

**Comment by cjsaurusrex** [comment]
I think both of them have the potential to resolve this issue. It could be worth actually implementing both a `stripQueryStrings` and a `ignoreUnnamedRequests`? Since I imagine some people will want auto-generated metric paths(without query strings creating thousands of metrics) and others may just want to skip them if unnamed?

What do you think of doing that?

_I unfortunately actually have 1 scenario where even stripping the query string will create a fair number of unique metrics which is all that worries me_

**Comment by cjsaurusrex** [comment]
Hey @hassy - Unless I'm missing it(please correct me if I am!); it doesn't look as if the metrics-by-endpoint plugin has a Github Actions workflow for publishing it to npm?

Looks as if the previous version published was [1.0.2](https://www.npmjs.com/package/artillery-plugin-metrics-by-endpoint)

**Comment by hassy** [comment]
Yep, that's correct - releases are triggered by a CI commit. About to release a new version of Artillery CLI that will include the new feature. :)

**Comment by hassy** [comment]
@cjsaurusrex Artillery v2.0.0-34 is out now with this feature included!
