### ISSUE TITLE
Artillery plugin type error: c.args.map is not a function

### ISSUE THREAD

**Issue by ahouseago** [artilleryio/artillery#1985]
Version info: 
```
Artillery: 2.0.0-34
Node.js:   v16.16.0
OS:        darwin
```

Running this command: 
```
pnpm --package=artillery@2.0.0-34 dlx artillery -v
```
or version 2.0.0-33
```
pnpm --package=artillery@2.0.0-33 dlx artillery -v
```

With version 2.0.0-32, I get this output with warnings about missing peer dependencies omitted:
```

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery: 2.0.0-32
Node.js:   v16.16.0
OS:        darwin
```

Instead, this happened (with the same peer dependency warnings from before omitted):

```
(node:10426) TypeError Plugin: artillery: c.args.map is not a function
module: @oclif/config@1.18.12
task: toCached
plugin: artillery
root: $PNPM_ROOT/store/v3/tmp/dlx-10179/node_modules/.pnpm/artillery@2.0.0-34/node_modules/artillery
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery: 2.0.0-34
Node.js:   v16.16.0
OS:        darwin
```

The error seems to be from the `@oclif/config` package which is [deprecated](https://www.npmjs.com/package/@oclif/config), and possibly related to issue #1933, which I also encounter when trying to run a load test with artillery.

**Comment by hassy** [comment]
thank you @ahouseago! can confirm the issue, fix out shortly

**Comment by hassy** [comment]
This should be fixed now, but will require a `npm install`. The issue was caused by a backwards-incompatible change of a dependency going out as a semver-patch upgrade.

**Comment by ahouseago** [comment]
Thanks for the quick response. It looks like it's fixed for me, running `pnpx artillery -v` outside of an artillery project doesn't give me any errors with v2.0.0-34 👍 

```
VERSION INFO:

Artillery: 2.0.0-34
Node.js:   v16.16.0
OS:        darwin
```
