### ISSUE TITLE
Hi @DanielGubay 👋 Artillery v1 is no longer maintained. Please try using Artillery v2.

### ISSUE THREAD

**Issue by DanielGubay** [artilleryio/artillery#2018]
Hi @DanielGubay 👋 Artillery v1 is no longer maintained. Please try using Artillery v2.

_Originally posted by @hassy in https://github.com/artilleryio/artillery/issues/2017#issuecomment-1664583616_
            

hi so I'm now attempting to use v2.0.0-0. and now I am running into this issue (node:4353) [MODULE_NOT_FOUND] Error Plugin: artillery: Cannot find module 'artillery-pro'

**Comment by hassy** [comment]
could you try the most recent release of Artillery please - `v2.0.0-35`

**Comment by DanielGubay** [comment]
tried that also and got this

(node:5703) [MODULE_NOT_FOUND] Error Plugin: artillery: Cannot find module 'artillery-pro'
Require stack:
- /home/ubuntu/node_modules/artillery/lib/cmds/aws/run.js
- /home/ubuntu/node_modules/@oclif/config/lib/plugin.js
- /home/ubuntu/node_modules/@oclif/config/lib/config.js
- /home/ubuntu/node_modules/@oclif/config/lib/index.js
- /home/ubuntu/node_modules/@oclif/command/lib/command.js
- /home/ubuntu/node_modules/@oclif/command/lib/index.js
- /home/ubuntu/node_modules/artillery/bin/artillery
module: @oclif/config@1.18.16
task: toCached
plugin: artillery
root: /home/ubuntu/node_modules/artillery

**Comment by hassy** [comment]
It seems like some sort of an issue with your environment. E.g. running a fresh install of Artillery in a clean Docker container:

![CleanShot 2023-08-04 at 08 40 27](https://github.com/artilleryio/artillery/assets/1490/c7e1f780-c97f-4296-97cc-c3f2fc2db795)
