### ISSUE TITLE
Cannot send same key in formData

### ISSUE THREAD

**Issue by musenaw** [artilleryio/artillery#2020]
I want to send the same key name in a form data, but due its done as object only one can be sent.
[solution to send a file with example](https://github.com/artilleryio/artillery/issues/320#issuecomment-329448748)

Version info: 
```
VERSION INFO:

Artillery Core: 2.0.0-26
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v18.16.0
OS:      linux
```

Is there a way to send multiple key - values with same name in a formData?

**Comment by bernardobridge** [comment]
Hey @musenaw. This isn't currently supported by using the built-in `form-data`, as it's an object (as you said).

However, you should be able to leverage Artillery's hooks to do this. You can do it for example in a beforeRequest hook (https://www.artillery.io/docs/reference/engines/http#beforerequest-hooks), installing the `form-data` npm package (which we also use in Artillery:

```js
const FormData = require('form-data');

function setFormData(req, context, ee, next) {
    const form = new FormData();
    form.append('my_field', 'my value')
    form.append('my_field', 'my value2');
    req.body = form
    next();
};

module.exports = {
    setFormData
}
```

And then call this function in your scenario:
```yaml
  - flow:
    - post:
        url: '/'
        beforeRequest: 'setFormData'
```

_Note: you would need to remove the formData fields from your scenario YAML, as that would override this._
