### ISSUE TITLE
virtual user fails

### ISSUE THREAD

**Issue by DanielGubay** [artilleryio/artillery#2024]
when running a load test my virtual users fail everytime and unable to see any real data. This is all ran on a nginx load gen

Version info: 
```
v2.0.0-35
```

Running this command: 
```
artillery run asciiart-load-test.yml
```

I expected to see this happen:

expect to see user X number of created in X amount of time

Instead, this happened:

**Test run id: t9mmg_6mc39ae4retf58f3f5qd9fqz39bnp_xp3x
Phase started: Warm up phase (index: 0, duration: 60s) 16:53:32(+0000)

--------------------------------------
Metrics for period to: 16:53:40(+0000) (width: 6.002s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 7
http.request_rate: ............................................................. 1/sec
http.requests: ................................................................. 7
vusers.created: ................................................................ 7
vusers.created_by_name.0: ...................................................... 7
vusers.failed: ................................................................. 7

Warning: multiple batches of metrics for period 1691427210000 2023-08-07T16:53:30.000Z
--------------------------------------
Metrics for period to: 16:53:50(+0000) (width: 9.054s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 19
http.request_rate: ............................................................. 2/sec
http.requests: ................................................................. 19
vusers.created: ................................................................ 19
vusers.created_by_name.0: ...................................................... 19
vusers.failed: ................................................................. 19

Warning: multiple batches of metrics for period 1691427220000 2023-08-07T16:53:40.000Z
--------------------------------------
Metrics for period to: 16:54:00(+0000) (width: 9.102s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 24
http.request_rate: ............................................................. 3/sec
http.requests: ................................................................. 24
vusers.created: ................................................................ 24
vusers.created_by_name.0: ...................................................... 24
vusers.failed: ................................................................. 24

Phase completed: Warm up phase (index: 0, duration: 60s) 16:54:32(+0000)

Phase started: Ramp up load (index: 1, duration: 60s) 16:54:32(+0000)

Warning: multiple batches of metrics for period 1691427230000 2023-08-07T16:53:50.000Z
--------------------------------------
Metrics for period to: 16:54:10(+0000) (width: 9.104s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 30
http.request_rate: ............................................................. 3/sec
http.requests: ................................................................. 30
vusers.created: ................................................................ 30
vusers.created_by_name.0: ...................................................... 30
vusers.failed: ................................................................. 30

Warning: multiple batches of metrics for period 1691427240000 2023-08-07T16:54:00.000Z
--------------------------------------
Metrics for period to: 16:54:20(+0000) (width: 9.155s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 40
http.request_rate: ............................................................. 4/sec
http.requests: ................................................................. 40
vusers.created: ................................................................ 40
vusers.created_by_name.0: ...................................................... 40
vusers.failed: ................................................................. 40

Warning: multiple batches of metrics for period 1691427250000 2023-08-07T16:54:10.000Z
--------------------------------------
Metrics for period to: 16:54:30(+0000) (width: 9.157s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 44
http.request_rate: ............................................................. 5/sec
http.requests: ................................................................. 44
vusers.created: ................................................................ 44
vusers.created_by_name.0: ...................................................... 44
vusers.failed: ................................................................. 44

Warning: multiple batches of metrics for period 1691427260000 2023-08-07T16:54:20.000Z
--------------------------------------
Metrics for period to: 16:54:40(+0000) (width: 9.956s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 50
http.request_rate: ............................................................. 5/sec
http.requests: ................................................................. 50
vusers.created: ................................................................ 50
vusers.created_by_name.0: ...................................................... 50
vusers.failed: ................................................................. 50

Warning: multiple batches of metrics for period 1691427270000 2023-08-07T16:54:30.000Z
--------------------------------------
Metrics for period to: 16:54:50(+0000) (width: 9.954s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 60
http.request_rate: ............................................................. 6/sec
http.requests: ................................................................. 60
vusers.created: ................................................................ 60
vusers.created_by_name.0: ...................................................... 60
vusers.failed: ................................................................. 60

Warning: multiple batches of metrics for period 1691427280000 2023-08-07T16:54:40.000Z
--------------------------------------
Metrics for period to: 16:55:00(+0000) (width: 9.955s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 68
http.request_rate: ............................................................. 7/sec
http.requests: ................................................................. 68
vusers.created: ................................................................ 68
vusers.created_by_name.0: ...................................................... 68
vusers.failed: ................................................................. 68

Phase completed: Ramp up load (index: 1, duration: 60s) 16:55:32(+0000)

Phase started: Spike phase (index: 2, duration: 30s) 16:55:32(+0000)

Warning: multiple batches of metrics for period 1691427290000 2023-08-07T16:54:50.000Z
--------------------------------------
Metrics for period to: 16:55:10(+0000) (width: 9.956s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 76
http.request_rate: ............................................................. 8/sec
http.requests: ................................................................. 76
vusers.created: ................................................................ 76
vusers.created_by_name.0: ...................................................... 76
vusers.failed: ................................................................. 76

Warning: multiple batches of metrics for period 1691427300000 2023-08-07T16:55:00.000Z
--------------------------------------
Metrics for period to: 16:55:20(+0000) (width: 9.956s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 84
http.request_rate: ............................................................. 9/sec
http.requests: ................................................................. 84
vusers.created: ................................................................ 84
vusers.created_by_name.0: ...................................................... 84
vusers.failed: ................................................................. 84

Warning: multiple batches of metrics for period 1691427310000 2023-08-07T16:55:10.000Z
--------------------------------------
Metrics for period to: 16:55:30(+0000) (width: 9.956s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 92
http.request_rate: ............................................................. 11/sec
http.requests: ................................................................. 92
vusers.created: ................................................................ 92
vusers.created_by_name.0: ...................................................... 92
vusers.failed: ................................................................. 92

Phase completed: Spike phase (index: 2, duration: 30s) 16:56:02(+0000)

Warning: multiple batches of metrics for period 1691427320000 2023-08-07T16:55:20.000Z
--------------------------------------
Metrics for period to: 16:55:40(+0000) (width: 9.957s)
--------------------------------------

errors.ECONNREFUSED: ........................................................... 110
http.request_rate: ............................................................. 15/sec
http.requests: ................................................................. 110
vusers.created: ................................................................ 110
vusers.created_by_name.0: ...................................................... 110
vusers.failed: ................................................................. 110

All VUs finished. Total time: 2 minutes, 32 seconds

--------------------------------
Summary report @ 16:56:06(+0000)
--------------------------------

errors.ECONNREFUSED: ........................................................... 1230
http.request_rate: ............................................................. 17/sec
http.requests: ................................................................. 1230
vusers.created: ................................................................ 1230
vusers.created_by_name.0: ...................................................... 1230
vusers.failed: ................................................................. 1230

Checks:
fail: http.response_time.p99 < 100
fail: http.response_time.p95 < 75**

Files being used:
```
config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  # not actual ip address changed it for privacy  
  target: http:privateip:80
  phases:
    - duration: 60
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 60
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 30
      arrivalRate: 10
      rampTo: 30
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  ensure:
      thresholds:
        - http.response_time.p99: 100
        - http.response_time.p95: 75
scenarios:
  - flow:
      - loop:
        - get:
            url: "/1kb"
        count: 100
```

**Comment by bernardobridge** [comment]
Hi @DanielGubay 

This could be an issue with your local nginx setup. You're trying to hit your own application, right, not Artillery's Asciiart server?

Alternatively, assuming you're trying to hit your own application and trying to run `artillery` in the same host as your application that's using `nginx`, you might be suffering from the same issue described here: https://github.com/artilleryio/artillery/issues/1676#issuecomment-1317685622, originating from a NodeJS problem. If that's the case, can you try pointing to the local IP address of the application instead?

**Comment by DanielGubay** [comment]
thats 

> Hi @DanielGubay
> 
> This could be an issue with your local nginx setup. You're trying to hit your own application, right, not Artillery's Asciiart server?
> 
> Alternatively, assuming you're trying to hit your own application and trying to run `artillery` in the same host as your application that's using `nginx`, you might be suffering from the same issue described here: [#1676 (comment)](https://github.com/artilleryio/artillery/issues/1676#issuecomment-1317685622), originating from a NodeJS problem. If that's the case, can you try pointing to the local IP address of the application instead?

Hi @bernardobridge. I am trying to hit my own application. I target it by doing https:ipAdressOfServer:80

**Comment by DanielGubay** [comment]
Had to sort out an internal environment issue. It's working now.
