### ISSUE TITLE
No validation or extended formats for duration

### ISSUE THREAD

**Issue by rfalke** [artilleryio/artillery#2065]
Version info: 
```
2.0.0-35
```

Running this command: 
```
artillery some_script.yaml
```

I expected to see this happen:

If I provide `duration: 3m`, `duration: 3min`, `duration: "3m"` or `duration: "3min"` I expect that either the value is rejected (because only integer seconds are supported) and artillery doesn't run or that this phase runs for 3 minutes.

Instead, this happened:

It just runs. I stopped it after 15min. No idea how this is parsed.

**Comment by bernardobridge** [comment]
Hey @rfalke ! Thank you for reporting this.

We actually had in our pipeline to implement this feature soon (ability to specify different time formats). We'll resolve the bug you mentioned as we do that. I'll update here once we release this :)

**Comment by bernardobridge** [comment]
Released on https://github.com/artilleryio/artillery/releases/tag/v2.0.0-37
