### ISSUE TITLE
Add application key variable for Datadog plugin

### ISSUE THREAD

**Issue by yvesDenis** [artilleryio/artillery#2066]
The Datadog integration in Artillery via the publish-metrics plugin is not working well. Recent dogapi library versions allowed to use the DD_APP_KEY environment variable cause in many organisations, access to Datadog resources are audited and controlled(scoped) by the application keys.
For instance in my company, the Datadog application key is mandatory to programmatically interact with Datadog.

Version info: 
```
2.0.0-36
```

Running this command: 
```
artillery run 
```

**Comment by bernardobridge** [comment]
This is released on version `2.0.0-37`! Thanks for your contribution 🙇
