### ISSUE TITLE
Error attempting run-fargate: InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists

### ISSUE THREAD

**Issue by colmtroy** [artilleryio/artillery#2079]
I've an IAM user setup per https://www.artillery.io/docs/load-testing-at-scale/aws-fargate#iam-permissions
with `AdministratorAccess`

![](https://i.imgur.com/Wx6ewd7.png)

But I'm getting an error at run time which would suggest `AdministratorAccess` isn't sufficient? 

Version info: 
```
Artillery: 2.0.0-36
Node.js:   v16.13.1
OS:        darwin
```

Running this command: 
```
artillery run-fargate \  
   --region us-east-1 \
   --count 10 \
   order-check.yml
```

I expected to see this happen:

- Playwright Test should run in Fargate

Instead, this happened:

```
Checking AWS connectivity... [15:41:10]
Checking cluster... [15:41:10]
InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
```

**Comment by bernardobridge** [comment]
Hello @colmtroy .

I've tried this out on our AWS account with an Administrator role, and it's working.

You may be running into this: https://cloudstep.io/2019/02/19/unable-to-assume-the-service-linked-role/. It looks like it may happen when it's the first ECS cluster in the account. I think it should start working if you try to follow the suggestion there (run `aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com` yourself to create the service linked role).

Let me know if it helps. We'll look if we can improve something in the CLI to account for this situation - it's a weird UX from AWS!

**Comment by colmtroy** [comment]
Thanks @bernardobridge 

I tried 

```
aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com
```

and now I get

```
An error occurred (InvalidInput) when calling the CreateServiceLinkedRole operation: Service role name AWSServiceRoleForECS has been taken in this account, please try a different suffix
```

**Comment by bernardobridge** [comment]
@colmtroy can you try to run the ECS Get Started wizard and then run the test? 

From what I read online, running that is another possibility for resolving this, as it can reconfigure something internally in AWS that allows the Administrator role to assume the service linked role.

If that doesn't work, I suggest contacting AWS support, as unfortunately this seems like a general AWS issue that you'd get when trying to create the first ecs cluster in the account via API.

**Comment by colmtroy** [comment]
@bernardobridge 

>can you try to run the ECS Get Started wizard and then run the test?

I ran the wizard and created a default cluster with no issues.

While in there I noticed that artillery had at least gotten this far

![](https://i.imgur.com/WCdGZdy.png)

So I tried re-running my original run-fargate command and got the following

```
artillery run-fargate \                                                                                                 ░▒▓ 1 х │ took 12s │ at 17:56:48 
   --region us-east-1 \
   --count 10 \
   order-check.yml
Checking AWS connectivity... [18:01:12]
Checking cluster... [18:01:12]
Tags: name:order-check.yml [18:01:14]
Test run ID: t6cza_exh3cfa56b4wdx7qxtmzq9j8zb4ea_89pm [18:01:14]
Preparing launch platform... [18:01:14]
Error: Could not find public subnets in default VPC
Error: Could not find public subnets in default VPC
```

I also tried deleting that `artilleryio-cluster` and starting from scratch, but no dice :/ 

I can contact AWS support, but it seems like there might be more than one issue at play here given the new subnet error?

**Comment by bernardobridge** [comment]
Hey @colmtroy , thanks for that! 

Yes, it seems running the wizard worked and you're through to Artillery creating resources now, so we're past the original error I believe.

I'll try to take a look at the new error from our side, but it may again be something with your AWS account setup, as default vpcs should have public subnets by default: https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html

Maybe try going into VPC in AWS console and see if there's a wizard - it may be that you don't have a default vpc setup?

**Comment by colmtroy** [comment]
@bernardobridge i'll take a look at that now.

As an aside, I created a separate aws cli user with the policy json file located here
https://www.artillery.io/docs/load-testing-at-scale/aws-fargate#iam-permissions

Same VPC error...

**Comment by bernardobridge** [comment]
The error would be the same with that policy, if the account / region doesn't have a default vpc with public subnets, it wouldn't be able to get it. I haven't had a chance to look at the code as I'm not in front of the laptop right now, but I don't think it's a permissions issue right now.

**Comment by colmtroy** [comment]
Thanks for your super quick replies @bernardobridge btw - really appreciated :) 

So I made some progress on this....

Turns out for whatever reason us-east-1 had no default VPC!
(Aside: seems to be a pretty common issue https://stackoverflow.com/a/56288327 )

I created a default VPCs for both eu-west-1 and us-west-1 

So now when I execute I can see everything appear to execute correctly, but no actual requests arrive at the testing target.

eu-west-1

```
artillery run-fargate \                                                                                                 ░▒▓ 1 х │ took 10s │ at 18:31:12 
   --region eu-west-1 \
   --count 10 \
   order-check.yml
Checking AWS connectivity... [18:44:20]
Checking cluster... [18:44:20]
Tags: name:order-check.yml [18:44:20]
Test run ID: tj9by_4ztpfm6zk49cwh7ehh8zc97hb6qab_b7t9 [18:44:20]
Preparing launch platform... [18:44:20]
Environment:
  Account:     856973387453
  Region:      eu-west-1
  Count:       10
  Cluster:     artilleryio-cluster
  Launch type: ecs:fargate
  Subnets:     subnet-008e3974b333edf01, subnet-04f7396ea00a11dd8, subnet-07880b81232846ed1 (autodetected)
  

Preparing test bundle... [18:44:22]
Test bundle prepared... [18:44:22]
Test bundle contents:
┌─────────────────────────────┬─────────┬─────────────────────┐
│ Name                        │ Type    │ Notes               │
├─────────────────────────────┼─────────┼─────────────────────┤
│ yml                         │ file    │                     │
├─────────────────────────────┼─────────┤                     │
│ js                          │ file    │                     │
├─────────────────────────────┼─────────┼─────────────────────┤
│ artillery-engine-playwright │ package │ not in package.json │
└─────────────────────────────┴─────────┴─────────────────────┘

Launching workers... [18:44:24]
Waiting for Fargate... [18:44:25]
Waiting for workers to start: pending: 10 [18:44:57]
Waiting for workers to start: pending: 10 [18:45:07]
Waiting for workers to start: pending: 10 [18:45:17]
Waiting for workers to start: pending: 10 [18:45:27]
Waiting for workers to come online... [18:45:27]
Workers are running, waiting for reports... [18:46:00]
--------------------------------
Summary report @ 18:46:09(+0100)
--------------------------------

No measurements recorded during this period
Test run completed: tj9by_4ztpfm6zk49cwh7ehh8zc97hb6qab_b7t9 [18:46:09]
```

same result for us-west-1

```
artillery run-fargate \          ░▒▓ 1 х │ took 4s │ at 18:49:05 
   --region us-west-1 \
   --count 10 \
   order-check.yml
Checking AWS connectivity... [18:49:45]
Checking cluster... [18:49:45]
Tags: name:order-check.yml [18:49:48]
Test run ID: tyd57_n3dm6eqmkwd3n4zbdmhhfmqb65xxt_crtt [18:49:48]
Preparing launch platform... [18:49:48]
Environment:
  Account:     856973387453
  Region:      us-west-1
  Count:       10
  Cluster:     artilleryio-cluster
  Launch type: ecs:fargate
  Subnets:     subnet-0f830b6a, subnet-dd79b784 (autodetected)
  

Preparing test bundle... [18:49:54]
Test bundle prepared... [18:49:54]
Test bundle contents:
┌─────────────────────────────┬─────────┬─────────────────────┐
│ Name                        │ Type    │ Notes               │
├─────────────────────────────┼─────────┼─────────────────────┤
│ yml                         │ file    │                     │
├─────────────────────────────┼─────────┤                     │
│ js                          │ file    │                     │
├─────────────────────────────┼─────────┼─────────────────────┤
│ artillery-engine-playwright │ package │ not in package.json │
└─────────────────────────────┴─────────┴─────────────────────┘

Launching workers... [18:49:56]
Waiting for Fargate... [18:49:57]
Waiting for workers to start: pending: 10 [18:50:33]
Waiting for workers to start: pending: 10 [18:50:44]
Waiting for workers to start: pending: 10 [18:50:55]
Waiting for workers to start: pending: 10 [18:51:06]
Waiting for workers to come online... [18:51:06]
Workers are running, waiting for reports... [18:52:00]
--------------------------------
Summary report @ 18:52:11(+0100)
--------------------------------

No measurements recorded during this period
Test run completed: tyd57_n3dm6eqmkwd3n4zbdmhhfmqb65xxt_crtt [18:52:12]
```

Any ideas what might cause that issue?

**Comment by colmtroy** [comment]
@bernardobridge the script runs fine locally. I'm making some headway here - but yet to bottom it out fully. Will report back once I have something definitive.

>P.S. one thing I noticed is it's picking up a file named yml and js in the Test bundle contents which seems weird to me. It might be something there

This does indeed seem to be a contributing factor. I'll do some more troubleshooting tomorrow and will let you know.

**Comment by bernardobridge** [comment]
Hey @colmtroy - great ! If possible, to keep the issues scoped (and help other users find problems), would you be okay to open a new issue for this problem, since it's unrelated to the original issue?

In the meantime, if the test bundling is the problem, you might want to take a look at this thread in Discussions: https://github.com/artilleryio/artillery/discussions/1940#discussioncomment-6355454. Some people had issues related to their file structure there (which we haven't been able to replicate yet), so if you think it's the same problem, it could help to post there. Otherwise, a new issue would be ideal. Thanks!

**Comment by colmtroy** [comment]
>Hey @colmtroy - great ! If possible, to keep the issues scoped (and help other users who might be looking for help), would you be okay to open a new issue for this problem, since it's unrelated to the original issue?

Of course :) Will open a separate issue for you now - it's a doozy too :) 

I'll close this issue - thanks again!
