### ISSUE TITLE
Running test on lambda fails with "Error: Cannot find module '@oclif/command'"

### ISSUE THREAD

**Issue by NaimSakaamini** [artilleryio/artillery#2232]
Version info: 
```
Artillery: 2.0.0-31
Node.js:   v18.17.1
OS:        linux
```

Running this command: 
```
const artilleryExecutablePath = './node_modules/artillery/bin/run';
spawnSync(
      artilleryExecutablePath,
      [
        'run',
        scriptPath,
        '--output',
        outputPath,
        '--platform',
        'aws:lambda',
        '--platform-opt',
        'region=us-east-1'
      ]
    );
```

I expected to see this happen:

Run the test

Instead, this happened:

Test run id: tbkrw_xdx9zdwhde9ftz98dyx3yckhtygtn_aqbh
NOTE: AWS Lambda support is experimental. Not all Artillery features work yet.
For details please see https://docs.art/aws-lambda
λ Creating AWS Lambda function...
- Bundling test data
- script.yaml
- payload.js
- Installing dependencies
- Creating zip package
Preparing AWS environment...
- Lambda function: artilleryio-
- Region: us-east-1
- AWS account: 
[]: A Lambda function has exited with an error. Reason: ArtilleryError
{
stdout: '',
stderr: 'node:internal/modules/cjs/loader:1031\n' +
'  throw err;\n' +
'  ^\n' +
'\n' +
"Error: Cannot find module '@oclif/command'\n" +
'Require stack:\n' +
'- /var/task/node_modules/artillery/bin/run\n' +
'    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)\n' +
'    at Function.Module._load (node:internal/modules/cjs/loader:873:27)\n' +
'    at Module.require (node:internal/modules/cjs/loader:1100:19)\n' +
'    at require (node:internal/modules/cjs/helpers:119:18)\n' +
'    at Object.<anonymous> (/var/task/node_modules/artillery/bin/run:7:18)\n' +
'    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n' +
'    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n' +
'    at Module.load (node:internal/modules/cjs/loader:1076:32)\n' +
'    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n' +
'    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {\n' +
"  code: 'MODULE_NOT_FOUND',\n" +
"  requireStack: [ '/var/task/node_modules/artillery/bin/run' ]\n" +
'}\n'
}
--------------------------------
Summary report @ 01:41:17(+0000)
--------------------------------

Files being used:
```

```

**Comment by bernardobridge** [comment]
Hello @saurabhmarwaha and anyone else reading here 👋

Since Artillery 2.0.14, Lambda Container Images are the default, and zipfiles are no longer supported. This type of error should no longer happen.

If you still run into another issue, please open [another issue](https://github.com/artilleryio/artillery/issues) with it and we'll take a look!
