### ISSUE TITLE
Set a timeout per request

### ISSUE THREAD

**Issue by cbraillon** [artilleryio/artillery#2267]
Can we have the possibility to set a timeout per request which takes the priority over the global timeout ?
In my http scenario, I have a request that may take a little longer to answer but i don't want to increase the timeout of the others requests.

**Comment by bernardobridge** [comment]
Hi @cbraillon.

You should be able to use a [beforeRequest](https://www.artillery.io/docs/reference/engines/http#beforerequest-hooks) hook to achieve that:

```js
function myBeforeRequestHandler(req, context, ee, next) {

    //req gives you access to the got package request object, including its timeout, which you can override for that particular request
    console.log(req)
    req.timeout = 1;
    next();
};
```

You'll see something like this in the metrics:
```
--------------------------------------
Metrics for period to: 13:26:50(+0000) (width: 0.035s)
--------------------------------------

errors.ETIMEDOUT: .............................................................. 1
```

Hope that helps!
