### ISSUE TITLE
Always getting the last scenario when using the new --scenario-name flag

### ISSUE THREAD

**Issue by feraball** [artilleryio/artillery#2313]
Version info: 
```
Artillery: 2.0.0-38
Node.js:   v20.10.0
OS:        darwin

```

Running this command: 
```
artillery run --scenario-name "MyScenario" -o reports/my-report.json my-super-load-test.yml
```

I expected to see this happen:

I expect to see Artillery running only "MyScenario" scenario.

Instead, this happened:

It always runs the last scenario in the array. 

Your filtering function always update the "foundIndex" even when the scenarioName does not match, so at the end of the loop it's always the last index:
```
packages/core/lib/runner.js:

327 if (options.scenarioName) {
328     let foundIndex;
329     const foundScenario = script.scenarios.filter((scenario, index) => {
340       foundIndex = index;
341       return new RegExp(options.scenarioName).test(scenario.name);
342     });
...
```
Also, the test file that covers this feature is asserting the Scenario number 2 so it passes but it won't if it tries to assert using the first scenario.

Files being used:
```
packages/core/lib/runner.js
packages/artillery/test/cli/command-run.test.js
packages/artillery/test/scripts/scenario-named/scenario.yml
```

**Comment by bernardobridge** [comment]
Hey @feraball,

Thanks for the report 🙇 . Completely missed that in the original PR 🤦 !

Fix is open for it, and will be released in the next Artillery CLI version.

**Comment by bernardobridge** [comment]
Fixed in https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.1
