### ISSUE TITLE
Regions Supported for Artillery (Not Pro version)

### ISSUE THREAD

**Issue by nithinr19** [artilleryio/artillery#2377]
Hi Team,

Can you let us know what all regions are supported by Artillery. i am trying to execute a yaml in us-west-2 but its throwing error as unsupported.

"- Unsupported region (us-west-2) provided. Please specify one of: us-east-1, us-west-1, eu-west-1, eu-central-1, ap-south-1, ap-northeast-1"

**Comment by hassy** [comment]
The version of Artillery you're running supports 6 regions (the ones listed in the error message).

We added 12 more regions in https://github.com/artilleryio/artillery/pull/2358 including `us-west-2`. This will be released in the next version of Artillery later this week.

**Comment by nithinr19** [comment]
Thankyou for the quick response.

**Comment by nithinr19** [comment]
Still getting the same expection. - Unsupported region (eu-west-2) provided. Please specify one of: us-east-1, us-west-1, eu-west-1, eu-central-1, ap-south-1, ap-northeast-1. When can i expect the next version artillery

**Comment by hassy** [comment]
v2.0.4 was out last week. Make sure you're running the latest version (you can check with `artillery -v`) and if not install it with `npm install -g artillery@latest`
