### ISSUE TITLE
Artillery http test wont respect duration time and keep running

### ISSUE THREAD

**Issue by dirtyren** [artilleryio/artillery#2387]
Version info: v2.0.1 with HLH plugins nodejs 18

The test should respect the duration time and it just keeps on running log after the duration time has elapsed.
When I am running a normal http simple test, it reaches max Vusers and keeps running, but, when when running a streaming test using the HLS extension, the test will reach max  Vuers and keep running for the time setup on duration, when Artillery will stop using network resources and CPU, but it will not stop running. The test will have stopped, but artillery will keep on running.

Anything I can do to help, any info you need, just let me know.

Tks.

**Comment by dirtyren** [comment]
Hey guys, I'd like to update some tests that we did this afternoon.
The problem occurs when running artillery inside testkube using the testkube binary runner and exporting metrics to pushgateway.
   If we disable the plugin pushmetrics exporting to pushgateway or we do not use the runner binary, using artillery run instead, the problem does not occur.
   It seems there is something happening when using pushmetrics and the runner that we could not yet pinpoint.

   []s.

**Comment by hassy** [comment]
hi @dirtyren 👋 thank you for the extra information - it doesn't look like it's going to be easy to replicate, and it sounds like it could be due to some interaction between an Artillery plugin and testkube.

In general we'd always recommend running Artillery directly and avoid using any wrappers over it that try to abstract it away.

**Comment by dirtyren** [comment]
hi @hassy , I will test artillery by it self and get back to you, to see if the problem is the interaction with testkube. Tks for getting back to me.
   []s.
