### ISSUE TITLE
Running into InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes issue on run-lambda

### ISSUE THREAD

**Issue by md1440** [artilleryio/artillery#2403]
Version info: 
```
2.0.3
```

Running this command: 
```
> artillery run-lambda --region eu-central-1 ***SNIP***
```

I expected to see this happen:

the Lambda being deployed and the test being started

Instead, this happened:

λ Creating AWS Lambda function...
- Bundling test data
  - scenarios/scenario_1.yml
  - processors/processor.js
  - package.json
- Installing dependencies
- Installing extra engines & plugins: artillery, artillery-plugin-apdex, artillery-plugin-metrics-by-endpoint, dotenv, prettier
- Creating zip package
Preparing AWS environment...
⠏ ***SNIP***/node_modules/.pnpm/aws-sdk@2.1532.0/node_modules/aws-sdk/lib/protocol/json.js:80
  resp.error = util.error(new Error(), error);
                          ^

InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes

Files being used:
```
  "dependencies": {
    "artillery": "~2.0.3",
    "artillery-plugin-metrics-by-endpoint": "~1.2.0",
    "artillery-plugin-apdex": "~1.0.1",
    "dotenv": "^16.0.3"
  },
  "devDependencies": {
    "prettier": "^2.8.8"
  },

scenario:

config:
  target: ***SNIP***
  phases:
    - duration: 30
      arrivalRate: 10 # no. of requests
      name: Sustained load
  plugins:
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  processor: "../processors/processor.js"
scenarios:
  - name: "***SNIP***"
    flow:
      - post:
          url: "/***SNIP***/{{ $env.***SNIP*** }}/recipient"
          headers:
            Authorization: "{{ $env.***SNIP*** }}"
            Content-Type: application/json
          beforeRequest: "generateRecipientAddressData"
          json:
            address: "{{ address }}"
            variation: "{{ variation }}"


```

The zipped file on s3 has ~ 116mb, unpacked it's ~ 430MB with 99% of that being the node modules
The processor.js just generates some simple userdate. I even switched to using the fake-data plugin instead of faker but that did not make any difference.

Also it's a little curious why prettier as a devDependency gets bundled.

UPDATE: after some investigation it seems that instead of bundling the local project node_moduls it takes the entire common/config node_modules of our Rushstack monorepo.

**Comment by md1440** [comment]
When excluding the processor from the config it works to deploy to AWS

```
function generateRecipientAddressData(requestParams, ctx, ee, next) {
  ctx.vars.address = {
    firstName: randFirstName(),
    lastName: randLastName(),
    street: randStreetName(),
    houseNumber: "12",
    address2: "",
    zipCode: "77777",
    city: "Tolle Stadt",
    country: "Deutschland",
  };
  ctx.vars.variation = 1;

  return next();
}

module.exports = {
  generateRecipientAddressData,
};
```

There is not really anything particular going on in this processor...

**Comment by bernardobridge** [comment]
Hi @md1440,

Thanks for the thorough report 🙇‍♂️ ! We are aware that currently the bundle size may be close to the limits, and are looking to improve this setup soon.

In the meantime, there are a couple of things I notice in your particular case:
- You do not need to install `artillery-plugin-metrics-by-endpoint` or `artillery-plugin-apdex` in your package.json. Artillery already includes those by default;
- `dotenv` should also be unnecessary. Have you tried using the `--dotenv` [flag](https://www.artillery.io/docs/reference/cli/run-lambda#shared-flags)? It should allow you to auto-load the dotenv file you need.
- It seems to also be installing `prettier` in the bundle. For now, it might be worth not installing prettier in this package.json, as it may be pushing you over the edge.

**Comment by md1440** [comment]
Thank you @bernardobridge, that was helpful. In the end I got it to run, what made the difference after applying all the steps you mentioned was to not call the custom processor.js in the config, rather use a .csv based payload. For the moment that is sufficient but would be great to see it improved to allow for a little broader spectrum of use cases running on lambda.
