### ISSUE TITLE
Fargate timed out error

### ISSUE THREAD

**Issue by hassy** [artilleryio/artillery#2427]
### Discussed in https://github.com/artilleryio/artillery/discussions/2426

<div type='discussions-op-text'>

<sup>Originally posted by **Mathdon** January 17, 2024</sup>
Hi, I tired running a test in eu-west-w 2 on fargate and had this error

Error: Timed out waiting for workers to sync

It linked me to this bit of the code:

https://github.com/artilleryio/artillery/blob/main/packages/artillery/lib/platform/aws-ecs/legacy/run-cluster.js#L1742

Do you know what would cause this?

Thanks</div>

**Comment by bernardobridge** [comment]
👋 Fixed in [Artillery v2.0.5](https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.5)
