### ISSUE TITLE
Fargate: AccessDeniedException displayed trying to update Log group retention policy

### ISSUE THREAD

**Issue by robin-miro** [artilleryio/artillery#2486]
Thank you for filing a bug report! 🐛 Please provide a short summary of the bug,
along with any information you feel relevant to replicating it.
\\\\\\\\\\\\\\\\-->

Version info:

```
VERSION INFO:

Artillery: 2.0.5
Node.js:   v21.6.1
OS:        darwin
```

Running this command:

```
artillery run-fargate --region eu-west-1 scenarios/login/scenario.yml -e production --count=2 --subnet-ids=subnet-1,subnet-2
```

I expected to see this happen:

*The log group artilleryio-log-group/artilleryio-cluster is created*

Instead, this happened:

\\\\\\\\\\\\\\\*I see an error from cli that the log group does not exist, I created it manually, and CLI shows it doesn't have permission with IAM template provided

```
AccessDeniedException: User: arn:aws:sts::123456:assumed-role/artilleryio-cli-role/test-session is not authorized to perform: logs:PutRetentionPolicy on resource: arn:aws:logs:eu-west-1:123456:log-group:artilleryio-log-group/artilleryio-cluster:log-stream: because no identity-based policy allows the logs:PutRetentionPolicy action
```

* 

Files being used:

```
<any>
```

**Comment by robin-miro** [comment]
Hey @bernardobridge , thanks for the swift reply.

### 1. About the IAM role

Yep, we also added that to the IAM role `artilleryio-cli-role` already, thanks for updating the docs, that would be more clear for others!  And this role is created by us to be able to assume from local laptop or from CI/CD to trigger the artillery test.

### 2. About the error
Yep, it's only the warnings, but I would like to highlight that the CloudWatch LogGroup is not created by CLI, more specifically: `arn:aws:logs:eu-west-1:123456:log-group:artilleryio-log-group/artilleryio-cluster` , meaning we must create it manually, currently to bypass it, we do it by ourselves, potentially & ideally maybe CLI should create it also. 

Better I should separate ticket if you prefer for the following:

### 3. About Datadog
We noticed that Datadog-agent is starting together with Artillery, from logs, it also tries to setup and connect datalog, however from `config`,  I don't even enable the datalog plugin, the datadog is a great feature,  but is it possible to disable it when running test from Fargate, meaning even no any traffic to Datadog.  I understand it won't really send metrics to datadog, but from a security perspective, maybe it's not ideal. WDYT?

**Comment by bernardobridge** [comment]
>Yep, it's only the warnings, but I would like to highlight that the CloudWatch LogGroup is not created by CLI, more specifically: arn:aws:logs:eu-west-1:123456:log-group:artilleryio-log-group/artilleryio-cluster , meaning we must create it manually, currently to bypass it, we do it by ourselves, potentially & ideally maybe CLI should create it also.

Hi @robin-miro . Are you sure it doesn't create the log group? The log group is automatically created by AWS ECS (Fargate) when it runs, but it needs the containers to actually start. You shouldn't need to manually create it at all. Perhaps the test didn't start, or you ended up early, so that's why the log group never got created?

It should be under: `/artilleryio-log-group/<NAME_OF_CLUSTER>`. 

---

>We noticed that Datadog-agent is starting together with Artillery, from logs, it also tries to setup and connect datalog, however from config, I don't even enable the datalog plugin, the datadog is a great feature, but is it possible to disable it when running test from Fargate, meaning even no any traffic to Datadog. I understand it won't really send metrics to datadog, but from a security perspective, maybe it's not ideal. WDYT?

At the moment the `datadog-agent` is always started. However, it's not sending any logs to Datadog if you don't have it configured. The container will exist there, but as you don't pass the configuration options (namely `DD_API_KEY`), it won't do anything - as it can't!

I do agree it can be confusing though, and we are in the process of replacing this setup with something else. 👍 Will update you when we know more.

**Comment by robin-miro** [comment]
Hey @bernardobridge , 

Sorry for late, i just get tried from an complete new AWS region. 

the error is:

```
Launching workers... [11:15:26]
Waiting for Fargate... [11:15:28]
WARNING: Max retries exceeded setting retention policy
ResourceNotFoundException: The specified log group does not exist.
    ...

WARNING: Max retries exceeded setting retention policy
ResourceNotFoundException: The specified log group does not exist.
    ...
}
Waiting for workers to start: pending: 1 [11:16:02]
Waiting for workers to start: pending: 1 [11:16:13]
Waiting for workers to start: pending: 1 [11:16:24]
Waiting for workers to start: pending: 1 [11:16:35]
Waiting for workers to come online... [11:16:35]
Workers are running, waiting for reports... [11:17:56]
```

**Comment by InesNi** [comment]
Hi @robin-miro 👋🏻,

> We noticed that Datadog-agent is starting together with Artillery, from logs, it also tries to setup and connect datalog, however from config, I don't even enable the datalog plugin, the datadog is a great feature, but is it possible to disable it when running test from Fargate, meaning even no any traffic to Datadog. I understand it won't really send metrics to datadog, but from a security perspective, maybe it's not ideal. WDYT?

I just wanted to update you that as of Artillery [v2.0.7](https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.7) the Datadog agent has been replaced with ADOT (AWS Distro for OpenTelemetry) which is loaded conditionally, so you should no longer see any Datadog-agent containers.
