### ISSUE TITLE
playwright tests not running in fargate with latest artillery version v2.0.7

### ISSUE THREAD

**Issue by prabhakaran-repos** [artilleryio/artillery#2542]
Running playwright tests in fargate with latest artillery version v2.0.7 fails with the following error:

05 March 2024 at 16:31 (UTC+5:30) | worker error, id: 1 browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1097/chrome-linux/chrome | -
-- | -- | --
05 March 2024 at 16:31 (UTC+5:30) | ╔═════════════════════════════════════════════════════════════════════════╗ | -
05 March 2024 at 16:31 (UTC+5:30) | ║ Looks like Playwright Test or Playwright was just installed or updated. ║ | -
05 March 2024 at 16:31 (UTC+5:30) | ║ Please run the following command to download new browsers: ║

Version info: v2.0.7
Running this command: npx artillery run-fargate --region ap-south-1 tests.yml

The same tests works in v2.0.6

**Comment by hassy** [comment]
Thanks @prabhakaran-repos. Unable to reproduce with 2.0.7 on [https://github.com/artilleryio/artillery/tree/main/examples/browser-load-testing-playwright](https://github.com/artilleryio/artillery/tree/main/examples/browser-load-testing-playwright). Is your test depending on a specific version of Playwright (in `package.json`) perhaps?

**Comment by prabhakaran-repos** [comment]
Even for me it works locally with run command. Only with run-fargate, it fails. 

This is my package.json, no direct dependency on playwright.
    "@aws-sdk/client-sqs": "^3.525.0",
    "artillery": "^2.0.6",
    "axios": "^1.6.7"

**Comment by bernardobridge** [comment]
Hi @prabhakaran-repos . Could you post a log of when you start your Fargate test? (it should say which files are being bundled).

I suspect that maybe your `package.json` file is being bundled to the worker, which is then causing artillery to be reinstalled and results in a browser mismatch.

**Comment by prabhakaran-repos** [comment]
Yes, package.json is bundled.

│ Name                                   │ Type    │ Notes │
├────────────────────────────────────────┼─────────┼───────┤
│ tests/ui-tests/test.yml                │ file    │       │
├────────────────────────────────────────┼─────────┤       │
│ tests/ui-tests/test.js                 │ file    │       │
├────────────────────────────────────────┼─────────┤       │
├────────────────────────────────────────┼─────────┤       │
│ test-data/ui-tests/tokens              │ file    │       │
├────────────────────────────────────────┼─────────┤       │
│ package.json                           │ file    │       │
├────────────────────────────────────────┼─────────┤       │
│ package-lock.json                      │ file    │       │
├────────────────────────────────────────┼─────────┼───────┤
│ @aws-sdk/client-sqs                    │ package │       │
├────────────────────────────────────────┼─────────┼───────┤
│ artillery                              │ package │       │
├────────────────────────────────────────┼─────────┼───────┤
│ axios                                  │ package

**Comment by bernardobridge** [comment]
Hey @prabhakaran-repos 👋 

This problem is happening due to keeping your `package.json` side by side with the test script, while including `artillery` as a direct dependency - this is one of the reasons why [we don't recommend installing Artillery as a dependency](https://www.artillery.io/docs/get-started/get-artillery#installing-as-a-devdependency-in-nodejs-projects).

To fix it, do one of the following:
- Don't include Artillery as a dependency
- Change your test folder hierarchy so that the scenario you're trying to run isn't at the same level as a `package.json` that contains Artillery as a dependency
