### ISSUE TITLE
How to get Summary Report data in after hooks processor

### ISSUE THREAD

**Issue by rajivnw** [artilleryio/artillery#2556]
I would like to fetch p95 and p99 values to save in a file from report which generated and shows in console after all VUs finished. So how I can access this report data in any hooks in processor.js? 

<img width="768" alt="image" src="https://github.com/artilleryio/artillery/assets/20470735/71643ec2-a92f-415d-b988-ebe85043d194">

**Comment by vikramjb** [comment]
@rajivnw 👋 

You can generate a json report file and the parse it from there or you can use the publish metrics plugin to push the metrics data to a third party service and extract it from there. 


@InesNi @hassy @bernardobridge Is there any other way?

**Comment by rajivnw** [comment]
@vikramjb I know that staff but I'm looking if there is any other way to get at runtime (without doing manual stuffs like parsing) after all scenarios finished. Just wanted to fetch p95 and p99 values to save in a CSV file.

**Comment by rajivnw** [comment]
@vikramjb I figure out this. Created a custom plugin and added below code.

 events.on('done', function (stats) {
    const report = stats.report();
    console.log({ report });
    fs.appendFileSync('plugin-data.csv', JSON.stringify(report.latency) + '\n');

  });

**Comment by rajivnw** [comment]
done
