### ISSUE TITLE
Example custom plugin does not work when adding a processor function

### ISSUE THREAD

**Issue by servohatred** [artilleryio/artillery#2575]
Version info: 
```
2.0.7
```

Running this command: 
```
artillery run myscenario.yml
```

I am trying to use the helloworld plugin in my project (https://github.com/artilleryio/artillery/blob/main/examples/artillery-plugin-hello-world/index.js). I have a ts processor file in there but I am getting this error when It's trying to add a custom hook function to the global object processor: 

This is the code not working : 
```
  script.config.processor = script.config.processor || {};
   // Add our custom function:
   script.config.processor['pluginHelloWorldAfterRequestHook'] = function (
     req,
     vuContext,
     events,
     next
   ) {
 
     console.log(self.greeting); // print greetingncrease custom counter
     return next(); // the hook is done, go on to the next one (or let Artillery make the request)
   };
```
And this is the error : 
```
TypeError: Cannot create property 'pluginHelloWorldAfterRequestHook' on string 'js transpiled file'
    at new ArtilleryHelloWorldPlugin (\plugins\artillery-plugin-hello-world.js:33:61)
    at Launcher.initPlugins (\node_modules\artillery\lib\launch-platform.js:214:31)
    at async Launcher.run (\node_modules\artillery\lib\launch-platform.js:414:5)

Node.js v20.3.1
```
I'm not sure if it has something to do with the transpiled file. 
 My intention is to share some data from the processor function to the plugin using context vars. For that intention I need to create an afterScenario hook to grab the context in the plugin code. Trying to make it work with the example plugin first . Thank you in advance!

**Comment by bernardobridge** [comment]
Hi @servohatred 👋 

I actually think that's a bug with the example plugin code, as it also fails with `.js` processor . I'll fix it shortly.

**Comment by servohatred** [comment]
> Fixed [here](https://github.com/artilleryio/artillery/pull/2577) @servohatred - just remove `use strict` from your plugin and it should work.

Thank you very much, tried that and it worked. A quick question if posible .... Does artillery support adding afterScenario hooks ? I can see an before request hook in the example but not sure about the other one.

**Comment by bernardobridge** [comment]
Glad it worked!

Yes we do support `afterScenario`/`beforeScenario` hooks (e.g. [http engine](https://www.artillery.io/docs/reference/engines/http#function-actions-and-beforescenario--afterscenario-hooks)), but it's worth noting that not all engines have it implemented. For example, the HTTP engine has those hooks, but Playwright engine does not.

**Comment by servohatred** [comment]
That was it, i've been trying that with the playwright engine but it's not working. Thank you for the clarification! Hope it gets implemented!
