### ISSUE TITLE
Headers in default Playwright config values are not being reflected in Artillery performance tests

### ISSUE THREAD

**Issue by sruthii38** [artilleryio/artillery#2593]
I have default headers that are configured in playwright.config.ts and it worked when running playwright test. When I call the same playwright test through artillery, it is not working.

This default config is specific to header.
I tried specifying config in different sections

config:
engines:
playwright:
contextOptions:
extraHTTPHeaders:
User-Agent: '****'
I have also tried setting at artillery default as well

config:
http:
defaults:
headers:
User-Agent: "*****"
None of these options worked.

Can you suggest a way to make this work?

**Comment by bernardobridge** [comment]
Hi @sruthii38, the `extraHTTPHeaders` option should work (but not the `config.http` option).

Can you please share your `config` + `scenario` using [Github Code Blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)? Without the proper formatting it's difficult to say what might be wrong.

**Comment by sruthii38** [comment]
Hi, the extraHTTPHeaders is working for initial URL load but the user on our website will get redirected by generating 302 status and authorize through headers but the default headers specified in Playwright are not being picked by artillery(Spec file in playwright is doing expected). The extraHTTPHeaders are passed only for the URL load but not for redirect urls so the performance tests are failing. Can you please help me with this blocker.
