### ISSUE TITLE
How to generate a HTML report

### ISSUE THREAD

**Issue by nithinkadam19** [artilleryio/artillery#2594]
Hi Team,

I am running a load test with Artillery V 2.0.4. when i run command "artillery report myresult.json". it is generating a basic html report. But not a report as shown in attachment. Attached is the basic HTML report.
<img width="720" alt="Basic_Report" src="https://github.com/artilleryio/artillery/assets/163103402/af34fcf7-5750-44fb-8b6e-c2ed1e62fa2d">

<img width="896" alt="image" src="https://github.com/artilleryio/artillery/assets/163103402/b64c67dd-89d5-427c-950e-71a7a984a49d">
<img width="896" alt="Screenshot 2024-03-22 165956" src="https://github.com/artilleryio/artillery/assets/163103402/df465ef7-aa32-44a6-9085-05ada8ed49c4">

Do i need to use a Pro version ?  or is there any other way i can generate a report similar to attached Artillery.io reportviwer one.

I had one more question: Is it possible to merge multiple json into single json and generate HTML report.

**Comment by hassy** [comment]
That other report was produced by a community tool (not an official Artillery project) which is no longer supported. [Artillery Cloud](https://www.artillery.io/cloud) is now the recommended way to visualize and analyze test reports.
