### ISSUE TITLE
artillery playwright launch options tracesDir not working

### ISSUE THREAD

**Issue by bshostak** [artilleryio/artillery#2636]
Hello, I am looking at the documentation [https://github.com/artilleryio/artillery-engine-playwright/blob/main/README.md](https://github.com/artilleryio/artillery-engine-playwright/blob/main/README.md) specifically: launchOptions - an object containing arguments to [browserType.launch()](https://playwright.dev/docs/api/class-browsertype#browser-type-launch) method.

I'm trying to have it output traces since that is an option of the .launch() method. But after the run, no traces are output. I'm not sure if this is a bug or if it is just unsupported. If it is unsupported, would be great to have support for traces/videos to output for debugging purposes (i'd rather not take a bunch of screenshots during the run). Would be beneficial in fargate as well so we can grab any and all worker logs including traces, videos, etc.

Lastly, great tool! Thanks for all the work you do to support it.

Version info:

```
2.0.0 although in my package.json i installed 2.0.9
```

Running this command:

```
npx artillery run MYYAMLFILE
```

I expected to see this happen:

Expected to see traces put into a traces folder after run.

Instead, this happened:

Nothing happened

Files being used:

```
  engines:
    playwright:
      aggregateByName: true
      launchOptions:
        headless: true
        tracesDir: ./traces
```

**Comment by bernardobridge** [comment]
Hey @bshostak 👋 . I believe `tracesDir` only allows you to specify the location of traces, but doesn't actually start a trace.

We have an early preview of tracing working with Artillery Cloud (we capture traces and then make it available in the UI) - if you'd be interested in trying it out, can you reach out to h@artillery.io ? We'd be happy to send you a trial!

**Comment by bshostak** [comment]
@bernardobridge Thank you! Yes, I will send an email over now.
