### ISSUE TITLE
iam:AttachRolePolicy on resource artilleryio-ecs-worker-role not authorized

### ISSUE THREAD

**Issue by manuelcarriernunesatsap** [artilleryio/artillery#2657]
Following the instructions on [Distributed Load Testing on AWS Fargate](https://www.artillery.io/docs/load-testing-at-scale/aws-fargate) doesn't work.

The following screenshot shows the problem:

![image](https://github.com/artilleryio/artillery/assets/148589233/77fc3a3e-50df-44a4-aa96-61734d43f50b)

[A branch in a github.com repo](https://github.com/manuelcarriernunesatsap/artillery/tree/run-fargate-error-01) contains files and instructions to facilitate reproducing the error.

# Version info
Artillery: 2.0.10, Node.js: v20.12.2, OS: win32

**Comment by bernardobridge** [comment]
Hi @manuelcarriernunesatsap 👋 

Thanks for setting up the reproduction repo.

Could you try changing the first two statements to this?

```json
{
            "Sid": "CreateOrGetECSRole",
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:GetRole",
                "iam:AttachRolePolicy"
            ],
            "Resource": "arn:aws:iam::123456789000:role/artilleryio-ecs-worker-role"
        },
        {
            "Sid": "CreateECSPolicy",
            "Effect": "Allow",
            "Action": [
                "iam:CreatePolicy",
            ],
            "Resource": "arn:aws:iam::123456789000:policy/artilleryio-ecs-worker-policy"
        },
```

So basically changing the `iam:AttachRolePolicy` from the second statement to the first one.

Let me know if that works, and if it does I'll update the docs!

**Comment by manuelcarriernunesatsap** [comment]
Thanks for the quick response, @bernardobridge

Applying the change to the AWS policy resolved the problem.
