### ISSUE TITLE
Missing actions in the AWS Fargate policy

### ISSUE THREAD

**Issue by landro** [artilleryio/artillery#2663]
To get the logging working, I had to add the following the policy listed at [https://www.artillery.io/docs/load-testing-at-scale/aws-fargate#iam-permissions](https://www.artillery.io/docs/load-testing-at-scale/aws-fargate#iam-permissions)

```
    {
      "Sid": "LogsPermissions",
      "Effect": "Allow",
      "Action": [
        "logs:PutRetentionPolicy",
 +       "logs:CreateLogStream",
 +       "logs:CreateLogGroup",
 +      "logs:PutLogEvents"
      ],
      "Resource": [
        "arn:aws:logs:*:123456789000:log-group:artilleryio-log-group/*"
      ]
    }
```

**Comment by hassy** [comment]
thank you @landro!

**Comment by landro** [comment]
It seems the artilleryio-ecs-worker-policy is not attached to the artilleryio-ecs-worker-role - I believe that is the underlying issue.
That would invalidate what I suggest above.

**Comment by bernardobridge** [comment]
> It seems the artilleryio-ecs-worker-policy is not attached to the artilleryio-ecs-worker-role - I believe that is the underlying issue.
That would invalidate what I suggest above.

Hi @landro . Indeed, the statements you mentioned in the original post shouldn't actually be needed in the role that triggers the test, only in the `artilleryio-ecs-worker-role` (via the `artilleryio-ecs-worker-policy`).

It's strange that it wasn't attached to the role. 
- Did you get any error from the CLI when running the test? 
- Was this working before, and then stopped working?
