### ISSUE TITLE
"Error: No target specified and no environment chosen" in AWS Fargate container

### ISSUE THREAD

**Issue by manuelcarriernunesatsap** [artilleryio/artillery#2671]
When [artillery-script-02.yml](../../../manuelcarriernunesatsap/artillery/tree/run-fargate-error-02/artillery-script-02.yml) is run via

```PowerShell
$Env:TARGET_URL = 'http://asciiart.artillery.io:8080'
artillery run-fargate 'artillery-script-02.yml' --region='eu-central-1' --count=1 --output='report.json'
```

`Error: No target specified and no environment chosen` is output to the logs generated by the AWS Fargate container. [The run-fargate-error-02 branch in the manuelcarriernunesatsap/artillery repo](../../../manuelcarriernunesatsap/artillery/tree/run-fargate-error-02) contains files and instructions to facilitate reproducing this.

# Version info

```
Artillery: 2.0.10
Node.js: v20.12.2
OS: win32
```

**Comment by bernardobridge** [comment]
Hey @manuelcarriernunesatsap 👋 ! 

Environment variables need to be propagated to Fargate containers using a `dotenv` file with the `--dotenv` flag. That's why it's erroring, since it would just resolve to undefined.

**Comment by manuelcarriernunesatsap** [comment]
Thanks for the quick 💨  response, @bernardobridge 😃 

Is that something that changed along the way? 💭

**Comment by bernardobridge** [comment]
Hi @manuelcarriernunesatsap ! I don't think so, no 🤔, not for Fargate. Did you have a different experience at one point?

**Comment by manuelcarriernunesatsap** [comment]
My possible experience would have occurred many months ago, which I can't remember. I asked to see if it was even possible that I have experienced such a thing.

Thanks, @bernardobridge .
