### ISSUE TITLE
phase name not showing if it is specified in default

### ISSUE THREAD

**Issue by TesterrA** [artilleryio/artillery#2679]
phase name is not showing if it is specified in default but it works fine if I set the environment variable

environments:
    low:
      phases:
        - duration: 60
          arrivalRate: 1
          rampTo: 5
          name: Warm up phase
        - duration: 60
          arrivalRate: 5
          rampTo: 10
          name: Ramp up load
        - duration: 30
          arrivalRate: 10
          rampTo: 30
          name: Spike phase
    high:
      phases:
      - duration: 60
        arrivalRate: 5
        rampTo: 10
        name: Warm up the API
      - pause: 60
      - duration: 60
        arrivalRate: 10
        rampTo: 50
        name: Ramp up to peak load
      - pause: 60
      - duration: 300
        arrivalRate: 50
        name: Sustained peak load
      - pause: 60
      - duration: 30m
        arrivalRate: 1
        rampTo: 100
        name: Gradual Ramp Up
      - pause: 60
      - duration: 3h
        arrivalRate: 100
        name: Sustained Maximum Load
    default:
      phases:
        - duration: 1
          arrivalCount: 1
          name: default phase

Version info: 2.0.10

Running this command: 
```
artillery run sample.yml
```

I expected to see this happen:

Phase started: default phase (index: 0, duration: 1s) 09:38:48(+0530)

Phase completed: default phase (index: 0, duration: 1s) 09:38:49(+0530)

Instead, this happened:

Phase started: unnamed (index: 0, duration: 1s) 09:38:48(+0530)

Phase completed: unnamed (index: 0, duration: 1s) 09:38:49(+0530)

**Comment by bernardobridge** [comment]
Just for future reference for anyone reading this:

`config.default.phases` doesn't exist in Artillery. If you want a default phase when you don't use an environment, you just need to have it under `config.phases`. If you don't specify one or an environment with a phase, Artillery will run a phase of duration 1s, arrivalRate 1.
