### ISSUE TITLE
Lambda uses Node v16 runtime

### ISSUE THREAD

**Issue by carrejoe3** [artilleryio/artillery#2707]
Node v16 is being used as a runtime when using the `artillery run-lambda` command: https://github.com/artilleryio/artillery/blob/02da55041d5053c8ff599956f69d5e4166971b45/packages/artillery/lib/platform/aws-lambda/index.js#L748

Node v16 has reached EOL which means many organisations can't use this tool unfortunately.

Version info: Latest.

**Comment by hassy** [comment]
thanks @carrejoe3! will be updated in the upcoming release of Artillery (due Monday next week)

**Comment by carrejoe3** [comment]
> thanks @carrejoe3! will be updated in the upcoming release of Artillery (due Monday next week)

Hey @hassy, do you know when this is likely to be patched please?

**Comment by hassy** [comment]
@carrejoe3 this is fixed in the most recent release of Artillery (v2.0.14)

Tests running on Lambda will now use Lambda Container Images instead of a Lambda-provided runtime.
