### ISSUE TITLE
Parallel execution and launchOption not working from .yml file

### ISSUE THREAD

**Issue by Brijendra9322** [artilleryio/artillery#2742]
I would like to handle the browser launch options and parallel execution both from .yml file. how to do that?
below is my .yml file but launchOptions and parallel is not working . i want to run with multiple user id with different browser sessions.
I see that Playwright.config.ts is not working in case of artillery. kindly help here.

config:
target: "https://www.google.com/"
playwright:
launchOptions:
headless: false
phases:
- duration: 1
arrivalRate: 1
name: "Phase 1"
processor: "./tests/test/xyz.ts"
engines:
playwright: {}
output:
json: "report/artillery_report_{{__timestamp | dateFormat 'YYYY-MM-DD'}}.json"
scenarios:

engine: playwright
testFunction: "demoTest"
parallel: 2

**Comment by bernardobridge** [comment]
Closing this as it's not an issue and has been answered here: https://github.com/artilleryio/artillery/discussions/2686#discussioncomment-9378946
