### ISSUE TITLE
File upload using Playwright engine net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by pjanakiraman24** [artilleryio/artillery#2761]
Hi Team,

I am trying to upload files using the below code. This works fine when i run it directly from playwright test runner but fails with a message net::ERR_FILE_NOT_FOUND when i run it through Artillery. 

    const fileChooserPromise = this.page.waitForEvent("filechooser");
    await this.BrowseButton.click();
    const fileChooser = await fileChooserPromise;
    await fileChooser.setFiles(fileName);

I am not sure what is causing this. There are 2 different places I am uploading files, in one of the application the same code works fine without any errors using Artillery. In the other app it is throwing this file not found error. How do I know if this is an Artillery issue or application issue. When i manually upload the file or upload it using playwright test runner it works fine. The files I upload are excel files. 

Playwright version 1.43.1 and Artillery version 2.0.12

**Comment by hassy** [comment]
I'm guessing 'fileName` is not an absolute path, and it's resolved differently by Playwright Test Runner and Artillery. What does the directory structure look like? Can you try running it with an absolute path?

**Comment by pjanakiraman24** [comment]
You are correct, it was a file path issue. I corrected the file path and it worked fine. Thanks!
