### ISSUE TITLE
Broken docs rendering

### ISSUE THREAD

**Issue by milosgajdos** [artilleryio/artillery#2790]
The docs rendering is broken at least in [https://www.artillery.io/docs/reference/extensions/publish-metrics/datadog](https://www.artillery.io/docs/reference/extensions/publish-metrics/datadog)

See the screenshots below:

![Screenshot 2024-05-28 at 10 22 37](https://uploads.linear.app/6bc804d5-8e50-40e0-b9b5-8dcdaf9ff6df/a35007d5-732d-4c94-a006-d3cb68faac47/5a8036c3-fc9f-452d-bc26-665f140501c9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZiYzgwNGQ1LThlNTAtNDBlMC1iOWI1LThkY2RhZjlmZjZkZi9hMzUwMDdkNS03MzJkLTRjOTQtYTAwNi1kM2NiNjhmYWFjNDcvNWE4MDM2YzMtZmM5Zi00NTJkLWJjMjYtNjY1ZjE0MDUwMWM5IiwiaWF0IjoxNzE2ODg4NjIxLCJleHAiOjMzMjg3NDQ4NjIxfQ.mVO6yF79Q7sVDrtBMv-7rr7INbbqopjufqN7TDRiwYM "=943x")

![Screenshot 2024-05-28 at 10 22 48](https://uploads.linear.app/6bc804d5-8e50-40e0-b9b5-8dcdaf9ff6df/67f3fc09-cfbf-4d31-9357-cbe8279cd18d/554caac9-664e-4696-8299-80fc29c96c51?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZiYzgwNGQ1LThlNTAtNDBlMC1iOWI1LThkY2RhZjlmZjZkZi82N2YzZmMwOS1jZmJmLTRkMzEtOTM1Ny1jYmU4Mjc5Y2QxOGQvNTU0Y2FhYzktNjY0ZS00Njk2LTgyOTktODBmYzI5Yzk2YzUxIiwiaWF0IjoxNzE2ODg4NjIxLCJleHAiOjMzMjg3NDQ4NjIxfQ.2h3CjL84j3lxbYiv2tvqmV2fMBXgovUWEi9lp6viiHg "=853x")

**Comment by manfromanotherland** [comment]
It was a badly formatted markdown table, we have just fixed the issue there.

Thanks for letting us know, @milosgajdos.

**Comment by milosgajdos** [comment]
Some of it was fixed but this is still broken 🤷‍♂️ 

<img width="889" alt="Screenshot 2024-05-28 at 12 05 34" src="https://github.com/artilleryio/artillery/assets/1392526/c9a25bbc-2c36-4d28-b85b-82afaeb41b85">

**Comment by manfromanotherland** [comment]
Ah missed that one 🤦, sorted now. Thanks again!
