### ISSUE TITLE
Sending metrics via Pushgateway with basic auth

### ISSUE THREAD

**Issue by Anonycoders** [artilleryio/artillery#3194]
Hello,
I'm trying to use the Prometheus integration for Artillery and there is an issue where the Pushgateway comes with a basic auth and since the Prometheus config does not support the basic auth, we are not able to send the metrics.

Is there any possibility to add support for this case or there is already something in the documents that I have missed?

Many thanks in advance 🙇

**Comment by bernardobridge** [comment]
Hey @Anonycoders 👋 

We don't have first-class support for that, but I believe you should be able to set the basic auth as part of the url you set in the `pushgateway` config option (https://www.artillery.io/docs/reference/extensions/publish-metrics/prometheus#example). Basically something like: `http://USERNAME:PASSWORD@URL`

**Comment by Anonycoders** [comment]
Hey @bernardobridge 👋🏼 
Thank you for the quick response. Actually the first attempt was done like the way you said but was not successful.
Turned out to be a typo not the process itself. 🤦🏼 
I'll close this issue as it's not the case anymore. thank you.
