### ISSUE TITLE
Lambda script creates a random role with no permissions

### ISSUE THREAD

**Issue by jaxoncreed** [artilleryio/artillery#3199]
Version info:

```
Artillery: 2.0.7
Node.js:   v16.20.2
OS:        darwin
```

Running this command:

```
artillery run-lambda --region us-east-1 --memory-size 3000 test.yml
```

I expected to see this happen:

The script runs properly on Lambda

Instead, this happened:

I'm trying to set up artilleryio on AWS lambda and following the instructions yields similar results as this post: [https://t.co/90sfosbFCJ](https://t.co/90sfosbFCJ)

When I run the "run-lambda" command it hangs. In Cloud Watch, I get the following error:

![image](https://uploads.linear.app/6bc804d5-8e50-40e0-b9b5-8dcdaf9ff6df/b84eee35-daf1-475d-b2ed-65aba5c4367e/890f688b-1ce6-4ff0-ae00-27e31b024d47?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZiYzgwNGQ1LThlNTAtNDBlMC1iOWI1LThkY2RhZjlmZjZkZi9iODRlZWUzNS1kYWYxLTQ3NWQtYjJlZC02NWFiYTVjNDM2N2UvODkwZjY4OGItMWNlNi00ZmYwLWFlMDAtMjdlMzFiMDI0ZDQ3IiwiaWF0IjoxNzE4MzY5MjQ5LCJleHAiOjMzMjg4OTI5MjQ5fQ.XiH5c593gCu-xRw6a9NJNYO4BF2iBIb8ZLnUOjZB3ME)

If I'm interpreting this correctly, I think it means that my AWS CLI (which is logged in with admin credentials) has successfully connected with AWS, but for some reason, it creates a new role called artilleryio-default-lambda-role-20230116.

This randomly gated role doesn't have the proper permissions to set up SQS:

![image](https://uploads.linear.app/6bc804d5-8e50-40e0-b9b5-8dcdaf9ff6df/bf99940e-6187-43fa-abb1-4f91d7e638d4/91b0a4cb-00c9-4862-8f62-9e2159a0e6c6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZiYzgwNGQ1LThlNTAtNDBlMC1iOWI1LThkY2RhZjlmZjZkZi9iZjk5OTQwZS02MTg3LTQzZmEtYWJiMS00ZjkxZDdlNjM4ZDQvOTFiMGE0Y2ItMDBjOS00ODYyLThmNjItOWUyMTU5YTBlNmM2IiwiaWF0IjoxNzE4MzY5MjQ5LCJleHAiOjMzMjg4OTI5MjQ5fQ.dYmj2wV5qyS8zvpV3J-maSBEe41zK4vkCltWuyreF2g)

The user I'm logged into on the AWS CLI (cli-user) has admin permissions

![Screenshot 2024-06-14 at 1 42 26 PM](https://uploads.linear.app/6bc804d5-8e50-40e0-b9b5-8dcdaf9ff6df/26e9f3ad-6ae6-4171-a654-4fad24367ae2/141c0ca6-816d-4771-92e0-d5007f3c4870?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZiYzgwNGQ1LThlNTAtNDBlMC1iOWI1LThkY2RhZjlmZjZkZi8yNmU5ZjNhZC02YWU2LTQxNzEtYTY1NC00ZmFkMjQzNjdhZTIvMTQxYzBjYTYtODE2ZC00NzcxLTkyZTAtZDUwMDdmM2M0ODcwIiwiaWF0IjoxNzE4MzY5MjQ5LCJleHAiOjMzMjg4OTI5MjQ5fQ.9LedHM6Liblf-KWUZmjCI1907JfoXDuKY6UUb2toueg "=1125x")

![Screenshot 2024-06-14 at 1 44 29 PM](https://uploads.linear.app/6bc804d5-8e50-40e0-b9b5-8dcdaf9ff6df/5d032dd2-d210-4f3d-8bae-ddcc1428e3f7/bb0101ae-c32d-494a-9b0a-b4e249769ddd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZiYzgwNGQ1LThlNTAtNDBlMC1iOWI1LThkY2RhZjlmZjZkZi81ZDAzMmRkMi1kMjEwLTRmM2QtOGJhZS1kZGNjMTQyOGUzZjcvYmIwMTAxYWUtYzMyZC00OTRhLTliMGEtYjRlMjQ5NzY5ZGRkIiwiaWF0IjoxNzE4MzY5MjQ5LCJleHAiOjMzMjg4OTI5MjQ5fQ.uTzBcyeuDva6W-ZMR_2zKXXRjaF9LFEtBzxIgc4GF2s "=453x")

Do you know why this random role is created?

Files being used:

```
<relevant yaml/js/csv go here>
```

**Comment by hassy** [comment]
The role is not random, it's the role that AWS Lambda functions running the test will assume. You can see the full definition of what's created here: [https://github.com/artilleryio/artillery/blob/main/packages/artillery/lib/platform/aws-lambda/index.js#L489](https://github.com/artilleryio/artillery/blob/main/packages/artillery/lib/platform/aws-lambda/index.js#L489)

Artillery should've created a policy attached to that role which allows SQS access: [https://github.com/artilleryio/artillery/blob/main/packages/artillery/lib/platform/aws-lambda/index.js#L540](https://github.com/artilleryio/artillery/blob/main/packages/artillery/lib/platform/aws-lambda/index.js#L540)

Can you confirm if it's there?

**Comment by jaxoncreed** [comment]
Ah I figured out the problem. Yes, it happened repeatedly. My problem was that I had already created a role named "artilleryio-default-lambda-role" Deleting that role seemingly fixed the problem.
