### ISSUE TITLE
Handle processors larger than 256mb on AWS lambda

### ISSUE THREAD

**Issue by jaxoncreed** [artilleryio/artillery#3200]
Version info:

```
Artillery: 2.0.15
Node.js:   v16.20.2
OS:        darwin
```

Running this command:

```
artillery run-lambda --region us-east-1 --memory-size 3000 test.yml
```

I expected to see this happen:

The test runs.

Instead, this happened:

I have a 1.5mb processor file (it's that size because we're doing some cryptography to simulate a function that happens on our app). When I run the test on my local machine, everything goes well, but when deploying the lambda, I get the following message:

```
{
  err: {
    message: 'One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes.',
    stack: 'InvalidParameterValueException: One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes.\n' +
      '    at Request.extractError (/artillery/node_modules/aws-sdk/lib/protocol/json.js:80:27)\n' +
      '    at Request.callListeners (/artillery/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n' +
      '    at Request.emit (/artillery/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n' +
      '    at Request.emit (/artillery/node_modules/aws-sdk/lib/request.js:686:14)\n' +
      '    at Request.transition (/artillery/node_modules/aws-sdk/lib/request.js:22:10)\n' +
      '    at AcceptorStateMachine.runTo (/artillery/node_modules/aws-sdk/lib/state_machine.js:14:12)\n' +
      '    at /artillery/node_modules/aws-sdk/lib/state_machine.js:26:10\n' +
      '    at Request.<anonymous> (/artillery/node_modules/aws-sdk/lib/request.js:38:9)\n' +
      '    at Request.<anonymous> (/artillery/node_modules/aws-sdk/lib/request.js:688:12)\n' +
      '    at Request.callListeners (/artillery/node_modules/aws-sdk/lib/sequential_executor.js:116:18)'
  }
}
```

It looks like the limit of SQS is 256mb. Am I right to assume that the processor is being delivered through SQS? Is there another way to deliver the bundle?

Thanks!
Files being used:

```
<relevant yaml/js/csv go here>
```

**Comment by bernardobridge** [comment]
Hi @jaxoncreed 👋 

That's peculiar, the processor isn't being sent through SQS, no. A couple of questions:
- Can you share what the `run-lambda` command initial output was? It should have had something saying `Test bundle contents:` detailing which files were being bundled. 
- Any chance you could show your processor file and contents of your YAML? I'd like to try to replicate it.

**Comment by bernardobridge** [comment]
Thanks for the details @jaxoncreed ! 

>Sure thing! I created a temp branch for the entire project here:
I don't think the project is public, I don't seem to have access to it.

---

One question - in the `package.json` that's being used, do you have `artillery` installed there? It is possible that that is the reason you're running out of space in the Lambda container. Ideally, have a separate package.json (in e.g. a folder just for the tests) with only the dependencies the tests themselves need, not `artillery`. 

---

>It would seem that your theory was correct. An error was thrown somewhere in the bundle (the test works locally but there might be something about the AWS environment that causes a problem), then because the bundle is all one line, it will include the entire line in the error message pointing out that error.

Yes, it's possible we need to handle a couple of things better here. Once you give me access to your repo, I can try to replicate it!

**Comment by jaxoncreed** [comment]
oops sorry about that. Use these links:

 - Repo: https://github.com/jaxoncreed/dcc-test-server
 - YML: https://github.com/jaxoncreed/dcc-test-server/blob/test-upload/test.yml
 - Bundle: https://github.com/jaxoncreed/dcc-test-server/blob/test-upload/bundle/bundle.js
 - Raw Code: https://github.com/jaxoncreed/dcc-test-server/blob/test-upload/src/customFunctions.ts

**Comment by bernardobridge** [comment]
Hey @jaxoncreed 👋 

I usually try to run things locally first (before moving to Lambda), and I mistakenly ran the test without providing the `npm_config_emailed_url` environment variable. Sure enough, it errored [where expected](https://github.com/jaxoncreed/dcc-test-server/blob/test-upload/src/customFunctions.ts#L14). However, I did notice that it errored with a very similar thing to the logs you showed above (shows the whole bundle, and then only after do we see the actual issue). 

Could it be that you aren't passing that `npm_config_emailed_url` to the Lambda? Have you tried using the `--dotenv` flag with a `.env` file to do it, perhaps?

**Comment by jaxoncreed** [comment]
Thanks for your help. Using the --dotenv flag worked!
