### ISSUE TITLE
Artillery API test for 1VU showing incorrect value for 'median' under 'http.response_time'

### ISSUE THREAD

**Issue by akshatrastogi01** [artilleryio/artillery#3223]
Version info: 
```
2.0.7
```

Running this command: 
```
artillery run-fargate
```

I expected to see this happen:

Artillery API test for 1VU showing incorrect value for 'median' under 'http.response_time'.
Detailed report is attached.
The test was done for 1VU on Fargate.

Attributes for 'http.response_time' (ms) are:

min - 122
max - 122
median - 122.7
p95 - 122.7
p99 - 122.7
In noway the median should come out to be - 122.7

Instead, this happened:

median - 122.7

Files being used:
```
[report.html.zip](https://github.com/user-attachments/files/15937019/report.html.zip)

```

**Comment by hassy** [comment]
answered here: https://github.com/artilleryio/artillery/discussions/3222 please don't open duplicate issues
