### ISSUE TITLE
Bug:  Payloads with `loadAll` and field names include unexpected objects

### ISSUE THREAD

**Issue by Rio517** [artilleryio/artillery#3268]
Hello!

When using `loadAll` with field names, `vuContext.vars` includes the expected array of objects and each field name loading with an object from the CSV rows.

Version info:
```
Artillery: 2.0.17
Node.js:   v20.15.0
OS:        linux
Playwright Version 1.45.1
```

Running this command:
```
npx artillery run my-test.yml
```

## Expected to see this happen:

In `vuContext.vars`
```js
{
  payloadName: [
    { field1: '01', field2: '01' },
    { field1: '02', field2: '02' },
    { field1: '03', field2: '03' },
    ...
  ]
}
```
## Instead, this happened:

In `vuContext.vars`

```js
{
  field1: { field1: '01', field2: '01' },
  field2: { field1: '02', field2: '02' },
  payloadName: [
    { field1: '01', field2: '01' },
    { field1: '02', field2: '02' },
    { field1: '03', field2: '03' },
    ...
  ]
} 
```

**Note:** This becomes super problematic when using multiple identical field names from different payloads. I had two payloads, one normal payload and one with `loadAll`. Both payloads had an `account_id`.  In theory, only the non-`loadAll` payload's `account_id` should have been at the root of `vuContext.vars`. However, the unintended `account_id` from the `loadAll` payload would overright the first value - leading to confusion.

Theoretically, one could reorder the payloads, but I wasn't sure how deterministic that was. I just renamed the keys once I figured out what was going on. 

### Simplified configuration

````yaml
config:
  engines:
    playwright: {}
  payload:
    path: 'path/contacts.csv'
    fields:
      - 'first_name'
      - 'last_name'
    loadAll: true
    name: 'uploadContacts'
scenarios:
- engine: playwright
  name: 'ContactUpload'
  testFunction: 'contactUploadTest'
````

### console.log(vuContext.vars);
````js
{
  first_name: {
    first_name: 'load_first_01',
    last_name: 'load_last_01',
  },
  last_name: {
    first_name: 'load_first_02',
    last_name: 'load_last_02',
  }
  uploadContacts: [
    {
      first_name: 'load_first_01',
      last_name: 'load_last_01',
    },
    {
      first_name: 'load_first_02',
      last_name: 'load_last_02',
    },
    {
      first_name: 'load_first_03',
      last_name: 'load_last_03',
    },
    {
      first_name: 'load_first_04',
      last_name: 'load_last_04',
    },
    {
      first_name: 'load_first_05',
      last_name: 'load_last_05',
    },
   ...
  ],
  '$uuid': '74017401-7401-7401-7401-74017401b660'
}
````

### CSV - contacts.csv
```csv
load_first_01,load_last_01,
load_first_02,load_last_02,
load_first_03,load_last_03,
load_first_04,load_last_04,
load_first_05,load_last_05,
load_first_06,load_last_06,
load_first_07,load_last_07,
load_first_08,load_last_08,
load_first_09,load_last_09,
load_first_10,load_last_10,
load_first_11,load_last_11,
load_first_12,load_last_12,
load_first_13,load_last_13,
load_first_14,load_last_14,
load_first_15,load_last_15,
load_first_16,load_last_16,
```
### testFunction
```js
async function contactUploadTest(page, vuContext, events) {
  console.log(vuContext.vars);
}
module.exports = { contactUploadTest };
```

**Comment by bernardobridge** [comment]
Hi @Rio517 . There does seem to be a bug there when using `loadAll` with field names. We'll take a look at this as soon as possible.

In the meantime as a workaround, are you perhaps able to not set field names?

**Comment by bernardobridge** [comment]
Fix for this is now released in https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.19 . Thanks for the report!

**Comment by Rio517** [comment]
Thanks so much!
