### ISSUE TITLE
ERROR: error on running npx artillery  

### ISSUE THREAD

**Issue by gelsogrove** [artilleryio/artillery#3382]
Hello 

Could you please take a look to this error that appears suddenly running npx artillery ?

**npx artillery** 
/Users/gelso/workspace/project-name/node_modules/widest-line/node_modules/string-width/index.js:3
**const isFullwidthCodePoint = require('is-fullwidth-code-point');**
                             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/gelso/workspace/project-name/node_modules/is-fullwidth-code-point/index.js from /Users/gelso/workspace/project-nam/node_modules/widest-line/node_modules/string-width/index.js not supported.
 
 Node version : **v20.17.0**
 "artillery": "**^2.0.20",**
 
Thanks in advance

**Comment by hassy** [comment]
Unable to reproduce here with Node v20.17.0

**Comment by gelsogrove** [comment]
it's weird can you try to remove the **node_module** folder we have this error in more than one enviroment

**Comment by gelsogrove** [comment]
yes it works fine wit the latest version thanks!
