### ISSUE TITLE
Dynatrace publish-metrics page says datadog

### ISSUE THREAD

**Issue by agardnerIT** [artilleryio/artillery#3397]
I believe this page should say `dynatrace` instead of `datadog`

https://www.artillery.io/docs/reference/extensions/publish-metrics/dynatrace

![image](https://github.com/user-attachments/assets/b88700ee-5ce9-468a-8b46-ffbaf2efe136)

**Comment by manfromanotherland** [comment]
[Fixed](https://www.artillery.io/docs/reference/extensions/publish-metrics/dynatrace), thanks @agardnerIT!
