### ISSUE TITLE
Issue: Incorrect Documentation Link - WebSocket Guide

### ISSUE THREAD

**Issue by kkssbbb** [artilleryio/artillery#3425]
### Description
Hello Artillery Team,

I discovered an incorrect link in the documentation while reviewing the WebSocket guide. This link currently leads to a 404 error page, and I would like to help correct it.

### Current Behavior
In the "Scenarios Section" of the test script reference, there is a broken link for the WebSocket guide:
- **Location of Incorrect Link:** [Scenarios Section](https://www.artillery.io/docs/reference/test-script#scenarios-section)
- **Incorrect URL:** https://www.artillery.io/docs/docs/guides/guides/websocket
### Screenshots
![image](https://github.com/user-attachments/assets/f7dfb2c5-daeb-4f24-a91f-6d164eacf530)
Here is the relevant excerpt from the documentation:

> Each Artillery engine used during testing supports additional scenario attributes. Read the documentation to learn what you can do in a scenario for each Artillery engine:
> 
> - Testing HTTP
> - Testing with Playwright
> - Testing Socket.IO
> - Testing WebSockets

### Expected Behavior
The link should direct users to the correct WebSocket documentation:
- **Correct URL:** https://www.artillery.io/docs/reference/engines/websocket

### Impact
- Users may experience confusion when trying to access the WebSocket guide.
- It may hinder the learning process for new users.

### Proposed Solution
I propose the following steps to resolve this issue:
1. Locate the source of the incorrect link in the documentation.
2. Update the link to the correct URL.
3. Review other sections for similar issues to ensure overall documentation quality.

### Additional Context
This is my first contribution to the world of open-source development, and I am thrilled to start with Artillery. I look forward to learning and contributing to this project, and I appreciate any guidance you can provide.

---
Thank you for considering my contribution. I look forward to helping improve Artillery's documentation! 🚀

**Comment by hassy** [comment]
thanks @kkssbbb! the source for the docs is not open, we'll fix the incorrect URL shortly

**Comment by kkssbbb** [comment]
Hi @hassy, ​​I appreciate the hard work the Artillery team puts into maintaining the documentation. As a loyal Artillery user, how about making the documentation open source so that more people can contribute and improve the quality of Artillery's documentation?

**Comment by hassy** [comment]
We don't have plans to open source the documentation at this time @kkssbbb. Thanks for reporting the issue, it's fixed now.
