### ISSUE TITLE
Currently getting loads of issues with metric Fargate Warning: multiple batches of metrics for period

### ISSUE THREAD

**Issue by rbtaina** [artilleryio/artillery#3429]
### Discussed in https://github.com/artilleryio/artillery/discussions/3426

<div type='discussions-op-text'>

<sup>Originally posted by **rbtaina** December 10, 2024</sup>
- Error: error sending test data to Artillery Cloud
Test report may be incomplete
Warning: multiple batches of metrics for period 1733832590000

This only started when i add   includeFiles: to my yml file and the worst thing the test wont stop, it will carry on running, my tests which was supposed to be 10minutes ended up running for 30 minutes and only stopped because i closed VS.

Any recommendations?
Thanks Robert</div>

**Comment by hassy** [comment]
going to close this as there's a Discussion already
