### ISSUE TITLE
scenario.weight cannot be set to 0

### ISSUE THREAD

**Issue by eranegozy** [artilleryio/artillery#350]
I'd like to have the option of setting the weight of a scenario to 0.
However, I believe that doing so now causes the system to think there is no weight and it gets set to 1 as the default value.

This is the code in artillery-core/lib/runner.js:
```
  if (!runState.compiledScenarios) {
    _.each(script.scenarios, function(scenario) {
      if (!scenario.weight) {
        scenario.weight = 1;
      }
    });

```

**Comment by hassy** [comment]
Thanks @eranegoz
