### ISSUE TITLE
Improve graphical reports

### ISSUE THREAD

**Issue by hassy** [artilleryio/artillery#51]
Current output of `artillery report` is quite useful, but there are many ways in which the reports can be improved further to help analyse performance of the systems under test.

Specifically, with this change in `core` it's now possible to show fine-grained request latencies: https://github.com/shoreditch-ops/artillery-core/commit/fe9e0b62a0d8e3374ceaf9179c353fd41e20203c

There are other enhancements that can be made for ~~`v1.4`~~ `2.0` - this is the thread to collect them all.

**Comment by DannyCork** [comment]
current is 1.4.1. 
Wondering if these changes were merged ?

**Comment by hassy** [comment]
Not yet, still a work in progress.

**Comment by dshook** [comment]
Having a histogram of response times would be very useful IMO.  Something that shows how many requests fell into the 0-20 ms range, 21-40 range, etc..

**Comment by aguformoso** [comment]
What about a simple plot of _successful RPS_ (HTTP 200) vs. _attempted RPS_? I post-process the files with some python scripts and end up analyzing this (rather than time series):
![Successful vs. attempted RPS](https://cloud.githubusercontent.com/assets/1735250/21421180/2dc9da20-c83a-11e6-98e2-37e0d5b4b24d.png)

**Comment by hassy** [comment]
What's attempted as opposed to successful RPS @aguformoso?

**Comment by aguformoso** [comment]
Attempted includes every single HTTP request the client sends to the 
service. Successful includes those HTTP responses the service is able to 
deliver with a 200 code.
I think it would be a nice way to see the stress limits of your 
application!

**Comment by steveschnepp** [comment]
Note that 302 might also be a Successful request for some scenarios.

**Comment by straub** [comment]
@hassy Just a heads-up, that merge seems unrelated, this may have been closed accidentally?
