### ISSUE TITLE
Invalid URL or request options will fail silently and hang request

### ISSUE THREAD

**Issue by Limess** [artilleryio/artillery#512]
My colleague had issues where they were adding headers to a CSV file, which led to the request URL being populated as `url` (the string). This led to [request](https://github.com/request/request) returning an error. 

Normally, this would have been handled as expected by Artillery, but in this event, `request` doesn't emit an `error` event, instead it only calls the provided callback function, see the below for a discussion on adding documentation for this:

https://github.com/request/request/issues/1779

This means that either the error is completely unhandled (if `maybeCallback` is `undefined`), or caught but then ignored: https://github.com/shoreditch-ops/artillery/blob/fb681c16d7c799e1788d2eba1f84bd0f90525294/core/lib/engine_http.js#L304-L307.

The solution is to always have a callback function on this line: https://github.com/shoreditch-ops/artillery/blob/fb681c16d7c799e1788d2eba1f84bd0f90525294/core/lib/engine_http.js#L437 and to handle any errors here, rather than in the stream (or alternatively check if the callback has been called in the stream and handle errors there as well).

**Comment by hassy** [comment]
Great bug report, thanks @Limess!
