### ISSUE TITLE
InvalidParameterException: Task count can not be greater than 10 (Artillery Pro)

### ISSUE THREAD

**Issue by sparkida** [artilleryio/artillery#595]
We have a license for "Medium" in Artillery Pro and it promises 20 load generators, but when exceeding 10 this error occurs.

```
artillery run-cluster ... --fargate --count 20 ...
```

**Comment by hassy** [comment]
Apologies for that @sparkida, that was an issue on our side, the just-released v1.3.2 update contains a fix for that issue. Please give that a go and let us know if you're still seeing any issues.

**Comment by sparkida** [comment]
Just launched 20 :)

Thank you again
