### ISSUE TITLE
ECS task runs indefinitely with rampTo on Node v7 with no solution to change version (Artillery Pro)

### ISSUE THREAD

**Issue by sparkida** [artilleryio/artillery#596]
```
You are running Node.js v7.10.1 which is affected by a bug that can cause
Artillery to hang indefinitely when a rampTo arrival phase is used.
Use Node.js v6.8.0 or lower to avoid the issue.
```

The cloudwatch logs are saying to use Node.js v6 or lower, but there doesn't seem to be a way to adjust this in the tests. Please advise

**Comment by hassy** [comment]
@sparkida the new v1.3.2 release of Artillery Pro makes use Node.js 10 (LTS) which should remove this warning.

**Comment by sparkida** [comment]
She's working! Thank you @hassy
