### ISSUE TITLE
Artillery Support for SocketCluster

### ISSUE THREAD

**Issue by pvangeepuram** [artilleryio/artillery#600]
We are intending to use Artillery for testing our systems, and wanted to suggest adding support for testing SocketCluster backends.

**Comment by semiaddict** [comment]
Hello @pvangeepuram,
Did you ever manage to create a SocketCluster engine ?
I am also very much interested in this, and will likely create one if none is already available.

**Comment by semiaddict** [comment]
FYI, I started working on an engine for SocketCluster: https://github.com/philharmoniedeparis/artillery-engine-socketcluster
