### ISSUE TITLE
Regression in CSV parsing because of csv-parse upgrade.

### ISSUE THREAD

**Issue by rajeshja** [artilleryio/artillery#622]
A new version of `csv-parse`, i.e. `4.3.0` was released on Dec 31, 2018. This version has some validation refinements including one for the `from_line` option. artillery passes the `from_line` option as either 1 or 0 depending on whether headers should be skipped or not. This should be changed to use 2 or 1 instead.

Affected line in `artillery/lib/commands/run.js`:

    from_line: typeof payloadSpec.skipHeader === true ? 1 : 0,

This should be changed to:

    from_line: typeof payloadSpec.skipHeader === true ? 2 : 1,

Alternatively, package.json should be changed to use 

    "csv-parse": "4.2.0",

**Comment by rajeshja** [comment]
Thanks. When can I expect the latest code on npmjs.com?

**Comment by rajeshja** [comment]
Thanks. When can I expect the latest code on npmjs?

**Comment by tcco** [comment]
ping!

**Comment by ianseyer** [comment]
This is also effecting me

**Comment by rajeshja** [comment]
Note that the bug has been fixed, but the latest build has not been published to npmjs yet.

**Comment by MLG-ANolan** [comment]
Any timeframe on when the latest with this fix will be released?

**Comment by rajeshja** [comment]
I only raised the pull request to fix the bug. I'm not part of the team that owns artillery, so will look to @hassy to answer that question.

**Comment by fgauna12** [comment]
Hello, any updates when this will be released?
