### ISSUE TITLE
Not able to use overrides with artillery pro

### ISSUE THREAD

**Issue by himasimplisafe** [artilleryio/artillery#638]
Not able to use --overrides for https://artillery.io/docs/pro/run-cluster/. We are getting error with phases with json format and we saw this error `File not found: {phases:` in AWS docker container/instance logs.

Our example here:
--overrides '{"config": {"phases": [{"duration": 10, "arrivalRate": 1}]}}'

We saw --overrides flag is still in experiment state?

**Comment by himasimplisafe** [comment]
If I pass file to overrides with json like below 
`{
    "config": {
       "phases": [
          {
             "duration": 10,
             "arrivalRate": 1
          }
       ]
    }
 }`

**Comment by himasimplisafe** [comment]
<img width="731" alt="screen shot 2019-01-29 at 4 14 58 pm" src="https://user-images.githubusercontent.com/24592500/51940889-34aede80-23e1-11e9-84e7-d15a277ad24c.png">

**Comment by hassy** [comment]
Can you share the error you're seeing in the logs @himasimplisafe? (feel free to email h@artillery.io as well rather than posting here).

**Comment by vidhya0406** [comment]
Is there a workaround or a suggested way to use `overrides`?

**Comment by hassy** [comment]
`--overrides` is fully supported in Artillery Pro (with `run-cluster`).

@vidhya0406 If you're having issues, could you please create a new issue with a command that reproduces the issue you're seeing. I'll close this old issue since there's nothing specific here to follow up on.
