### ISSUE TITLE
Question: flow with one endpoint being http and another being https

### ISSUE THREAD

**Issue by tateexon** [artilleryio/artillery#647]
Hello,
I am currently trying to create a flow that hits two endpoints, one is http and the other is https. Is this possible with this tool? My main load test use case at the moment has this dependency.

Things I have tried so far:
* Empty target and just pass in the full url in the url fields
* Target containing "http" and in the url fields adding "://www.blarg.com/a" and "s://www.blarg.com/b", inspired by: https://github.com/artilleryio/artillery/issues/303

Neither seemed to work due to the url being unhappy with the formatting. It is fully possible I messed up on the things I tried so far so if one of those should work I will gladly go back and hammer on it some more.
Thanks for any help in advance!

**Comment by msarzijr** [comment]
Use:

config:
  target: "http:/"
...
scenarios:
...
        url: "/www.yourFirstTarget.com/"
...
        url: "/www.yourSecondTarget.com/"
