### ISSUE TITLE
Date variable

### ISSUE THREAD

**Issue by Tagliatti** [artilleryio/artillery#661]
Hello, how can I get the `date` in the script file? It does not have to be inline, it can be passed by the CLI.
Example in bash:
``` bash
date -d "+31 days" +%Y-%m-%d
```

**Comment by hassy** [comment]
You could set the value in an environment variable and then read it with `$processEnvironment` in the Artillery script - https://artillery.io/docs/script-reference/#using-dynamic-values-in-config

**Comment by hassy** [comment]
closing but feel free to re-open if that doesn't solve your issue
