### ISSUE TITLE
Incorrect Json request body on a Post request - Nested arrays are converted to flat arrays

### ISSUE THREAD

**Issue by siddarthareddyt** [artilleryio/artillery#666]
Hi,

I am trying to post a JSON as a request payload to a Post service endpoint. Setting up the request body through a `beforeRequest` method's `requestParams.json ` property as:

    function setJSONBody(requestParams, context, ee, next) { 
         var body = {
           size: 10,
           query: a huge JSON
         };
        requestParams.json = body;
       return next();
    }

However, the payload JSON is not what is expected - all the nested arrays are converted to flat arrays. For ex: `[[1,2], [3,4]]` is converted to  `[1,2,3,4]`.

I have tried using `JSON.parse(payload)` and `JSON.parse(JSON.stringify(payload))` but got an error: `SyntaxError: Unexpected token o in JSON at position 1
   at JSON.parse (<anonymous>)`

Is this a known issue or am I missing something here?

**Comment by hassy** [comment]
That should not be happening. Can you `console.log(body)` to confirm that the value is not already flattened arrays?

Which version of Artillery is that? (`artillery -V`)

**Comment by siddarthareddyt** [comment]
I did `console.log(body)`, and it is as expected, a correct json. 

I am using artillery 1.6.0-27.

**Comment by siddarthareddyt** [comment]
any update on this one?

**Comment by hassy** [comment]
The fix is in and will be available in the next release of Artillery. Thanks for the bug report @siddarthareddyt!

**Comment by siddarthareddyt** [comment]
@hassy  Thanks for the efforts to fix this. 
The fix seems to solve the problem partly but parsing a **complex json (e.g. of size 58KB) takes more than a minute.**

I said this solves partly because it fails for jsons with `null` values:
`TypeError: Cannot read property 'constructor' of null
    at template (artillery_l/core/lib/engine_util.js:197:9)
    at Object.deepForEach (artillery_l/core/lib/engine_util.js:202:25)
    at forEachObject (artillery_l/node_modules/deep-for-each/lib/index.js:16:8)
    at forEach (artillery_l/node_modules/deep-for-each/lib/index.js:36:5)
    at template (artillery_l/core/lib/engine_util.js:199:5)
    at Array.deepForEach (artillery_l/core/lib/engine_util.js:202:25)
    at array.forEach (artillery_l/node_modules/deep-for-each/lib/index.js:24:8)
    at Array.forEach (<anonymous>)
    at forEachArray (artillery_l/node_modules/deep-for-each/lib/index.js:22:9)
    at forEach (artillery_l/node_modules/deep-for-each/lib/index.js:34:5)`

Any idea that might be causing this?

**Comment by hassy** [comment]
Are you able to provide more information about the JSON object @siddarthareddyt? e.g. is there a lot of nesting? are a lot of values objects/arrays or mostly primitive values? I've run some one-off tests on fairly large JSON objects (500kb+ when serialised), but we definitely need to ahh an automated performance test for the `template()` function.

The `null` issue is an easy fix, thanks again for the report!

**Comment by hassy** [comment]
Fixed in https://github.com/artilleryio/artillery/pull/688
