### ISSUE TITLE
I have to use xml request as body for post request in artillery .please give me a sample  

### ISSUE THREAD

**Issue by Sreedevi-91v** [artilleryio/artillery#676]

**Comment by RameshPrabakar** [comment]
I have tried like this it's worked for me. And also

config:
  target: 'https://artillery.io'
  phases:
    - duration: 60
      arrivalRate: 20
  defaults:
    headers:
      x-my-service-auth: '987401838271002188298567'
scenarios:
  - flow:
    - post:
           headers:
               Content-Type: "application/xml"
           url: "/api"
           body: '<?xml version="1.0">
                        <sample> 
                        <header> ...  </header> 
                         <body> ...  </body> 
                        </sample>'

**Comment by hassy** [comment]
Yep, what @RameshPrabakar said. You can set `body` to any data, just set `content-type` accordingly and it should work.
