### ISSUE TITLE
Support for streaming/download API?

### ISSUE THREAD

**Issue by henock1** [artilleryio/artillery#707]
Hello,

I'm working on a project that is a download server/API. This application zips files and pipes the archive back to the user in the response as new data chunks arrive from our data store. I have tried fiddling with the event emitter that we get with Artillery, but I can't seem to figure out if waiting for the file response stream to close/complete before moving to the next scenario is  possible with this tool? If so, can someone point me in the right direction? If not, this is a massive feature gap for my use case and I would recommend adding it. Thanks!

- HG

**Comment by hassy** [comment]
Artillery will wait for the entire response to complete before moving on to the next request in the scenario. Individual scenario executions are independent of each other though (like in the real world where you'd have concurrent clients downloading files concurrently). If you want to test downloads sequentially I'd suggest creating just one virtual user:

```yaml
config:
  phases:
    - arrivalCount: 1
      duration: 1
```

And then using `loop` with a counter to make multiple sequential requests to the endpoint which streams a file back.
