### ISSUE TITLE
What happened to version 2.0?

### ISSUE THREAD

**Issue by wilsson** [artilleryio/artillery#726]
What happened to version 2.0?

**Comment by thu2004** [comment]
Hi
When will you plan to make a new release ? 

The latest on in https://www.npmjs.com/package/artillery is 4 months ago. (1.6-0-28) but there is not such release in this repo "releases" tab.

**Comment by hassy** [comment]
There's no publicly available roadmap for 2.0 at this moment in time. v1.6 is the next planned release. v1.6.0-29 was released earlier this week and is available on npm as usual.
