### ISSUE TITLE
Support localStorage when do a load test for frontend app

### ISSUE THREAD

**Issue by gitlabbin** [artilleryio/artillery#729]
any way to let artillery support localStorage? now it only support cookie,
but more front http apps use localStorage and sessionStorage.

**Comment by SamuelMorales** [comment]
Hey gitlabbin, today I found my self wondering the same question. I see no one aswered this, maybe you have a solution?  Did you manage to simulate or do some localStorage on artillery?

**Comment by hassy** [comment]
`localStorage` is a client-side API and Artillery does not run client-side Javascript (it's not a browser).

As far as the server is concerned, it makes no difference whether a client app uses `localStorage` or not, only what the client sends as an HTTP header or body. So if for example your app uses `localStorage` to store an auth token, you will want to emulate the HTTP request that is made with that token in your Artillery scenario to test the server.
