### ISSUE TITLE
Support something like chancejs for dynamic data generation

### ISSUE THREAD

**Issue by antony** [artilleryio/artillery#73]
In our unit and integration tests, we use http://chancejs.com a lot, for reasons of variation testing, data realism, and general amusement.

I'd like to see the same sort of support in Artillery so that we can do something like

```
"scenarios": [
    {
      "flow": [
        {
          "loop": [
            {"post": {
               "url": "/create-user",
               "json": {
                  "email": "{{ chance.email() }}",
                  "password": "{{ chance.string(length: 10) }}"
               }
            }}
          ],
          "count": 100
        }
      ]
    }
  ]
```

The format of the chance inserts is undetermined, can't immediately think of a nice way to do it.

Right now I'm using mockaroo (some website I found which generates CSVs with chance-like data) to generate CSVs, but it's a pay-for product and it's still very static.

Thoughts?

**Comment by hassy** [comment]
This is a good idea, will need to have a think about the best way to integrate it nicely.

**Comment by danielmihai** [comment]
Hi,

Before you integrate a third-party random content generator, i propose we use the loop clause for generating random variables in the payload section. 

I propose enabling at least a loop clause in conjuction with a random clause. I want to extend the functionality of the payload clause. 

how can we propose, make a user story, contribute and release new features ? 

Thanks, 
Daniel.

**Comment by lightglitch** [comment]
The ability to integrate third-party generators like the one mentioned above or faker.js to create dynamic variable values would be a must. 
When we want to test thousands of users registrations is a pain to create the CSV.

**Comment by mgufrone** [comment]
Is there any plan for this feature? It would be nice to have the mentioned package above or faker.js to generate a lot of data.

**Comment by hassy** [comment]
@lightglitch @mgufrone It's unlikely that this will be implemented as a built-in feature since it can be easily accomplished with a custom JS function (using `faker.js`) - https://artillery.io/docs/testing_http.html#advanced-writing-custom-logic-in-javascript

(The functionality could also be packaged up as an Artillery plugin)

**Comment by lightglitch** [comment]
Didn't notice that, that's enough for me thx.

**Comment by mgufrone** [comment]
okay noted. @hassy thanks. 👍

**Comment by antony** [comment]
I'll probably look at writing this Artillery plugin soon. I'll bear in mind the ability to switch between faker / chance as required.

**Comment by hassy** [comment]
@antono cool! plugin docs are pretty-much non-existent unfortunately ([plugins.md](https://github.com/shoreditch-ops/artillery/blob/master/docs/plugins.md) is the extent of it) but there's a couple of plugins to look at:

- https://github.com/Nordstrom/artillery-plugin-aws-sigv4
- https://github.com/Nordstrom/artillery-plugin-influxdb
- https://github.com/shoreditch-ops/artillery-plugin-statsd

Feel free to message me on Gitter or drop me a line on h@artillery.io if you have any questions.

**Comment by hassy** [comment]
for anyone who might come across this -> https://github.com/beyonk-adventures/artillery-plugin-chance

**Comment by amrsa1** [comment]
what what the conclusion regarding this feature ?
