### ISSUE TITLE
[Improvement] Add ability to generate report without opening default browser

### ISSUE THREAD

**Issue by MakStreamline** [artilleryio/artillery#731]
Would be nice to have this option. Case: on some of out test servers browser is installed and after bunch of runs we have multiply browser instances opened. Which leads to memory usage.
Solution might be like: add cli option to call/block this dependency npm-global/lib/node_modules/artillery/node_modules/opn/index.js

**Comment by hassy** [comment]
You can use the `--output` flag to write the report to a file (which won't open a browser).

We'll probably remove the default behaviour of opening a browser in a future release, but for now `--output` is the way to go.
