### ISSUE TITLE
Provision to print only last output

### ISSUE THREAD

**Issue by vijayant123** [artilleryio/artillery#744]
Hello,
Thank you for this great piece of software. Is there an existing provision to instruct Artillery to only print the last and final stats as output to stdout (or file)? I would only want to get a clear and single output from the test run so that I can process it further for my purposes. Since there is no documented CLI flag for doing this, please consider this as a feature request where I can:
1. Restrict output to last stats only (as opposed to --quiet flag)
2. Set a custom time in seconds (or ms) for the stats output instead of the default 10 seconds

Looking for input from the contributors on this.
Regards,
Vijayant

**Comment by hassy** [comment]
You can use the `-o` option to produce a JSON report, which will contain the final aggregate report and then process that as required.

**Comment by vijayant123** [comment]
Oh I have missed that while reading the docs. Thank you @hassy for your kind help. I will close the issue now.

Regards,
Vijayant

**Comment by krisdover** [comment]
> You can use the -o option to produce a JSON report, which will contain the final aggregate report and then process that as required.

Yes, but there is no way to output this JSON report directly to the console e.g. for piping into `jq`. It has to be stored in a file then processed from there, which isn't very convenient for interactive use. Would be great if we could specify `-o -` to output the JSON to stdout.
