### ISSUE TITLE
 Error: xhr poll error

### ISSUE THREAD

**Issue by RabiRanaEF** [artilleryio/artillery#748]
I want to done a load test on our chat app based on socket io. but i face a problem **xhr poll error**  but when i test same .yaml file on an other app running on my machine (localhost) then i dos't face any issue related to xhr poll error. when i add socketio.transports to ["websocket"] then i get websocket error.
![Capture](https://user-images.githubusercontent.com/55832523/65675884-5ba0db80-e068-11e9-9887-844476732e39.PNG)

**Comment by hassy** [comment]
"xhr poll error" is quite common and does not seem to have a single definitive cause.

Switching transport to `websocket` usually works; what's the WebSocket error you're seeing?

related: #254, #335, #361

**Comment by RabRana** [comment]
Thanks for you quick response. i have error message blow when i use socketio.transports: ["websocket"]. If there is any solution for it kindly suggest me. 
![123](https://user-images.githubusercontent.com/55832523/65683545-e983c300-e076-11e9-9e4c-eb30af0bb54b.PNG)

**Comment by sizovilya** [comment]
I have the same problem. Any ideas ?

**Comment by hassy** [comment]
@sizovilya xhr poll or websocket error?

**Comment by RabiRanaEF** [comment]
@hassy  when i write  below lines
socketio:
    transports: ["websocket"]

then i get websocket error and when i remove above lines then i get xhr poll error.

**Comment by RabiRanaEF** [comment]
@sizovilya  share with me if you get some solutions. i read some issues and i found this error occur due to heavy load on server.

**Comment by sizovilya** [comment]
@RabiRanaEF hi. I have resolved it now. In my case issue was related to nginx proxying.
I resolved error when i set right url to config.target. If you have nginx as a proxy or some cache(like ingress), try to run artillery without proxying, directly to application url.

**Comment by RabiRanaEF** [comment]
@sizovilya  Thanks bro but i can't

**Comment by RabiRanaEF** [comment]
@sizovilya  @hassy  Now i facing timeout error without any changes in app and .yaml file ... What is this firstly i get an xhr error  and now i get timeout error , what is the actual problem with artillery ?

**Comment by RabiRanaEF** [comment]
And how i find the error . "Why i getting Timeout error at all or some users?"

**Comment by RabiRanaEF** [comment]
@hassy  Thanks for  you help i solve my problem. The problem is in  server's port connection.

**Comment by tamaker** [comment]
> @hassy Thanks for you help i solve my problem. The problem is in server's port connection.

Can you share what you did to fix the issue?

**Comment by RajeshVerma7** [comment]
I am getting the same issue. Can you share the fix?

**Comment by adantoscano** [comment]
Same here, I'm trying to connect to my localhost server and I always get xhr or websocket timeout error

```yaml
config:
  target: "http://localhost:3000/"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 500
      arrivalRate: 5
scenarios:
  - engine: "socketio"
    flow:
      - think: 600 # do nothing for 10m and disconnect
```

**Comment by siaminator** [comment]
In my case it was simply related to my server using the socket.io v3, and adding this library resolved everything
https://github.com/ptejada/artillery-engine-socketio-v3

**Comment by taciomcosta** [comment]
It seems to be an incompatibility issue with recent versions of socket.io lib.
What I did was to enable `allowEIO3` flag as pointed out in socket.io docs ([here](https://socket.io/docs/v4/server-initialization/#allowEIO3)). 
It makes the ws server compatible with socket.io v2 (and with artillery as well).

**Comment by sakurarar** [comment]
> 
> 
> It seems to be an incompatibility issue with recent versions of socket.io lib.
> What I did was to enable `allowEIO3` flag as pointed out in socket.io docs ([here](https://socket.io/docs/v4/server-initialization/#allowEIO3)).
> It makes the ws server compatible with socket.io v2 (and with artillery as well).

THANK YOU!

Adding this fixed my problem
