### ISSUE TITLE
Plugin Directory

### ISSUE THREAD

**Issue by antony** [artilleryio/artillery#759]
Excuse my ignorance if I've missed it, but I can't find a plugin directory. Does such a thing exist?

I've published a plugin that I think could be useful to others, but I'm not sure where/how to get it listed.

If it doesn't already exist, it would be good to have a readme section / wiki page to this effect.

**Comment by hassy** [comment]
That does not exist, but it definitely should!

What's the name of your plugin?

**Comment by antony** [comment]
It's here: https://github.com/beyonk-adventures/artillery-plugin-chance - it's very similar to (and in fact based on) a faker plugin I found via google, however it provides flexibility in the data that is generated.

I use it to provide cache-breaking random data to mimic a real-world caching scenario.

I'm also developing another one for setting up test-data from an endpoint, before each scenario is run. I'll publish that one asap.

**Comment by hassy** [comment]
Awesome, thanks @antony!

First version of the updated community page is live now - https://artillery.io/community/

**Comment by antony** [comment]
@hassy Looks awesome - this is great! Thanks!

I'll get my other plugin ready and open a PR :)
