### ISSUE TITLE
What does p99 and p95 mean?

### ISSUE THREAD

**Issue by zhaoyi0113** [artilleryio/artillery#761]
I have read the issue https://github.com/artilleryio/artillery/issues/91 but it doesn't say whether it is average or max of 99% / 95% of requests.  I got a report like this:

```
"latency": {
      "min": 9.2,
      "max": 15530.7,
      "median": 18.6,
      "p95": 6580.9,
      "p99": 9168.2
    }
```

You can see that the median is very small but the p95 and p99 are very large. According to the doc:

```
Request latency is in milliseconds, and p95 and p99 values are the 95th and 99th percentile values (a request latency p99 value of 500ms means that 99 out of 100 requests took 500ms or less to complete).
```

It says 99 out of 100 requests took 500ms or less. Does it cut the top 1% (most expensive) off and measure the rest 99% of requests?  Whether the p99 value is the average or max latency of the 99% of request. Take above as an example, if there is only one request took 9168.2ms, is the `p99` 9168.2ms?

**Comment by hassy** [comment]
`median` is the same as `p50` (and not the same as average, Artillery does not report averages as those are not useful as a measurement of latency). `p99` of 9168.2 means that 99% of requests took less than that amount of time to complete.

**Comment by zhaoyi0113** [comment]
OK so the 9168.2 p99 means the max latency is 9168.2?

**Comment by reyrodrigez** [comment]
yes, max latency for 99% of the users. For the 100% the max is still 15530.7

**Comment by zhaoyi0113** [comment]
Thanks for explaining

**Comment by ajcastro** [comment]
@hassy @reyrodrigez is there a specific number for an ideal or accepted latency?

**Comment by chirag-tokopedia** [comment]
Hi Guys, can you please give an example to understand p50, p95 & p99 and how it will be helpful?

**Comment by michaelsnyder-mb** [comment]
> Hi Guys, can you please give an example to understand p50, p95 & p99 and how it will be helpful?

These numbers are the percentage of the time the value will be above the comparison value. So, p99 means 99% of values are below the p99 value. p95 = 95%, p50 = 50%.
