### ISSUE TITLE
How to record more performance metrics?

### ISSUE THREAD

**Issue by julesm007** [artilleryio/artillery#763]
I would like to record other performance metrics other than latency such as transaction time, response time, averages of those and more. I believe I have to create a plug-in to do this, is there someone that can give me some insight on how to start this process?

**Comment by hassy** [comment]
Artillery provides a way of emitting custom metrics from your JS code which are included in the reports. For example: https://github.com/artilleryio/artillery-plugin-metrics-by-endpoint/blob/master/index.js#L48-L49 Those can be used from any hook function.

What is the difference between response time and latency in your use case? The `artillery-plugin-metrics-by-default` might be handy if you're looking to exclude network round-trip time from latency reports.
