### ISSUE TITLE
posting formdata always sets content-type as multipart/form-data

### ISSUE THREAD

**Issue by ThomasSchumann** [artilleryio/artillery#765]
Minor annoyance - I can't override the content-type header for a formData POST request - it is always set to multipart/form-data
I needed to hit an API that that expected application/x-www-form-urlencoded, and I was able to work around it by URL encoding the formData in the body attribute (rather than the formData attribute) and setting the correct content-type.

**Comment by hassy** [comment]
Just switch to `form` instead of `formData`: https://artillery.io/docs/http-reference/#forms

**Comment by ThomasSchumann** [comment]
Thanks, that looks like it worked.
