### ISSUE TITLE
I guessed it correctly then... But how can I configure this function using json config file that I am creating?

### ISSUE THREAD

**Issue by Lillypot** [artilleryio/artillery#766]
I guessed it correctly then... But how can I configure this function using json config file that I am creating? 

Is there any tests/samples which can illustrate this?

_Originally posted by @venkatesh-tr in https://github.com/artilleryio/artillery/issues/82#issuecomment-216122402_

**Comment by Lillypot** [comment]
I have the same issue - I don't know how to parse the processor into the post using the afterResponse. I  have placed the processor: "./getToken.js" below the phase but it's your authtoken code .. when I try running it as per below I get: TypeError: cb is not a function
    at processFunc (/usr/local/lib/node_modules/artillery/core/lib/engine_http.js:467:66).. please can you help?

before:
  flow:
    -
      post:
        url: "/testviaservlessart/thirdpartyentry/v1/authenticate"

        headers:
          content-type: "application/json"
        json:
          userName: "{{ userName }}"
          password: "{{ password }}"

#        capture:
#          json: "$['id-token']"
#          as: "authToken"
        afterResponse: "authToken"

scenarios:
  -

**Comment by hassy** [comment]
@Lillypot make sure your function implements the interface described in the docs: https://artillery.io/docs/http-reference/#advanced-writing-custom-logic-in-javascript

**Comment by Lillypot** [comment]
> @Lillypot make sure your function implements the interface described in the docs: https://artillery.io/docs/http-reference/#advanced-writing-custom-logic-in-javascript
Thanks Hassy. I managed to get this to work but now I have a new issue.. 
1. I want to include the URL in the setJSONbody 
2. I need to refresh the token every hour  .. please can you advise:

const https = require('https');

module.exports = {
  setJSONBody: setJSONBody,
       getToken:getToken
};


//functions.js

function setJSONBody(requestParams, context, ee, next) {
//         context.vars['url'] = 'https://ppd.driver-vehicle-licensing.api.gov.uk/thirdparty-access/v1/authenticate'
        requestParams.json = {
            userName: 'Artillerymad',
            password: 'UpgradeArt'
        context.vars['url'] = 'https://jooo/loop/v1/authenticate'
        }
        return next()

 }

function  getToken (requestParams, response, context, ee, next) {
    // I use this only for debugging

    console.log(`response body : ${JSON.stringify(response.body)}`)
    var token = response.body['id-token'];
    context.vars['authToken'] = token;
    console.log('authToken:', token);

    return next()
  }

**Comment by Lillypot** [comment]
> @Lillypot make sure your function implements the interface described in the docs: https://artillery.io/docs/http-reference/#advanced-writing-custom-logic-in-javascript

Thanks Hassy. I managed to get this to work but now I have a new issue.. 
1. I want to include the URL in the setJSONbody 
2. I need to refresh the token every hour  .. please can you advise:

const https = require('https');

module.exports = {
  setJSONBody: setJSONBody,
       getToken:getToken
};


//functions.js

function setJSONBody(requestParams, context, ee, next) {
//         context.vars['url'] = 'https://jooo/llop/y-amend/v1/authenticate'
        requestParams.json = {
            userName: 'Artillerymad',
            password: 'UpgradeArt'
        context.vars['url'] = 'https://jooo/loop/v1/authenticate'
        }
        return next()

 }

function  getToken (requestParams, response, context, ee, next) {
    // I use this only for debugging

    console.log(`response body : ${JSON.stringify(response.body)}`)
    var token = response.body['id-token'];
    context.vars['authToken'] = token;
    console.log('authToken:', token);

    return next()
  }
