### ISSUE TITLE
How to disable default report opening in browser?

### ISSUE THREAD

**Issue by guptapranay** [artilleryio/artillery#773]
I want HTML report not to open by default in the browser while giving this command:

`artillery report report.json`

Currently, in docker, this is giving me unhandled promise rejection:

`artillery_1  | (node:24) UnhandledPromiseRejectionWarning: Error: Exited with code 3
artillery_1  |     at ChildProcess.cp.once.code (/usr/local/lib/node_modules/artillery/node_modules/opn/index.js:85:13)`

**Comment by hassy** [comment]
Use the `-o` option - `artillery report --help`

**Comment by guptapranay** [comment]
@hassy -o option tells : 

`Set file to write html report to (will open on browser default)`

Is there a way, NOT to open html report in browser by default

**Comment by hassy** [comment]
Artillery won't try to open the report in a browser when `-o` is used.
