### ISSUE TITLE
Detailed response time metrics with time: true

### ISSUE THREAD

**Issue by Icecold777** [artilleryio/artillery#801]
Hello,

Is it possible to add _time: true_ parameter to request?
For example in beforeRequest custom script or any other way?

It'll help to be more confident in response time statistics and get more details

**according to Request library docs:**
timingPhases
Contains the durations of each request phase. If there were redirects, the properties reflect the timings of the final request in the redirect chain:

- wait: Duration of socket initialization (timings.socket)
- dns: Duration of DNS lookup (timings.lookup - timings.socket)
- tcp: Duration of TCP connection (timings.connect - timings.socket)
- firstByte: Duration of HTTP server response (timings.response - timings.connect)
- download: Duration of HTTP download (timings.end - timings.response)
- total: Duration entire HTTP round-trip (timings.end)

```
request.get({
  url : 'http://example.com',
  time : true
},function(err, response){
  console.log('Request time in ms', response.elapsedTime);
});
```

**Comment by Icecold777** [comment]
Surprisingly it works just adding to .yml script request part 
- flow:
    - get:
        url: "{{ path }}"
        name: "PDP"
        time: true
        afterResponse: "reportLatency"

reportLatency.js 
```

function reportLatency(req, res, context, events, done) {
        events.emit('customStat', { stat: `waitTime for ${req.name || req.url}`, value: res.timingPhases.wait });
	events.emit('customStat', { stat: `dnsTime for ${req.name || req.url}`, value: res.timingPhases.dns });
	events.emit('customStat', { stat: `tcpTime for ${req.name || req.url}`, value: res.timingPhases.tcp });
	events.emit('customStat', { stat: `firstByteTime for ${req.name || req.url}`, value: res.timingPhases.firstByte });
	events.emit('customStat', { stat: `downloadTime for ${req.name || req.url}`, value: res.timingPhases.download });
	events.emit('customStat', { stat: `totalTime for ${req.name || req.url}`, value: res.timingPhases.total });
  
  return done();
}
```
I've compared total time and time metrics collected with solution provided in #231
There is difference  10-100 ms 

```
CalcTimings 1959
TotalTimingsDetailed 1905.5116560000001
CalcTimings 1189
TotalTimingsDetailed 1179.3357940000005
CalcTimings 1190
TotalTimingsDetailed 1180.9426109999995
CalcTimings 1290
TotalTimingsDetailed 1280.4177089999994

```

**Comment by hassy** [comment]
Thanks @Icecold777. We need to expose these metrics natively once work on #802 is finished.

**Comment by Shazwazza** [comment]
This would be fantastic :) Is the plan to keep custom metrics in this plugin https://github.com/artilleryio/artillery-plugin-metrics-by-endpoint or add them natively?

**Comment by dominikstohl** [comment]
Are there any news on the question asked by @Shazwazza ?
otherwise I would try to implement this in the mentioned plugin and enable with config flag.

**Comment by hassy** [comment]
hi @dominikstohl 👋  Artillery v2 includes those out-of-the-box now. You can enable extra metrics with:

```yaml
config:
  http:
    extendedMetrics: true
```
or by adding ` --overrides '{"config":{"http":{"extendedMetrics":true}}}'` to `artillery run`.

(not documented yet, but will be soon)

**Comment by hassy** [comment]
aaand documented: https://www.artillery.io/docs/guides/guides/http-reference#additional-performance-metrics-v2

closing :)

**Comment by dominikstohl** [comment]
hi @hassy , thanks for your informations and for adding this in the docs. <3

I have another question: I see this in the console, but is it available in the report?

I see the implemention in artillery, so i can add it via a custom afterResponse function to the report. But is there something to do to add this to the report by default?

Thanks!

**Comment by hassy** [comment]
Yes @dominikstohl, they should show up in the report too. If not, please file a bug. 😄
