### ISSUE TITLE
Artillery detecting incoming from 127.0.0.1

### ISSUE THREAD

**Issue by Paladin-z** [artilleryio/artillery#808]
When looking at /var/log/user.log I see repititions of

    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 8080
    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 123
    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 8080
    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 8080
    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 8080
    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 123
    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 8080
    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 8080
    Feb 24 06:32:24 server400 Artillery[INFO]: Honeypot detected incoming
    connection from 127.0.0.1 to port 808

Filling the log space and making the system unresponsive, Debian Buster with Swizzin installed. Currently 36GB

**Comment by hassy** [comment]
That does not look like a log from Artillery.

**Comment by Paladin-z** [comment]
It doesn't? Why's that when it explicitely states that it's from Artillery? "Artillery[INFO]: Honeypot detected ..." ?

**Comment by hassy** [comment]
I think this is the Artillery you're after: https://github.com/BinaryDefense/artillery :)
