### ISSUE TITLE
[Request] Add artillery-engine-grpc to artillery.io/community

### ISSUE THREAD

**Issue by kenju** [artilleryio/artillery#810]
Would you add https://github.com/kenju/artillery-engine-grpc to the list of https://artillery.io/community/ ? 😉 

> Search NPM for packages whose names start with artillery-plugin or artillery-engine for more. If you've made a new plugin or engine and would like to see it here, please let us know via team@artillery.io or via Github Issues.

**Comment by kenju** [comment]
@hassy would you consider this request?

**Comment by hassy** [comment]
@kenju apologies for taking a while, yes definitely, the plugin is now on the Community page - https://artillery.io/community/ Thank you!

If you'd like a contributor-special Artillery hoodie drop me a line on h@artillery.io with size + an address we can post it to.

**Comment by kenju** [comment]
> the plugin is now on the Community page - https://artillery.io/community/ Thank you!

Thank you very much 😉 It is really great that you take much care of the artillery community! 👏 

> If you'd like a contributor-special Artillery hoodie drop me a line on h@artillery.io with size + an address we can post it to.

Fantastic. I've sent you an email with size + address.

**Comment by kenju** [comment]
@hassy 

Did you get my email?
