### ISSUE TITLE
Subsequent Flow calls don't run after failed Capture

### ISSUE THREAD

**Issue by bernardobridge** [artilleryio/artillery#812]
To replicate:

[sample.yml.zip](https://github.com/artilleryio/artillery/files/4312892/sample.yml.zip)

Basically it appears that when the capture part of the script fails for some reason (in this case it is failing on the regex), the subsequent flows do not run. The bad part is that there is no indicator in the output of it erroring, so it was quite hard to debug (only by digging in with DEBUG=* was I able to figure out it must be because of that).

**Comment by hassy** [comment]
Thanks for the detail @bernardobridge! `capture` is always strict, i.e. if it fails then the virtual user stop, but it does make sense to be able to turn that off in some cases. There should also always be output in the logs when a capture fails.
