### ISSUE TITLE
publishing results to external system like New Relic

### ISSUE THREAD

**Issue by ScottChapman** [artilleryio/artillery#816]
New Relic is clearly not support by the existing plugin, I'd be happy to contribute to that but am looking for any documentation on developing that.

**Comment by ScottChapman** [comment]
found it.

**Comment by rv-bnowak** [comment]
> found it.

Where did you find this @ScottChapman ?

**Comment by plazmist** [comment]
> found it.

WTF, really. @ScottChapman did you ever find exactly your question without answer but with comment like yours? What did you feel?
