### ISSUE TITLE
Getting "Error: socket hang up" error

### ISSUE THREAD

**Issue by himtar12** [artilleryio/artillery#823]
Usually I get this error when sending requests more than 1k. Many times I get this error. Any idea why ? 

below is the log:

> Error: socket hang up
> Report @ 20:43:09(+0530) 2020-04-28
> Elapsed time: 28 minutes, 56 seconds
>   Scenarios launched:  0
>   Scenarios completed: 0
>   Requests completed:  15
>   Mean response/sec: 2.99
>   Response time (msec):
>     min: 169.3
>     max: 248.3
>     median: 236.2
>     p95: 248.3
>     p99: 248.3
>   Codes:
>     200: 15
>   Errors:
>     ECONNRESET: 1
> 
> All virtual users finished
> Summary report @ 20:43:09(+0530) 2020-04-28
>   Scenarios launched:  1
>   Scenarios completed: 0
>   Requests completed:  2950
>   Mean response/sec: 1.7
>   Response time (msec):
>     min: 160.3
>     max: 2780
>     median: 237.4
>     p95: 356.5
>     p99: 890.2
>   Scenario counts:
>     114621: Verify /test
>   Codes:
>     200: 2950
>   Errors:
>     ECONNRESET: 1

**Comment by hassy** [comment]
`ECONNRESET` means the other side (i.e. the server) closed the connection. Typical reasons are server overload or a short keep-alive period. It usually indicates an issue with the system under test uncovered by the load test.

**Comment by himtar12** [comment]
Thanks @hassy
