### ISSUE TITLE
Is it possible to get latency by request ?

### ISSUE THREAD

**Issue by marwen-abid** [artilleryio/artillery#834]
I have a scenario that does a set of requests ( a couple of POSTs and a GET ). 
But the report seem to be showing Latency data by scenario. 
I need an extra level of granularity that would show latency per request. Is that possible ? Thank you for your help. 

Edit: I found the following but it didn't seem to help: https://github.com/artilleryio/artillery/issues/801

**Comment by hassy** [comment]
Yep, use https://github.com/artilleryio/artillery-plugin-metrics-by-endpoint

**Comment by marwen-abid** [comment]
Thank you! That's very helpful.
