### ISSUE TITLE
When using datadog eu reporting does not work.

### ISSUE THREAD

**Issue by kimpellikaan** [artilleryio/artillery#856]
### Issue
Metrics are not shown in datadog.

### Quick fix
In node_modules/datadog-metrics/node_modules/dogapi/lib/client.js set the `this.api_host` to `app.datadoghq.eu`.

### Solution direction
artillery-plugin-publish-metrics uses datadog-metrics to report metrics over the HTTP api. datadog-metrics in turn uses dogapi which is quite old. I expect during that time Datadog did not have an EU cluster.

In node_modules/datadog-metrics/node_modules/dogapi/lib/client.js the api_host is a static value:
```
var client = function(){
    this.api_key = null;
    this.app_key = null;
    this.proxy_agent = null;
    this.api_version = "v1";
    this.api_host = "app.datadoghq.com";
};
```

This should be dynamic so it can facilitate both `app.datadoghq.com` and `app.datadoghq.eu`.

**Comment by bobpozun** [comment]
I am using us5 and ran into a similar issue. It appears that even if you're using the api (not an agent) you can use the apiHost param. I *think* that solves your issue and is probably just a documentation update.

  plugins:
    publish-metrics:
      - type: datadog
        apiKey: "{{ $processEnvironment.DD_API_KEY }}"
        apiHost: "api.us5.datadoghq.com"
