### ISSUE TITLE
Vulnerability present - dot-prop

### ISSUE THREAD

**Issue by cmdcarini** [artilleryio/artillery#865]
There is a vulnerability present in the following dependency tree, please resolve if possible, fix available for dot-prop in versions >=5.1.1

artillery@1.6.1
│ └─┬ update-notifier@2.5.0
│   └─┬ configstore@3.1.2
│     └── dot-prop@4.2.0

**Comment by hassy** [comment]
closed by #866, thank you @cmdcarini

**Comment by tsondergaard** [comment]
Thanks @hassy! Eagerly awaiting the next artillery release so “npm audit” will pass on my CI again. When do you expect it will be?

**Comment by Tenkir** [comment]
This does not resolve the vulnerability with `update-notifier`.
