### ISSUE TITLE
how to add dynamic query string to target in ws engine?

### ISSUE THREAD

**Issue by GNSubrahmanyam** [artilleryio/artillery#869]

**Comment by GNSubrahmanyam** [comment]
@hassy any updates on this?

**Comment by GNSubrahmanyam** [comment]
@hassy any updates on this?

**Comment by nightwolfz** [comment]
I need this feature as well...

**Comment by GNSubrahmanyam** [comment]
https://github.com/artilleryio/artillery/issues/663

Refer pull request: https://github.com/artilleryio/artillery/pull/1119
