### ISSUE TITLE
Accessing interpolated request in beforeRequest

### ISSUE THREAD

**Issue by thekevinbrown** [artilleryio/artillery#892]
Right now I'm seeing:

```
{
   "myKey": "{{variable}}"
}
```
in `requestParams.json`. When the request actually goes out the variable substitution happens correctly. I see in other issues that `beforeRequest` should have already done the variable substitution. 

How do I get access to the request body with variables substituted in a `beforeRequest` function? I can't see the body anywhere but in `requestParams.json` so far.

**Comment by rmjwilbur** [comment]
Same issue for me on url. I need to sign requests for AWS and can't access the resolved values.

**Comment by rmjwilbur** [comment]
@thekevinbrown - clarity on this has been provided by @hassy - see: https://github.com/artilleryio/artillery/issues/189#issuecomment-1561281773

I am able to get the substituted values like this:
```
console.log('resolved:', global.artillery.util.template(requestParams.json, { vars: context.vars }));
```

**Comment by hassy** [comment]
thanks for updating this issue @rmjwilbur! we'll update the docs to include this info as well!
