### ISSUE TITLE
WARN deprecated har-validator@5.1.5: this library is no longer supported

### ISSUE THREAD

**Issue by openaspace** [artilleryio/artillery#895]
npm install -g artillery-plugin-hls
loadDep:global -> afterAd | |#######################----------------------------------------------------------------|
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/lib
`-- artillery-plugin-hls@0.0.3 
  `-- m3u8-parser@4.5.0 
    `-- @videojs/vhs-utils@2.2.1

**Comment by mlosa** [comment]
Same issue.

[root@ip-192-168-255-200 ~]# node -e "console.log('Running Node.js ' + process.version)"
Running Node.js v15.3.0
[root@ip-192-168-255-200 ~]# npm -v
7.0.14

**Comment by menghu1994** [comment]
Lack of **package-lock.json** file or har-validator@5.1.5 is in this file;
Solution
**npm install** to rewrite

**Comment by umesha-1996** [comment]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

i cann't be install angular-cli i have this error.can u help me??

**Comment by franfonse** [comment]
Same issue as @umesha-1996 

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

Any solutions?

**Comment by hassy** [comment]
We'll be upgrading the HLS plugin to remove the dependency on `request` which brings in `har-validator`. 

For other packages such as `angular-cli` which show the same warning, please report the issue to the authors of those packages.

**Comment by nvnkmr16** [comment]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

any solutions ?

**Comment by deszczur** [comment]
bump

**Comment by MadhurimaPaul-87** [comment]
npm WARN deprecated request@2.88.2: request has been deprecated, see request/request#3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

any solutions ?

**Comment by nvnkmr16** [comment]
Just uninstall the Current Node in the control panel and install the Stable Node version which is 14.16.0 LTS (Current Stable and Recommended Version) and then try to install the Angular CLI using the same command. It works.

**Comment by bigbigrock** [comment]
any solutions?
![image](https://user-images.githubusercontent.com/46518767/114851231-31fb0100-9e14-11eb-9a8f-f7a46bab1008.png)

**Comment by Kirti-22** [comment]
> Just uninstall the Current Node in the control panel and install the Stable Node version which is 14.16.0 LTS (Current Stable and Recommended Version) and then try to install the Angular CLI using the same command. It works.

No, it doesn't worked for me.....

**Comment by Kirti-22** [comment]
npm install -g @angular/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported      
[       ...........] / postinstall: sill install executeAc


this error occured even after uninstalling and reinstalling node.js.... any solution ???

**Comment by hassy** [comment]
Artillery no longer uses request.js - for other packages such as angular/cli, please report issues in their respective issue trackers.
