### ISSUE TITLE
Can't execute test, where is the problem?

### ISSUE THREAD

**Issue by openaspace** [artilleryio/artillery#896]
Hello, I can't execute any test..! where i'm wrong?

**Conf file:**
`config:
  target: "https://server1.example.com:8081"
  plugins:
    hls: {}

scenarios:
  - name: "Stream an HLS video"
    flow:
      - get:
          url: "/test/live/playlist.m3u8"
          hls:
            concurrency: 10
            streamSelector:
              resolution:
                width: 1920
                height: 1080
            throttle: 100
`
**RESPONSE**

root@FFMPEG-Encoder:~# artillery run hls.yaml
Report @ 22:35:14(+0100) 2020-11-03
Elapsed time: 1 second
  Scenarios launched:  0
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN

All virtual users finished
Summary report @ 22:35:14(+0100) 2020-11-03
  Scenarios launched:  0
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:

**Comment by hassy** [comment]
You need to tell Artillery to create some virtual users with a `config.phases` section

https://artillery.io/docs/guides/guides/test-script-reference.html#Load-Phases
