### ISSUE TITLE
Percentile aggregation for Artillery Pro

### ISSUE THREAD

**Issue by danjamesmay** [artilleryio/artillery#898]
I'm wondering how percentile aggregations work when running Artillery in a distributed fashion (e.g. via Artillery Pro) vs on a single host.

I am currently configuring Artillery (non-pro version) to send metrics to Datadog via the HTTP API.

I'm looking to make use of Artillery Pro, but it would seem that for percentiles to be calculated correctly, they would need to be sent as a distribution metric, of which the percentiles [are then calculated by Datadog](https://docs.datadoghq.com/metrics/distributions/#counting-distribution-metrics).

I was looking at the [stats module](https://github.com/artilleryio/artillery/blob/master/core/lib/stats2.js#L157), and I'm not sure how percentiles are aggregated when running Artillery distributed via Artillery Pro.

Would it be possible to elaborate on how metrics are calculated with Artillery Pro, specifically percentiles?

**Comment by hassy** [comment]
hi @danjamesmay, Artillery Pro aggregates response time distributions itself (using HDR histograms - http://hdrhistogram.org), the summaries are then sent to Datadog as gauges. This means that aggregations work regardless of the monitoring system used, as some systems don't support global distributions, and afaik they're still in beta even in Datadog.
