### ISSUE TITLE
Font size is too small in html report

### ISSUE THREAD

**Issue by 4ekki** [artilleryio/artillery#899]
Font size is so small, that chart legend is barely visible: 
![image](https://user-images.githubusercontent.com/38757986/98832710-3038a600-244e-11eb-8406-a2f17f654798.png)

Screen resolution is 1920*1080. 
Chrome Version 86.0.4240.183 (Official Build) (64-bit)
------------ Version Info ------------
Artillery: 1.6.1
Artillery Pro: not installed (https://artillery.io/pro)
Node.js: v10.16.0
OS: win32/x64

**Comment by hassy** [comment]
fixed in #1203
