### ISSUE TITLE
Getting 'JavaScript heap out of memory' error on JS hooks functions execution

### ISSUE THREAD

**Issue by himtar12** [artilleryio/artillery#907]
Hey @hassy 

I am getting below error on executing one of the JS hooks through Get request. Any idea what does it mean?
Looks like artillery is not able to withstand the load of JS complex execution scenarios.

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6AA2C5EBF napi_wrap+114095
 2: 00007FF6AA270B46 v8::base::CPU::has_sse+66998
 3: 00007FF6AA271946 v8::base::CPU::has_sse+70582
 4: 00007FF6AAA86E4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6AAA6EF21 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF6AA93B18C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF6AA9463C0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF6AA942EE4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF6AA9386E3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF6AA936D54 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF6AA95809D v8::internal::Factory::NewFillerObject+61
12: 00007FF6AA6BE06F v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1295
13: 00007FF6AAEDB3BD v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 000002E3DDEC3344
Unexpected error, Artillery shutting down.
Error: Command failed: node node_modules/artillery/bin/artillery run -c config/functional.yml -o results\regression_aif_verifyWorkpermitLinksForWO_test.json regression\assets\aif\aif_verifyWorkpermitLinksForWO_test.yml -e staging -v {\"auth\":\"N-kNJ[.3bO?UOOKevBXHLDepn8ddy98k\",\"environment\":\"staging\",\"requestsCount\":0,\"error\":\"\",\"retryCount\":0}
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6AA2C5EBF napi_wrap+114095
 2: 00007FF6AA270B46 v8::base::CPU::has_sse+66998
 3: 00007FF6AA271946 v8::base::CPU::has_sse+70582
 4: 00007FF6AAA86E4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6AAA6EF21 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF6AA93B18C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF6AA9463C0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF6AA942EE4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF6AA9386E3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF6AA936D54 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF6AA95809D v8::internal::Factory::NewFillerObject+61
12: 00007FF6AA6BE06F v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1295
13: 00007FF6AAEDB3BD v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 000002E3DDEC3344`

**Comment by hassy** [comment]
Have you tried increasing the amount of memory available? The error means Node.js is running out of memory. If you're seeing this behavior only when using hook functions, the issue could be down to a memory leak in that code. This can also happen if you're processing large responses from the server at high concurrency.

**Comment by himtar12** [comment]
I am processing huge responses but only with a single get request. I am also getting below warning as well.  Anyways, I will try to fix the memory leak if it is due to it. Thanks.

```
Warning:
CPU usage of Artillery seems to be very high (pids: [object Object])
which may severely affect its performance.
See https://artillery.io/docs/faq/#high-cpu-warnings for details.
```

**Comment by alanyong91** [comment]
@himtar12 you can refer the CPU issue from [faq](https://artillery.io/docs/faq/)

 I think the warning came up because your CPU can't handle the load. 

Reduce `arrivalRate` values could help.
