### ISSUE TITLE
Distributed load test using Artillery.io on standalone servers

### ISSUE THREAD

**Issue by abhayshankar** [artilleryio/artillery#918]
I have a requirement to run distributed load test using Artillery.io however not using EC2 instances but on standalone servers as the API's to be tested are not accessible from external network.
Is there any way to aggregate multiple reports from artillery runs in seperate servers and produce a single HTML report with all the data ?

**Comment by hassy** [comment]
Replied in https://github.com/artilleryio/artillery/issues/47#issuecomment-759360903.

I'll add here that if the service itself is hosted on AWS, you can use Artillery Pro to load test without exposing the service externally. Otherwise, sending metrics to a central store could be an acceptable workaround.

**Comment by kilian-bryon** [comment]
Hi, so I'm getting back on this topic. We are 2 years further and I was searching for a solution to use Artillery with distributed load but without using AWS. My company has its own data center and want's to use these for load generation and gather all reports on 1 central load controller. Any idea if there are updates on this or on how to achieve this goal? 

Thanks in advance!

**Comment by hassy** [comment]
hi @kilian-bryon & @davitol 👋 If running on AWS is not an option (Artillery has built-in support for running on AWS Lambda now - [blog post](https://www.artillery.io/blog/open-source-distributed-load-testing-with-lambda)), then the best solution is to run multiple instances of Artillery on different machines (there's a few ways this can be orchestrated, e.g. `ssh` + a shell script, Ansible etc), and configuring an [external metric target](https://www.artillery.io/docs/guides/plugins/plugin-publish-metrics) in Artillery to have all metrics aggregated centrally

**Comment by kilian-bryon** [comment]
Hi @hassy, running Artillery with AWS is indeed not an option because of security reasons (they are fairly strict on this and this is why they have their own data center). I was wondering if Artillery can be combined with the use of Kubernetes, or would Ansible be a better solution?

**Comment by hassy** [comment]
@kilian-bryon Kubernetes support is something we will add to Artillery soon (though we don't have an ETA). In the meantime, something like Ansible to run multiple instances of Artillery with an external metric destination should work well.

**Comment by kilian-bryon** [comment]
@hassy I have to make multiple pseudo-random scenarios with the Playwright engine. Then I have to execute these scripts on many hosts. I was thinking about a way for Ansible to launch multiple Docker containers, each containing 1 scenario to execute on multiple hosts. So multiple host servers, each containing multiple Docker containers, that are each executing a pseudo-random scene. All this data has to be sent to an external metric target.

Do you think this will be possible?

Kr,
Kilian

**Comment by kilian-bryon** [comment]
> @kilian-bryon Kubernetes support is something we will add to Artillery soon (though we don't have an ETA). In the meantime, something like Ansible to run multiple instances of Artillery with an external metric destination should work well.

Could I scale it up to say, 10 000 Virtual users when having no restrictions on hardware hosts?
