### ISSUE TITLE
HTTP: Report stats per endpoint

### ISSUE THREAD

**Issue by hassy** [artilleryio/artillery#92]
It can be very useful to see latency reported separately for different endpoints, for example many tests will have auth calls in them before calling other endpoints/services the metrics for which the user is really interested in.

**Comment by lucasvinals** [comment]
Maybe related? #258 This feature would be really helpful.

**Comment by tsondergaard** [comment]
Isn't this issue adequately addressed by [artillery-plugin-metrics-by-endpoint](https://www.npmjs.com/package/artillery-plugin-metrics-by-endpoint)?

**Comment by hassy** [comment]
Yes 💯  @tsondergaard! thank you

Can't believe it's been almost 5 years since I created this issue 😆
