### ISSUE TITLE
README.md Broken Links

### ISSUE THREAD

**Issue by ericmgoeken** [artilleryio/artillery#936]
The following links are broken:

- Artillery Getting Started Guide
- professional services page

Although maybe not the right place for it, but there are broken links in the docs too. 
For example the next button at the bottom of: https://artillery.io/docs/guides/getting-started/core-concepts.html

**Comment by hassy** [comment]
Thank you for letting us know @ericmgoeken! The README should be fixed.

It looks like the logic to determine the URL of the next page needs a fix in our documentation generator.

**Comment by hassy** [comment]
should be fixed now 🥳
