### ISSUE TITLE
Cannot find module '../util'

### ISSUE THREAD

**Issue by dmackinn** [artilleryio/artillery#940]
Just installed as a local dependency on a brand new project with nothing else in it and I get an error when trying to run artillery dino

> artillery dino

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '../util'

I'm running node 12.18.2, npm 6.14.5 on macOS Catalina 10.15.7. No other packages are installed on this project and I followed the documentation here: https://artillery.io/docs/guides/getting-started/installing-artillery.html

**Comment by dmackinn** [comment]
Here are the contents of my package.json
`{
    "name": "loadtest",
    "version": "1.0.0",
    "private": true,
    "scripts": {
        "test": "artillery dino"
    },
    "dependencies": {
        "artillery": "^2.0.0-dev1"
    }
}
`

**Comment by hassy** [comment]
Oops, fixed! 👀 When we said "expect things to break" in the `2.0.0-dev` release line, we didn't _quite_ mean that everything is going to be broken.

The dino (and everything else) should be back in action in `v2.0.0-dev2`, which should be published on `npm` shortly.

```
artillery dino -m "Thanks you @dmackinn\!"
 -----------------------
< Thanks you @dmackinn! >
 -----------------------
          \
           \
               __
              / _)
     _/\/\/\_/ /
   _|         /
 _|  (  | (  |
/__.-'|_|--|_|
```
