### ISSUE TITLE
Testing against a WebSocket using a Proxy

### ISSUE THREAD

**Issue by Samuel3** [artilleryio/artillery#961]
Hey there,

Is it possible to use artillery for WebSockets using a proxy? I found that testing http is possible with a proxy but for WebSockets I could not find anything. I tried to set env vars HTTP_PROXY and HTTPS_PROXY but that did not worked.

Thanks in advance

**Comment by hassy** [comment]
Hi @Samuel3👋 Using WebSocket with a proxy isn't supported right now.

In case anyone is looking and has some spare time to put together a PR, it looks fairly straightforward with the `ws` library which Artillery uses:

https://github.com/websockets/ws/issues/1276#issuecomment-357355842
