### ISSUE TITLE
TypeError: Cannot read property 'createScenario' of undefined in artillery

### ISSUE THREAD

**Issue by barsaranjeet15** [artilleryio/artillery#966]
TypeError: Cannot read property 'createScenario' of undefined

config:
  target: "http://localhost:3001"
  socketio:
    transports: ["websocket"]
  phases:   
    - duration: 10
      arrivalRate: 1
scenarios:
  - engine: "socketio-v3"
    flow:
      - emit:
          channel: "message"
          data: "hello"

**Comment by hassy** [comment]
hi @barsaranjeet15, are there any other warnings or errors printed in the console? what version of Artillery is that on? (`artillery -V`)

**Comment by barsaranjeet15** [comment]
hello i was able to find to solution by implementing socketio v3 because i am using socket io v4 that's why

so here is my solution if anyone get this kind of error in future


config:
  target: "http://localhost:3001"
  socketio:
    transports: ["websocket"]
  phases:   
    - duration: 60
      arrivalRate: 100
  engines:
   socketio-v3: {}
scenarios:
  - engine: "socketio-v3"
    flow:
      - emit: ["message", "hello"]
      - emit: ["message","world"]
      - emit: ["salutations","1","2","3"]
