### ISSUE TITLE
[WebSockets] How to add a parameter to a websocket connection

### ISSUE THREAD

**Issue by johanparmar** [artilleryio/artillery#976]
Hi,

We have developed a websocket server where the id of client is sent in the url: wss://<server-path>/<id>. Now we want to load test the server with artillery and  we want to pull this id from a csv file and it will be unique for each client connecting to the server. 

I have seen examples on how to do this with a Http REST Api  but not for websockets. Is it even possible?

**Comment by hassy** [comment]
not supported right now, but... really should be

**Comment by simonbuehler** [comment]
something like https://github.com/artilleryio/artillery/pull/711 ?

**Comment by hassy** [comment]
The problem is more to do with the fact that when `target` is being run through templates, user context variables aren't available yet.

Btw https://github.com/ptejada/artillery-engine-socketio-v3 has support for variable args in Socket.io

**Comment by johanparmar** [comment]
Thanks for your input! Unfortunately I'm not running socket.io as backend/engine
. Are there any plans to support this feature in the future?

**Comment by johanparmar** [comment]
Closing this issue with the hope that this might implemented in the near future

**Comment by nightwolfz** [comment]
In the meantime, you can hack directly into the matrix and change the code


![image](https://user-images.githubusercontent.com/805022/118395591-7cf27900-b64b-11eb-91f3-b30e69cc588e.png)

**Comment by nightwolfz** [comment]
Since it barely takes 5 minutes to add this change, here's the lazy change you can do it by hacking directly into the matrix

![image](https://user-images.githubusercontent.com/805022/118395868-ef178d80-b64c-11eb-8893-491139566792.png)
