### ISSUE TITLE
variables on command line won't work

### ISSUE THREAD

**Issue by FredCni** [artilleryio/artillery#984]
Environment: windows / command prompt

When running:
artillery run test.yml --target "..." -v '{"token": "value"}'

I get an error:
Variable definition is not valid JSON. Correct example: -v '{"var1": "value1", "var2": "value2"}'

It seems like the parsing fails (even with the provided example)

**Comment by hassy** [comment]
hi @FredCni 👋 that's a known issue with quoting on Windows:

https://github.com/artilleryio/artillery/issues/710#issuecomment-699522332

Powershell (if it's an option) may be easier to get working.

**Comment by FredCni** [comment]
Thanks.

I've been able to make it work by escaping the internal double quotes:
`--variables "{\"token\": \"value\"}"`

This should probably make its way in the docs.

**Comment by hassy** [comment]
Yes, definitely! Thanks for confirming quoting works @FredCni!
