### ISSUE TITLE
Broken link to FAQ in runtime errors

### ISSUE THREAD

**Issue by BePo65** [artilleryio/artillery#985]
I'm starting using artillery for load testing my server. On my first runs I get the following warning:
> Warning: High CPU usage warning (pids: 11520).
See https://artillery.io/docs/faq/#high-cpu-warnings for details.

Unluckily there is no path `/docs/faq/` in the `https://artillery.io` site and even google knows nothing about faqs.
Any help appreciated.

**Comment by dennmart** [comment]
This warning message looks to have been removed for the Artillery 2.0 release: #838. I'm not sure when this version is going to be released, though.

**Comment by hassy** [comment]
Sorry about that @BePo65! The warning usually means that the arrival rate is too high (e.g. >1000) - you can try reducing that. Sometimes it may have to do with custom JS code.

**Comment by BePo65** [comment]
Thanks for the help
